### ISSUE TITLE
Client close with outfit 3x3

### ISSUE THREAD

**Issue by k7aesa7r** [edubart/otclient#1000]
Tfs 1.3 client 10.98, using latest source of otclient~~

client closes when i use an outfit 3x3 with those config:
width:3 height:3 layers:2 paternx: 4 patterny:3 patternz:2 animations:9

![objectbuilder__frame_edit_2018-11-26_01-00-07](https://user-images.githubusercontent.com/6724006/48990707-ae42fb80-f116-11e8-8ed8-b61060f856a1.png)

It happens with ANY outfit using those values. if i use all above values with patternz:1 instead 2 it dont closes

**Comment by Riverlance** [comment]
Try to duplicate an already existent outfit the most similar as possible to what you are needing.
Then, edit if it's needed and setup the sprites overwriting the previous one.

I always do that instead of creating a new one attributing each one value.

**Comment by k7aesa7r** [comment]
Theres no outfit 3x3 using layers so i cant duplicate it.

**Comment by k7aesa7r** [comment]
So? Can someone confirm it also happens there in yours client?

**Comment by okk3** [comment]
Can you supply us with the crash log? It's kind of hard and demotivating to have to recreate the whole scenario in order to help out.
