### ISSUE TITLE
Enable/Disable Anti-Aliasing via Options Menu

### ISSUE THREAD

**Issue by JosensGames** [edubart/otclient#1009]
Hello, I tried so many times add a option that enable or disable the anti-aliasing mode in the game, somebody know how to do it correctly 🤒 ?

**Comment by iryont** [comment]
Hello

What did you try to do yourself, exactly?

**Comment by JosensGames** [comment]
First, add a new option in this options menu:

https://camo.githubusercontent.com/9f100a65440ebc046ed8d0664028bf2484c5063b/687474703a2f2f692e696d6775722e636f6d2f6271474e73536d2e706e67

This is for manage a variable created by me in the source, but this is the problem, I cannot find a way to add a new option.

**Comment by JosensGames** [comment]
Bump

**Comment by VagnerDomingues** [comment]
this interest me too, could you share how you manage to accomplish the pixelated art style in the client? 

so back to the answer... to add an option there you must create an option checkbox like this:

``` 
  OptionCheckBox
    id: pixelatedArt
    !text: tr('Disable Anti Aliasingl')
```
in the display order you want and inside the file: 
<b>modules/client_options/game.otui</b>

and the variable that must disable the AA should be @: 
<b>modules/client_options/options.lua</b>

i believe seeing these files you will know what to do, cheers!

**Comment by VagnerDomingues** [comment]
btw this ain't an issue its much more like a feature you should try to create a pull request when it's finished so that maintainers could add that to the client, pretty nice indeed!
