### ISSUE TITLE
Compatibillity Issues

### ISSUE THREAD

**Issue by cjrz74** [edubart/otclient#1012]
Compiling Client in Win32 mode it seems some players cannot open the client. I followed all the tutorials and it compiles correctly. The person who cannot open their client just crashes on startup. They are on a Windows 7 computer and other well known OTS open on their computer. Anti-Virus was disabled.

I have no problem opening the client.

Been trying to figure out for a while cant seem to get it pinned down.

**Comment by VagnerDomingues** [comment]
Does the crash has any exception error warning? for me it just looks like missing DLLs...
try extracting these in the client folder:
http://www.mediafire.com/file/898sy237xnd39cj/DLLs.rar

**Comment by cjrz74** [comment]
They have the DLL's
