### ISSUE TITLE
Compatibility Issues

### ISSUE THREAD

**Issue by cjrz74** [edubart/otclient#1014]
Compiling Client in Win32 mode it seems some players cannot open the client. I followed all the tutorials and it compiles correctly. The person who cannot open their client just crashes on startup. They are on a Windows 7 computer and other well known OTS open on their computer. Anti-Virus was disabled.

I have no problem opening the client.

There is no crash error the client just doesn't open.

Seems about 85% of ppl can open the client? The person opening has a toaster it looks like.
Using MSV, and it happens for both dx9 and opengl clients. It seems some servers have figured this out and they can open the client(Medivia).

Been trying to figure out for a while cant seem to get it pinned down.

**Comment by iryont** [comment]
Can be countless of things. If you do not provide a stacktrace or similar indicator a thing which is failing then this issue is pointless. Also, create an issue using the provided template.
