### ISSUE TITLE
OTCLient doesn't start on latest windows 10 pro build

### ISSUE THREAD

**Issue by tarantonio** [edubart/otclient#1017]
I compiled OTClient in Visual Studio 2017 with vcpkg method, Release x64. (also tried the other methods, mingw and msvs17 with sdk, with the same problem)
On Windows 10 pro version 1809, build 17763.316 exe doesn't start.
I tried the same exe on another pc with version 1803, build 17134.590 and exe starts without problem.

**Comment by iryont** [comment]
Try to locate the problem by debugging the game client since your issue does not contain any useful information. Also, please follow the template of the issue next time.

**Comment by cjrz74** [comment]
https://i.imgur.com/JZHcg6I.png
