### ISSUE TITLE
unable to get "default chat" on 7.6 / tibiafun.com.pl

### ISSUE THREAD

**Issue by divinity76** [edubart/otclient#1018]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [x] This issue is reproducible without changes to the code in this repository

PS: the Cipsoft 7.6 client is not affected, thus i'm confident that it's a otclient bug, not a `this server`-bug.

### Steps to reproduce (include any configuration/script required to reproduce)
1. make an account & character at tibiafun.com.pl
2. log in
3. ... try to say hi out loud.

### Expected behaviour
the character says hi

### Actual behaviour
can't find the default chat, in effect i can't use any spells, and can't talk to people close to me (other than using a PM) and can't chat with NPCs, etc..

### Environment
OTClient 0.6.6
Rev 0 (df422c0)
Built on Feb 17 2017
gcc 4.8.1
the `Commit df422c0 ` download from here https://otland.net/threads/otclient-builds-windows.217977/

**Comment by divinity76** [comment]
... and now all of a sudden, i can. no idea what changed, i didn't do anything different (that i'm aware of)

.. but since i can no longer reproduce, i guess i'll close it until i know how to reproduce it.

**Comment by iryont** [comment]
I do suggest to check terminal logs when such issue happens.
