### ISSUE TITLE
Ubuntu 18.04 error

### ISSUE THREAD

**Issue by brunotonin** [edubart/otclient#1022]
I am compiling using ubuntu 18.04, but when running the screen is getting like the image below.

Cmake:
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Link to static libraries: ON
-- Build type: RelWithDebInfo
-- Build commit: devel
-- Build revision: 0
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   system
--   thread
--   filesystem
--   chrono
--   date_time
--   atomic
-- Found Lua: /usr/lib/x86_64-linux-gnu/liblua5.1.a  
-- LuaJIT: OFF
-- Found PHYSFS: /usr/lib/x86_64-linux-gnu/libphysfs.a  
-- Found OPENSSL: /usr/lib/x86_64-linux-gnu/libssl.a;/usr/lib/x86_64-linux-gnu/libcrypto.a  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.a  
-- Debug information: ON
-- Crash handler: ON
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Found GLEW: /usr/lib/x86_64-linux-gnu/libGLEW.so  
-- OpenGL ES: OFF
-- Found OPENAL: /usr/lib/x86_64-linux-gnu/libopenal.so  
-- Found VORBISFILE: /usr/lib/x86_64-linux-gnu/libvorbisfile.a  
-- Found VORBIS: /usr/lib/x86_64-linux-gnu/libvorbis.a  
-- Found OGG: /usr/lib/x86_64-linux-gnu/libogg.a  
-- Bot protection: ON
-- Use precompiled header: OFF
-- Configuring done
-- Generating done

![Captura de tela de 2019-03-11 18-24-45](https://user-images.githubusercontent.com/14988385/54160400-2fa46c80-442e-11e9-8f98-523b73b4af4d.png)

**Comment by JSkalskiSBG** [comment]
No errors during 'make'?
Do you have nvidia card and installed drivers for that card?

**Comment by brunotonin** [comment]
@JSkalskiSBG 
No errors occurred during compilation.
I do not have video card, i use the processor.

But in Ubuntu 16.04 it works correctly.
Probably some incompatibility with OpenGL.

**Comment by iryont** [comment]
I think there was similar issue with zlib for loading png back then. Did you try to log in into the game to see if sprites are drawn correctly? Sprites are the only thing which aren't loaded by a png loader.

**Comment by brunotonin** [comment]
@iryont 
The sprites are loading.

![Captura de tela de 2019-03-19 19-34-17](https://user-images.githubusercontent.com/14988385/54646558-2fcfe800-4a7e-11e9-9578-20368f8faf33.png)

**Comment by iryont** [comment]
https://github.com/edubart/otclient/commit/8871659b0744286d77995476b02005319b052b4e

Do you have this fix?

**Comment by brunotonin** [comment]
@iryont 
It worked, thank you!
