### ISSUE TITLE
[7.6] "Cancel Target" packet is ignored

### ISSUE THREAD

**Issue by divinity76** [edubart/otclient#1023]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. target a creature for attacking
2. make the server send the "cancel target" packet (in hex: "A3" excluding the 
packet header - or "0100A3" with the packet header) - easiest way is probably to attack a NPC (i didn't do that however, i used a /echopacket command for otserv 0.6.0.. possibly incomplete diff here: http://paste.debian.net/1074683/ )

### Expected behaviour
the red corsair around the target should be removed (that's what the cipsoft 7.6 client does)

### Actual behaviour
... nothing, otclient still believe it's attacking the target

### Environment

7.6 protocol, OTClient df422c0 build from https://otland.net/threads/otclient-builds-windows.217977/

**Comment by iryont** [comment]
I don't know how to approach this issue since the code is definitely there for parsing A3 packet. It seems to work correctly. Are you sure you did not modify any files within the repository?

**Comment by divinity76** [comment]
the only modification i did was to alter the background image.. 
![image](https://user-images.githubusercontent.com/1874996/55382820-f0e26d80-5526-11e9-8017-0928787bc6e7.png)

.. but i can no longer reproduce it myself, i have no idea what changed.

if it happens again, i will record the whole thing >.>
