### ISSUE TITLE
[OPENGL_ES 2] Crash when compilled in VS 2015/2017

### ISSUE THREAD

**Issue by LeandroPerrotta** [edubart/otclient#1024]
I'm trying to compile OTClient with support to DX9 (OPENGL_ES 2). I'm following the guide here, and after a lot of issues to compille it (VS 2017), I managed to do it, but now OTClient crash when it starts.

The first crash was on function  '_internalCreateGLContext_' at '_framework/plataform/win32window.cpp_'. 

After do some researchs here on Issues reports for someone with problems similar to mine and an user suggest to change the libEGL.dll and libGLESv2.dll to an provided by him, and I did it and then this crash was fixed (only in 32 bits, in 64 still remain).

But now, it crashing at another point, I'll show in a printscreen:

https://imgur.com/a/lDLqbQZ

Right now, I don't know where problem is anymore, if is in libs, or in DLL, or whatever... I tried compilling it in 32 bits and 64 bits, also, on VS 2015 and 2017. Not able to run OTClient with OPENGL_ES 2 in any of those attempts.

The OPENGL_ES libs/headers used to compile it is of this GIT:
https://github.com/okk3/OpenGL-ES-SDK

I also don't know if the support to OPENGL_ES is still mainted to lastest versions of OTC, since not many people try to use this compilling flag. 

I am tring an last attempt to compile it with OPENGL_ES, now on MinGW / CodeBlocks. But on it i am having a lot of problems to compile OTClient (even without OPENGL_ES). Not sure if MinGW32 / CodeBlocks are really yet supported. Most of problems I having to compile it is related with functions of STD used in OTClient that not exists in STD ported to Windows in MinGW (most of them, Thread related).

**Comment by LeandroPerrotta** [comment]
I just fixed the problem. The solution was compile ANGLE by myself and put the libs and DLLs to OTClient. In that way, OTClient open withou any crash in DX9.

**Comment by djseban** [comment]
@LeandroPerrotta Do you still have solution for this? I compiled ANGLE myself, client still crashes

**Comment by LeandroPerrotta** [comment]
> @LeandroPerrotta Do you still have solution for this? I compiled ANGLE myself, client still crashes

Are you sure you compilling the very same version of ANGLE that you are using to compile on OTC/OPENGLES? If crashes persists, it only can be a different DLL from expected from the lib linked in the OTC.

[http://darghos.com.br/files/dll_OPENGLES.rar](url)

Here's my DLL's compiled, check if it help you. But I am not sure if it will help... I think no.

**Comment by djseban** [comment]
> > @LeandroPerrotta Do you still have solution for this? I compiled ANGLE myself, client still crashes
> 
> Are you sure you compilling the very same version of ANGLE that you are using to compile on OTC/OPENGLES? If crashes persists, it only can be a different DLL from expected from the lib linked in the OTC.
> 
> http://darghos.com.br/files/dll_OPENGLES.rar
> 
> Here's my DLL's compiled, check if it help you. But I am not sure if it will help... I think no.

Yeah, I am 100% sure I use proper DLLs (that is the ones resulting from ANGLE compilation). May I ask which commit of ANGLE did you compile to make it working? To be sure we are talking about MSVC2015

**Comment by LeandroPerrotta** [comment]
> > > @LeandroPerrotta Do you still have solution for this? I compiled ANGLE myself, client still crashes
> > 
> > 
> > Are you sure you compilling the very same version of ANGLE that you are using to compile on OTC/OPENGLES? If crashes persists, it only can be a different DLL from expected from the lib linked in the OTC.
> > http://darghos.com.br/files/dll_OPENGLES.rar
> > Here's my DLL's compiled, check if it help you. But I am not sure if it will help... I think no.
> 
> Yeah, I am 100% sure I use proper DLLs (that is the ones resulting from ANGLE compilation). May I ask which commit of ANGLE did you compile to make it working? To be sure we are talking about MSVC2015. The DLLs you gave link to are compiled by MinGW, right?

No, I not using MinGW, my Angle as OTC was compilled under MSVC2017

Here's the commit I used:
![image](https://user-images.githubusercontent.com/1825511/67166905-4c146a00-f36a-11e9-9971-895fbadca83c.png)

Also, I did an small change on it's source, but lol. Is so long ago, I do not remember exactly why I did it... Seems I only forcing a compilling FLAG to use DX9 instead 11.

![image](https://user-images.githubusercontent.com/1825511/67166929-94338c80-f36a-11e9-8e75-7ba71df9d7a9.png)

Hope it's help you somehow.
