### ISSUE TITLE
Error on ubuntu 18.04

### ISSUE THREAD

**Issue by yehia** [edubart/otclient#1029]
`/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libogg.a(framing.o): relocalização R_X86_64_32S contra ".rodata" não pode ser usada ao fazer um objecto PIE; recompilar com -fPIC
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libogg.a(bitwise.o): relocalização R_X86_64_32S contra ".rodata" não pode ser usada ao fazer um objecto PIE; recompilar com -fPIC
/usr/bin/ld: vinculação final falhou: Seção não representável na saída
collect2: error: ld returned 1 exit status
CMakeFiles/otclient.dir/build.make:3857: recipe for target 'otclient' failed
make[2]: *** [otclient] Error 1
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/otclient.dir/all' failed
make[1]: *** [CMakeFiles/otclient.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by iryont** [comment]
https://github.com/edubart/otclient/pull/1028/files

This PR might help you. Especially the first one within CMakeLists.txt
