### ISSUE TITLE
Droping itens on floor

### ISSUE THREAD

**Issue by mcaccelli** [edubart/otclient#1033]
[PROTOCOL 7.72] [NOSTALRIUS]
Drop item from backpack in the floor and the item is not on the floor

ERROR: ProtocolGame parse message exception (22 bytes unread, last opcode is 106, prev opcode is 114): unable to create item with invalid id 19202

ERROR: ProtocolGame parse message exception (22 bytes unread, last opcode is 106, prev opcode is 114): unable to create item with invalid id 39681

Those errors appears when any item droped in the floor

**Comment by iryont** [comment]
Not an issue with the game client.

**Comment by mcaccelli** [comment]
Any suggestion??
