### ISSUE TITLE
Black screen can't see anything ingame

### ISSUE THREAD

**Issue by Relyxia** [edubart/otclient#1034]
### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [ ] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. OTX2
2. 7.72 map
3. OTClient

### Expected behaviour
Drawing sqms

### Actual behaviour
This is how looks
![imagen](https://user-images.githubusercontent.com/51744529/59391356-55fede80-8d74-11e9-96b8-6c886d4278ec.png)

### Environment
7.72 latest update

**Comment by okk3** [comment]
Hello there Relyxia,

I think the error isn't OTClient related but lies on the first step. 

Best Wishes,
Okke

**Comment by Relyxia** [comment]
I run in other client (Tibia Loader otservlist.org) and it works...

**Comment by slavidodo** [comment]
The error states that the [ThingTypes - loaded from Tibia.dat] doesn't have that id..

The error is mostly related to your .dat, please verify it's loaded correctly.

**Comment by kuzynn** [comment]
Screen often goes black if your client is outdated.
