### ISSUE TITLE
Settings are saving but not checked

### ISSUE THREAD

**Issue by Kuhicop** [edubart/otclient#1035]
### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [ ] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. OTClient last version
2. Windows 10
3. My client_options\options.lua is: https://pastebin.com/WJ6JCfxu
If I test with original script it's also not working

### Expected behaviour
The client should select at startup the saved settings like this:
![image](https://user-images.githubusercontent.com/27239965/59555281-4ff54180-8fb0-11e9-902b-dc4613967a20.png)

### Actual behaviour
Settings are loaded but the gaps are not marked.

### Environment
Windows 10 Visual Studio 2017

**Comment by chaosb93** [comment]
werqr

**Comment by okk3** [comment]
Hello there @Kuhicop,

As the client starts it loads all the modules, that means, if you set this to `true` it will be checked.

https://github.com/edubart/otclient/blob/1addf3e1766ca3fe43bdf1114c0655a971123291/modules/client_options/options.lua#L6

Best Wishes,
Okke

**Comment by chaosb93** [comment]
thank u :) 
            
          
     
      
       
        Dnia 16 listopada 2019 12:38 Okke &lt;notifications@github.com&gt; napisał(a):
       
    
       
         Hello there  github.com @Kuhicop , 
 As the client starts it loads all the modules, that means, if you set this to  true  it will be checked. 
 github.com github.com 
 Best Wishes,  
Okke
