### ISSUE TITLE
PHYSFS identifier not found error

### ISSUE THREAD

**Issue by SaintyDEV** [edubart/otclient#1050]
Hello, I'm trying to compile OTC using VS but I'm getting this error:
`1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\filestream.cpp(71): error C3861: 'PHYSFS_readBytes': identificador não encontrado
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\filestream.cpp(100): error C3861: 'PHYSFS_writeBytes': identificador não encontrado
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\filestream.cpp(112): error C3861: 'PHYSFS_readBytes': identificador não encontrado
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\filestream.cpp(133): error C3861: 'PHYSFS_writeBytes': identificador não encontrado
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\filestream.cpp(187): error C3861: 'PHYSFS_readBytes': identificador não encontrado
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\filestream.cpp(250): error C3861: 'PHYSFS_readBytes': identificador não encontrado
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\filestream.cpp(316): error C3861: 'PHYSFS_readBytes': identificador não encontrado
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\filestream.cpp(357): error C3861: 'PHYSFS_writeBytes': identificador não encontrado
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\filestream.cpp(404): error C3861: 'PHYSFS_writeBytes': identificador não encontrado
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\filestream.cpp(458): error C3861: 'PHYSFS_getLastErrorCode': identificador não encontrado
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\filestream.cpp(458): error C3861: 'PHYSFS_getErrorByCode': identificador não encontrado
1>Unknown compiler version - please run the configure tests and report the results
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\sound\declarations.h(30): fatal error C1083: Não é possível abrir arquivo incluir: 'AL/al.h': No such file or directory (compilando arquivo de origem ..\src\framework\core\graphicalapplication.cpp)
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\resourcemanager.cpp(64): error C3861: 'PHYSFS_unmount': identificador não encontrado
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\resourcemanager.cpp(83): error C3861: 'PHYSFS_getLastErrorCode': identificador não encontrado
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\resourcemanager.cpp(83): error C3861: 'PHYSFS_getErrorByCode': identificador não encontrado
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\resourcemanager.cpp(93): error C3861: 'PHYSFS_getLastErrorCode': identificador não encontrado
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\resourcemanager.cpp(93): error C3861: 'PHYSFS_getErrorByCode': identificador não encontrado
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\resourcemanager.cpp(136): error C3861: 'PHYSFS_unmount': identificador não encontrado
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\resourcemanager.cpp(153): error C3861: 'PHYSFS_getLastErrorCode': identificador não encontrado
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\resourcemanager.cpp(153): error C3861: 'PHYSFS_getErrorByCode': identificador não encontrado
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\resourcemanager.cpp(165): error C2065: 'PHYSFS_Stat': identificador não declarado
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\resourcemanager.cpp(165): error C2146: erro de sintaxe: ';' ausente antes do identificador 'stat'
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\resourcemanager.cpp(165): error C3079: não é possível usar uma lista de inicializadores como operando direito deste operador de atribuição
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\resourcemanager.cpp(166): error C3861: 'PHYSFS_stat': identificador não encontrado
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\resourcemanager.cpp(170): error C2065: 'PHYSFS_FILETYPE_DIRECTORY': identificador não declarado
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\resourcemanager.cpp(191): error C3861: 'PHYSFS_getLastErrorCode': identificador não encontrado
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\resourcemanager.cpp(191): error C3861: 'PHYSFS_getErrorByCode': identificador não encontrado
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\resourcemanager.cpp(195): error C3861: 'PHYSFS_readBytes': identificador não encontrado
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\resourcemanager.cpp(205): error C3861: 'PHYSFS_getLastErrorCode': identificador não encontrado
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\resourcemanager.cpp(205): error C3861: 'PHYSFS_getErrorByCode': identificador não encontrado
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\resourcemanager.cpp(209): error C3861: 'PHYSFS_writeBytes': identificador não encontrado
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\resourcemanager.cpp(238): error C3861: 'PHYSFS_getLastErrorCode': identificador não encontrado
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\resourcemanager.cpp(238): error C3861: 'PHYSFS_getErrorByCode': identificador não encontrado
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\resourcemanager.cpp(246): error C3861: 'PHYSFS_getLastErrorCode': identificador não encontrado
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\resourcemanager.cpp(246): error C3861: 'PHYSFS_getErrorByCode': identificador não encontrado
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\resourcemanager.cpp(254): error C3861: 'PHYSFS_getLastErrorCode': identificador não encontrado
1>c:\users\yago\desktop\dev stuff\ot\otclient-master\src\framework\core\resourcemanager.cpp(254): error C3861: 'PHYSFS_getErrorByCode': identificador não encontrado
1>Projeto de compilação pronto "otclient.vcxproj" -- FALHA.
========== Recompilar Tudo: 0 com êxito, 1 com falha, 0 ignorados ==========`

I tried to add all includes folders and libs folders from otc sdk on project properties (including physfs-2.0.3.1) but it still doesn't work. What can it be?

Also, where should I set OPENGL_ES=2 for Dx9 support? Maybe I'm doing something dumb but I don't have any experience with VS, I always compiled OTC with CodeBlocks

**Comment by CrypterDEV** [comment]
You need physfs-3.0 because of the last commit.

**Comment by Crimson-Games** [comment]
Where can I download it?

**Comment by GustavoContreiras** [comment]
I need that too, I found at https://icculus.org/pipermail/physfs/2019-March/001280.html but couldnt compile it

**Comment by diath** [comment]
The easiest way to get it on Windows would be vcpkg: https://github.com/Microsoft/vcpkg

**Comment by SaintyDEV** [comment]
> I need that too, I found at https://icculus.org/pipermail/physfs/2019-March/001280.html but couldnt compile it

Well, it's not the best way but since I couldn't compile Physfs I downloaded an "old" version of OTC that still uses old Physfs (https://github.com/edubart/otclient/tree/6a2d12ce277b41b085778b132711842defe2090d)

**Comment by diath** [comment]
Here's physfs 3 for Windows for anyone struggling with building it: https://mega.nz/#!pbI3jKDD!8HeJ-DdgW2IU3itAKaaQCEoTk_5TxsC9KD18dbdF6MA
