### ISSUE TITLE
Monster disappear from Battle list after onSpawn event

### ISSUE THREAD

**Issue by SaintyDEV** [edubart/otclient#1051]
I have a level system wich changes the monster name after it spawns with onSpawn event. The problem is: the monster appears on Battle list for less then 1sec before onSpawn takes effect and then disappears, and only appears again if it moves 1 SQM. Is there a way to fix it? Or I will have to code something like an opcode that updates Battle after onSpawn?

**Comment by Crimson-Games** [comment]
I forgot to say: I'm using TFS 0.3.6pl1 protocol 8.54

**Comment by diath** [comment]
I don't think there's a simple way around it without resorting to the opcode way however as an alternative you could simply change your onSpawn event to trigger after the monster is spawned but before it's sent to the client so it's initially sent with proper information.
