### ISSUE TITLE
Moving creatures/items far out of reach

### ISSUE THREAD

**Issue by 4drik** [edubart/otclient#1055]
### Steps to reproduce
1. Drag a creature or an item, do not drop yet.
2. Walk out of reach.
3. Drop item.

### Expected behaviour
No terminal errors

### Actual behaviour
Terminal errors

### Environment
7.6 OTClient 0.6.6

###Proposed fix
https://github.com/4drik/otclient/commit/5e4a1937adb047b7d5a477dd2a6e7b9c7df09746
https://github.com/4drik/otclient/commit/ff0025bba7f72073b1ad6169ce10f4fdefa02631
Check for correctness.

###Comments
Probably the problem will be the same when we drop thing into inventory / container.
Terminal errors should refer to UIItem.

**Comment by Sajgon** [comment]
I can confirm this on my client running 7.7 too

**Comment by 4drik** [comment]
As I mentioned the problem occurs also when we drop thing into inventory / container.
Proposed fix
https://github.com/4drik/otclient/commit/521e799c6123008ac8734331f340c8e30216fb0a

**Comment by diath** [comment]
Seems like a proper solution, ideally we'd be able to connect to a destroy event for a Thing and just reset the currentDragThing variable if it gets destroyed but there's no such functionality so this should be fine for now. Feel free to open a PR.

**Comment by 4drik** [comment]
Done. @diath, please contact me on discord: 4drik#3435
I have written several improvements to OTClient that need to be checked.
