### ISSUE TITLE
Compilation Error on Ubuntu 19.10

### ISSUE THREAD

**Issue by LucasCPrazeres** [edubart/otclient#1056]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Try build
2. Follow the wiki steps
3. Wait for the error ...

### Expected behaviour
**Compile without error.**

### Actual behaviour
https://pastebin.com/z8Gdcsuj

### Environment
OTClient (last)
Ubuntu 19.10

**Comment by diath** [comment]
The wiki information is outdated, in the hg clone step you have to replace stable-2.0 with stable-3.0, I've updated the Wiki accordingly.
Though I'm not sure if it's needed at all on your version of Ubuntu as Disco Dingo seems to ship with 3.x by default (https://packages.ubuntu.com/disco/libphysfs-dev).

**Comment by LucasCPrazeres** [comment]
Solved
