### ISSUE TITLE
[Question] Are we open to update the client's Graphics?

### ISSUE THREAD

**Issue by slavidodo** [edubart/otclient#1066]
Should we update graphics to use OpenGL 3 core instead of fixed-function?

**Comment by iryont** [comment]
What for, exactly? It seems to be... rather pointless.

**Comment by Zbizu** [comment]
imo the performance issues should be solved first
#277
#220
#901

**Comment by okk3** [comment]
Hello there,

I wouldn't really mind updating it to OGL3 in terms of general performance, but I think the most important thing at the moment is to be able to use multi-graphics for a better user-friendly experience, it's really a pain in the arse to have to compile two or more binaries if you're running multi-platform and deliver more redundant data to the users. Most people nowadays have pretty decent machines that can run otclient flawlessly if you have fixed a few of those performance issues @Zbizu mentioned above.

Best Wishes,
Okke

**Comment by slavidodo** [comment]
@iryont There is no reason to close this!
