### ISSUE TITLE
Hello, i was compile a server in debian but when i run the server the server can't read the npc and charge it.

### ISSUE THREAD

**Issue by RNATI1992** [edubart/otclient#1096]
### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [ ] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1.
2.
3.

**Comment by okk3** [comment]
Hello @RNATI1992,

Please fill up the template before submitting an issue to this repository. Please make sure to give us enough information about your issue. 

Best Wishes,
Okke
