### ISSUE TITLE
Utevo vis lux doesn't work on 7.x

### ISSUE THREAD

**Issue by peonso** [edubart/otclient#1120]
### Before creating an issue, please ensure:
- [X] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [X] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Cast utevo vis lux running 7.x protocols

### Expected behaviour
CONDITION_PARAM_LIGHT_LEVEL, should be set to 10

### Actual behaviour
It's capped at 8 by https://github.com/edubart/otclient/blob/b3d947d4c3121bc6fa866a629ad62de50c12e8e0/src/client/lightview.cpp#L31

### Environment
using  7.72 OTClient 0.6.6

**Comment by okk3** [comment]
Created a new PR: https://github.com/edubart/otclient/pull/1121

Issue can be closed 👍 

Best Wishes
Okke
