### ISSUE TITLE
Clickable highlight words in npc channel

### ISSUE THREAD

**Issue by miltonhit** [edubart/otclient#1122]
Hi there,

Do you think of putting support for the "click" of highlight words in the npc channel the same as in tibia global?

Ex. 
![image](https://user-images.githubusercontent.com/6332560/103845289-87d44600-507a-11eb-93d1-3615c5e87a16.png)

When the player clicks on the word "records" the players says "records" on the same channel, 
facilitating interaction.

**Comment by Ayato96** [comment]
in game console.lua replace this function:
`function addTabText(text, speaktype, tab, creatureName)`
 
to

`
```
function addTabText(text, speaktype, tab, creatureName)
  if not tab or tab.locked or not text or #text == 0 then return end

  if modules.client_options.getOption('showTimestampsInConsole') then
    text = os.date('%H:%M') .. ' ' .. text
  end

  local panel = consoleTabBar:getTabPanel(tab)
  local consoleBuffer = panel:getChildById('consoleBuffer')
  local label = g_ui.createWidget('ConsoleLabel', consoleBuffer)
  label:setId('consoleLabel' .. consoleBuffer:getChildCount())
  label:setText(text)
  label:setColor(speaktype.color)
  consoleTabBar:blinkTab(tab)

  -- Overlay for consoleBuffer which shows highlighted words only

  if speaktype.npcChat and (g_game.getCharacterName() ~= creatureName or g_game.getCharacterName() == 'Account Manager') then
    local highlightData = getHighlightedText(text)
    if #highlightData > 0 then
      local labelHighlight = g_ui.createWidget('ConsolePhantomLabel', label)
      labelHighlight:fill('parent')

      labelHighlight:setId('consoleLabelHighlight' .. consoleBuffer:getChildCount())
      labelHighlight:setColor("#f24900")

      local highlightOptions = {}

      -- Remove the curly braces
      for i = 1, #highlightData / 3 do
        local dataBlock = { _start = highlightData[(i-1)*3+1], _end = highlightData[(i-1)*3+2], words = highlightData[(i-1)*3+3] }
        text = text:gsub("%{(.-)%}", dataBlock.words, 1)

        -- Recalculate positions as braces are removed
        highlightData[(i-1)*3+1] = dataBlock._start - ((i-1) * 2)
        highlightData[(i-1)*3+2] = dataBlock._end - (1 + (i-1) * 2)
        highlightOptions[#highlightOptions + 1] = dataBlock.words
      end
      label:setText(text)

      if (#highlightOptions > 1) then
        labelHighlight.onMousePress = function(widget, mousePos, button)
          if (button == MouseLeftButton) then
              local menu = g_ui.createWidget('PopupMenu')

              for k, v in pairs(highlightOptions) do
                menu:addOption(v, function() sendMessage(v, consoleTabBar:getTab('NPCs')) end)
              end
              menu:display(mousePos)
          end
        end

      elseif (#highlightOptions == 1) then
        labelHighlight.onMousePress = function(widget, mousePos, button)
          if (button == MouseLeftButton) then
            sendMessage(highlightOptions[1], consoleTabBar:getTab('NPCs')) end
          end
      end

      -- Calculate the positions of the highlighted text and fill with string.char(127) [Width: 1]
      local drawText = label:getDrawText()
      local tmpText = ""
      for i = 1, #highlightData / 3 do
        local dataBlock = { _start = highlightData[(i-1)*3+1], _end = highlightData[(i-1)*3+2], words = highlightData[(i-1)*3+3] }
        local lastBlockEnd = (highlightData[(i-2)*3+2] or 1)

        for letter = lastBlockEnd, dataBlock._start-1 do
          local tmpChar = string.byte(drawText:sub(letter, letter))
          local fillChar = (tmpChar == 10 or tmpChar == 32) and string.char(tmpChar) or string.char(127)

          tmpText = tmpText .. string.rep(fillChar, letterWidth[tmpChar])
        end
        tmpText = tmpText .. dataBlock.words
      end

      -- Fill the highlight label to the same size as default label
      local finalBlockEnd = (highlightData[(#highlightData/3-1)*3+2] or 1)
      for letter = finalBlockEnd, drawText:len() do
          local tmpChar = string.byte(drawText:sub(letter, letter))
          local fillChar = (tmpChar == 10 or tmpChar == 32) and string.char(tmpChar) or string.char(127)

          tmpText = tmpText .. string.rep(fillChar, letterWidth[tmpChar])
      end

      labelHighlight:setText(tmpText)
    end
  end

  label.name = creatureName
  label.onMouseRelease = function (self, mousePos, mouseButton)
    processMessageMenu(mousePos, mouseButton, creatureName, text, self, tab)
  end

  if consoleBuffer:getChildCount() > MAX_LINES then
    consoleBuffer:getFirstChild():destroy()
  end
end`
```

**Comment by okk3** [comment]
Hello Ayato,


Thanks for the contribution, do you mind making a PR? We need contributors!

Best Wishes
Okke

**Comment by miltonhit** [comment]
> in game console.lua replace this function:
> `function addTabText(text, speaktype, tab, creatureName)`
> 
> to
> 
> `
> 
> ```
> function addTabText(text, speaktype, tab, creatureName)
>   if not tab or tab.locked or not text or #text == 0 then return end
> 
>   if modules.client_options.getOption('showTimestampsInConsole') then
>     text = os.date('%H:%M') .. ' ' .. text
>   end
> 
>   local panel = consoleTabBar:getTabPanel(tab)
>   local consoleBuffer = panel:getChildById('consoleBuffer')
>   local label = g_ui.createWidget('ConsoleLabel', consoleBuffer)
>   label:setId('consoleLabel' .. consoleBuffer:getChildCount())
>   label:setText(text)
>   label:setColor(speaktype.color)
>   consoleTabBar:blinkTab(tab)
> 
>   -- Overlay for consoleBuffer which shows highlighted words only
> 
>   if speaktype.npcChat and (g_game.getCharacterName() ~= creatureName or g_game.getCharacterName() == 'Account Manager') then
>     local highlightData = getHighlightedText(text)
>     if #highlightData > 0 then
>       local labelHighlight = g_ui.createWidget('ConsolePhantomLabel', label)
>       labelHighlight:fill('parent')
> 
>       labelHighlight:setId('consoleLabelHighlight' .. consoleBuffer:getChildCount())
>       labelHighlight:setColor("#f24900")
> 
>       local highlightOptions = {}
> 
>       -- Remove the curly braces
>       for i = 1, #highlightData / 3 do
>         local dataBlock = { _start = highlightData[(i-1)*3+1], _end = highlightData[(i-1)*3+2], words = highlightData[(i-1)*3+3] }
>         text = text:gsub("%{(.-)%}", dataBlock.words, 1)
> 
>         -- Recalculate positions as braces are removed
>         highlightData[(i-1)*3+1] = dataBlock._start - ((i-1) * 2)
>         highlightData[(i-1)*3+2] = dataBlock._end - (1 + (i-1) * 2)
>         highlightOptions[#highlightOptions + 1] = dataBlock.words
>       end
>       label:setText(text)
> 
>       if (#highlightOptions > 1) then
>         labelHighlight.onMousePress = function(widget, mousePos, button)
>           if (button == MouseLeftButton) then
>               local menu = g_ui.createWidget('PopupMenu')
> 
>               for k, v in pairs(highlightOptions) do
>                 menu:addOption(v, function() sendMessage(v, consoleTabBar:getTab('NPCs')) end)
>               end
>               menu:display(mousePos)
>           end
>         end
> 
>       elseif (#highlightOptions == 1) then
>         labelHighlight.onMousePress = function(widget, mousePos, button)
>           if (button == MouseLeftButton) then
>             sendMessage(highlightOptions[1], consoleTabBar:getTab('NPCs')) end
>           end
>       end
> 
>       -- Calculate the positions of the highlighted text and fill with string.char(127) [Width: 1]
>       local drawText = label:getDrawText()
>       local tmpText = ""
>       for i = 1, #highlightData / 3 do
>         local dataBlock = { _start = highlightData[(i-1)*3+1], _end = highlightData[(i-1)*3+2], words = highlightData[(i-1)*3+3] }
>         local lastBlockEnd = (highlightData[(i-2)*3+2] or 1)
> 
>         for letter = lastBlockEnd, dataBlock._start-1 do
>           local tmpChar = string.byte(drawText:sub(letter, letter))
>           local fillChar = (tmpChar == 10 or tmpChar == 32) and string.char(tmpChar) or string.char(127)
> 
>           tmpText = tmpText .. string.rep(fillChar, letterWidth[tmpChar])
>         end
>         tmpText = tmpText .. dataBlock.words
>       end
> 
>       -- Fill the highlight label to the same size as default label
>       local finalBlockEnd = (highlightData[(#highlightData/3-1)*3+2] or 1)
>       for letter = finalBlockEnd, drawText:len() do
>           local tmpChar = string.byte(drawText:sub(letter, letter))
>           local fillChar = (tmpChar == 10 or tmpChar == 32) and string.char(tmpChar) or string.char(127)
> 
>           tmpText = tmpText .. string.rep(fillChar, letterWidth[tmpChar])
>       end
> 
>       labelHighlight:setText(tmpText)
>     end
>   end
> 
>   label.name = creatureName
>   label.onMouseRelease = function (self, mousePos, mouseButton)
>     processMessageMenu(mousePos, mouseButton, creatureName, text, self, tab)
>   end
> 
>   if consoleBuffer:getChildCount() > MAX_LINES then
>     consoleBuffer:getFirstChild():destroy()
>   end
> end`
> ```


It was very good. Thanks for the contribution, make a pull request with this change, it will help the community a lot
