### ISSUE TITLE
Lag when walking and using item

### ISSUE THREAD

**Issue by helviio** [edubart/otclient#1151]
Hello dear friends ... I come through this publication to ask for help to solve a bug that I'm having with OTC, when clicking on the map and using any type of item the char starts to lag/stuttering... i tried with another server and others customers ... everyone with the same problem OTCv8 has this same problem, but less lag ... the version I'm using is edubart/otclient (https://github.com/edubart/otclient)

I will leave a video of the normal Tibia client and the version of the OTC that I am using
my server version is tfs 04
Thank you all for your attention ... thanks now! <3

https://otland.net/threads/otc-lag-when-walking-and-using-item.276506/#post-2660311

**Comment by diath** [comment]
You can resolve this completely by removing the following on the server side:
https://github.com/otland/forgottenserver/blob/75cf2b91369d187453160e1b103c5123f5e3e2a4/src/actions.cpp#L435

**Comment by helviio** [comment]
thx <3

Em sáb., 22 de mai. de 2021 às 09:39, diath ***@***.***>
escreveu:
