### ISSUE TITLE
Latest OTClient doesn't work with forgotten server 1.4.1 (10.98 protocol)

### ISSUE THREAD

**Issue by eduardojunio** [edubart/otclient#1179]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Run forgotten server 1.4.1 (with the default data folder/map)
2. Try connecting to it using latest OTClient (master branch) selecting protocol 10.98

### Expected behaviour
Everything would work fine

### Actual behaviour
Broken map and can't walk properly

<details>
<summary>Screenshot of the issue</summary>

![Screen Shot 2022-04-02 at 14 18 38](https://user-images.githubusercontent.com/5347392/161394141-2288062e-b377-438a-9520-e8b6cd6f59b9.png)

</details>

### Environment

**OS:** macOS 12.2.1
**forgottenserver version:** 1.4.1
**OTClient version**: compiled from master (commit 45afb65b)
**Game protocol used:** 10.98

**Comment by eduardojunio** [comment]
I've connected to the same server using Cipsoft's client and it worked just fine, so the issue is on OTClient side.

**Comment by diath** [comment]
Works fine for me with edubart/otclient@45afb65b90284ce70f328733715043860186bf50, otland/forgottenserver@57d0dd4b145a5ee6b7b4c48ffb55b04bc75a4a5d and stock Tibia 10.98 data files.

![image](https://user-images.githubusercontent.com/1154021/161413573-61922083-f72e-4230-bcb9-a0989cfc24f0.png)

**Comment by eduardojunio** [comment]
@diath the issue was caused by bad Tibia files (I had downloaded them from somewhere and seems like they weren't real Tibia 10.98 files). I've installed Tibia on Windows, and copied the dat/spr files to my Mac and it worked just fine. Closing this issue! Thanks!
