### ISSUE TITLE
Errors during compilation

### ISSUE THREAD

**Issue by kamsz** [edubart/otclient#1193]
CMake Error at src/CMakeLists.txt:174 (find_package):
  Could not find a package configuration file provided by "STDUUID" with any
  of the following names:

    STDUUIDConfig.cmake
    stduuid-config.cmake

  Add the installation prefix of "STDUUID" to CMAKE_PREFIX_PATH or set
  "STDUUID_DIR" to a directory containing one of the above files.  If
  "STDUUID" provides a separate development package or SDK, be sure it has
  been installed.

**Comment by diath** [comment]
You probably want to post that in [mehah/otclient](https://github.com/mehah/otclient) instead of here as this upstream repo does not use stduuid library.

**Comment by sznycell162** [comment]
same the problem
