### ISSUE TITLE
Heys guys i have this problem, help me any?

### ISSUE THREAD

**Issue by foxrj21** [edubart/otclient#1208]
ERROR: ProtocolGame parse message exception (61 bytes, 40 unread, last opcode is 0xc8 (200), prev opcode is 0xffffffff (-1)): InputMessage eof reached

Packet has been saved to packet.log, you can use it to find what was wrong. (Protocol: 860

I'm having trouble changing the outfit on this client. On the server it is enabled right.

I created a topic in this forum:
https://criandotibia.com.br/index.php?/topic/278-erro-ao-tentar-trocar-outfit-no-otcv8-poup-n%C3%A3o-abre/

**Comment by yrpen** [comment]
It's not OTCv8 repository.
Here you go: >> https://github.com/OTCv8/otclientv8 <<
