### ISSUE TITLE
Translation:Fonts & Charset visual problems.

### ISSUE THREAD

**Issue by Fenrisus** [edubart/otclient#224]
![verdana-11px-rounded_cp1250](https://f.cloud.github.com/assets/3074538/79253/e189dd2e-61a7-11e2-9b0e-ae0aae9b6fbc.png)
I am rebuild textures for font similar like this, english(cp1252) work perfectly, but CP1251 charset have a problem (symbols, not a text). Similar problem i am find in Poland translation and Svenska (many parts of text looks fine, but text in symbols have too, looks like |Щsenord(password) ). And this problem have standart fonts and my edited.

**Comment by daniofordon** [comment]
has anyone solved this problem yet? how can you add polish characters to otclient?
