### ISSUE TITLE
enterGame.lua

### ISSUE THREAD

**Issue by DominikMS** [edubart/otclient#299]
Please change locals:
local loadBox
local enterGame
local motdWindow
local motdButton
local enterGameButton
local protocolBox
local protocolLogin

in to:

loadBox = nil
enterGame = nil
motdWindow = nil
motdButton = nil
enterGameButton = nil
protocolBox = nil
protocolLogin = nil

Beacuse we cannot edit this window from mods :/

**Comment by TheSumm** [comment]
What are the problems with non sandboxed modules and global variables, why is EnterGame not sandboxed and wouldn't it be possible to edit it using rootWidget:recursiveGetChildById(..)
