### ISSUE TITLE
Error Fix # 294

### ISSUE THREAD

**Issue by MaiconNociam** [edubart/otclient#326]
Well this error and still Fix # 294, improve more  even without success . Being able to help us because we can not change the script the order.lua ,because it involves many other scripts.

Error: http://www.youtube.com/watch?feature=player_embedded&v=KEpafKKTc-Y

**Comment by pstec01** [comment]
Conseguiram resolver?

**Comment by pstec01** [comment]
> Bem esse erro e ainda o Fix #294, melhora mais mesmo sem sucesso. Podendo nos ajudar pois não podemos alterar o script do order.lua ,pois envolve muitos outros scripts.
> 
> Erro: http://www.youtube.com/watch?feature=player_embedded&v=KEpafKKTc-Y

Conseguiu resolver?
