### ISSUE TITLE
New bug in action itemid use!!

### ISSUE THREAD

**Issue by totolol123** [edubart/otclient#359]
Well, with the latest commit the problem to take the items from the backpack solved, but continued to add ... I made a modification based on the last commit and it worked, it was: 

void ProtocolGame::parseContainerUpdateItem(const InputMessagePtr& msg)
{
    int containerId = msg->getU8();
    int slot;
    if(g_game.getFeature(Otc::GameContainerPagination)) {
        slot = msg->getU16();
    } else {
        slot = msg->getU8();
    }
    ItemPtr item = getItem(msg);
    g_game.processContainerUpdateItem(containerId, slot, item);
}

But continued just a bug ... When using an item that has ActionID, it give some errors: 

ERROR: ProtocolGame parse message exception (14 bytes unread, last opcode is 180, prev opcode is -1): InputMessage eof reached
ERROR: ProtocolGame parse message exception (10 bytes unread, last opcode is 180, prev opcode is -1): InputMessage eof reached
ERROR: Unable to send extended opcode 1, extended opcodes are not enabled
ERROR: ProtocolGame parse message exception (10 bytes unread, last opcode is 180, prev opcode is -1): InputMessage eof reached
ERROR: ProtocolGame parse message exception (10 bytes unread, last opcode is 180, prev opcode is -1): InputMessage eof reached
ERROR: ProtocolGame parse message exception (10 bytes unread, last opcode is 180, prev opcode is -1): InputMessage eof reached
ERROR: Unable to send extended opcode 1, extended opcodes are not enabled
ERROR: ProtocolGame parse message exception (311 bytes unread, last opcode is 180, prev opcode is -1): InputMessage eof reached
ERROR: no thing at pos:119 391 7, stackpos:2
C++ stack traceback:
    [C++]: ProtocolGame::getMappedThing
    ./otclient(ProtocolGame::getMappedThing(stdext::shared_object_ptr<InputMessage> const&)+0x1a7) [0x8432243]
    ./otclient(ProtocolGame::parseCreatureMove(stdext::shared_object_ptr<InputMessage> const&)+0x21) [0x8432457]
    ./otclient(ProtocolGame::parseMessage(stdext::shared_object_ptr<InputMessage> const&)+0x259) [0x8433d45]
    ./otclient(ProtocolGame::onRecv(stdext::shared_object_ptr<InputMessage> const&)+0x122) [0x842adb4]
    ./otclient(Protocol::internalRecvData(unsigned char_, unsigned short)+0x216) [0x836f0ca]
    ./otclient(std::_Function_handler<void (unsigned char_, unsigned short), std::_Bind<std::_Mem_fn<void (Protocol::*)(unsigned char*, unsigned short)> (stdext::shared_object_ptr<Protocol>, std::_Placeholder<1>, std::_Placeholder<2>)> >::_M_invoke(std::_Any_data const&, unsigned char_, unsigned short)+0x67) [0x8370238]
    ./otclient(std::function<void (unsigned char_, unsigned short)>::operator()(unsigned char*, unsigned short) const+0x2c) [0x836598e]
    ./otclient(Connection::onRecv(boost::system::error_code const&, unsigned int)+0x76) [0x835ff4e]
ERROR: no creature found to move
C++ stack traceback:
    [C++]: ProtocolGame::parseCreatureMove
    ./otclient(ProtocolGame::parseCreatureMove(stdext::shared_object_ptr<InputMessage> const&)+0xa7) [0x84324dd]

**Comment by alisonbarbosa** [comment]
I have this problem too!
did you find out how to solve it?
Would you be able to help me?
