### ISSUE TITLE
Issues/bugs/Missing Features in OTClient and also protocol 7.6 support. 

### ISSUE THREAD

**Issue by Schneider3000** [edubart/otclient#375]
Issues/Bugs (Outfits, Zooming in/out, right panel settings, resolution, white window, exp to next level)

FIRST

Outfits do not work properly, the chosen colours get added in a wrong order on the character.

For example, if the following colours are chosen and then OK is clicked:
Head: Red
Primary (body): Red
Secondary (legs): Red
Detail (feet): Red

![image](https://f.cloud.github.com/assets/5910329/1513634/c6a7ce80-4ae5-11e3-861c-a84a294db75e.png)

Then the outfit changes into this:
Head: WHITE
Primary (body): Red
Secondary (legs): Red
Detail (feet): Red

![image](https://f.cloud.github.com/assets/5910329/1513643/ebd0cda6-4ae5-11e3-9ceb-f8b9496719ed.png)

If Set Outfit menu is accessed again without changing outfit and OK is pressed again, then it changes to this:
Head: WHITE
Primary (body): WHITE
Secondary (legs): Red
Detail (feet): Red

Basically whatever colour you choose goes to the next body part, if you choose your head colour as red, then your body will become red and head will turn white. I dont know if this was explained clearly enough, though.

SECOND

To the next one,
In protocol 7.6 moving the windows such as inventory, battle and health bar out of right panel was not possible. This can be changed by using draggable: false but if draggable:false is used, then the order of the windows cannot be changed and they stay in the exact order as you opened them, moving them is not possible at all, not even inside the right panel. 

THIRD

This is just an issue in OTClient I believe. Normally if you use ctrl+ or ctrl- the zooming in and out is limited, you cannot zoom out with ctrl- more than the client lets. After you reload the modules, for instance by doing ctrl+shift+R, then for some reason zooming out is not limited anymore. You can zoom out as much as you want with ctrl-  after reloading modules, even if no changes were done to them.

FOURTH

When on fullscreen mode, it isnt possible to switch the resolution of the fullscreen mode in-game. This was possible in earlier Tibia versions atleast, Im not aware of the most up to date ones, though. If a person wants to play with fullscreen on OTClient using 1280x1024 resolution, then he has to change it manually from his OS / Graphic driver settings. It would be a good addition if changing the fullscreen resolution was possible inside OTClient aswell.

FIFTH

On Windows OS, a few people have experienced an issue with DX9 but not with OpenGL where minimizing and then maximizing the client back causes the whole OTClient window to go white. The white screen can be eliminated if you resize the OTClient window manually but double clicking it or stretching. This could be a driver issue but I havent figured it out yet.

SIXTH

The way experience to next level calculated in OTClient seems to differ from the way it is calculated in real tibia. For instance, the experience required from level 5 to 6 is 700 but with the equation that OTClient uses, the result is 800 and the higher level you get, the more the difference.

OTClient Exp for next level equation:
"(50_level_level_level)/3 - 100_level_level + (850_level)/3 - 200)"
Tibia  Exp for next level equation:
"50_(level)^2 - 150_(level) + 200"

So is there something I have missed or is the equation incorrect just as I thought?

I think thats a wrap for now.

**Comment by Felipe1993** [comment]
im having troubles to log into otclient on my server i use otx 7.72
[Warning - Protocol::RSA_decrypt] Not valid packet size (IP: xxx.xx.xxx.x)
my rsa is
109120132967399429278860960508995541528237502902798129123468757937266291492576446330739696001110603907230888610072655818825358503429057592827629436413108566029093628212635953836686562675849720620786279431090218017681061521755056710823876476444260558147179707119674283982419152118103759076030616683978566631413

i changed it in otclient put my rsa in all ot_client esa otserver
 no succes please help
