### ISSUE TITLE
Database questions.

### ISSUE THREAD

**Issue by Nu77** [edubart/otclient#390]
Sorry for this, but i really need to solve this doubt.
It's possible to connect to database and execute query in otclient? if is possible, someone write an example for me?
Thanks.

**Comment by Relyxia** [comment]
> local DATABASE_HOST = "localhost"
> local DATABASE_PORT = 3306
> local DATABASE_USER = "root"
> local DATABASE_PASS = ""
> local DATABASE_NAME = "dbname"
> 
> Isn't this facilitating for hackers? :o

Get a packer and build a db mirror
