### ISSUE TITLE
Get kick from server while using dash walking.

### ISSUE THREAD

**Issue by medanny** [edubart/otclient#421]
![image](https://f.cloud.github.com/assets/3634232/1809822/da81ae42-6e0a-11e3-9882-5de2423418e0.png)
If you enable it you get kick and this is the error that apears on the server...
disconected for exeeding packets per second limit.
once its turn off you wont get kick again any ideas?

**Comment by Tatuy** [comment]
Set maxPacketsPerSecond = 50+
