### ISSUE TITLE
[7.72] Some errors.

### ISSUE THREAD

**Issue by otclient** [edubart/otclient#460]
While playing on 7.72 server using OTClient i noticed some console errors:

This one has something to do with choosing target i guess not 100% sure:

>ERROR: protected lua call failed: LUA ERROR:
>/game_interface/widgets/uigamemap.lua:42: attempt to index local 'thingPos' (a nil value)
>stack traceback:
>[C]: in function '__index'
>/game_interface/widgets/uigamemap.lua:42: in function 
>Exiting application..

This one has something to do with closing containers but i don't know when it happen.

>ERROR: container not found
>at:
>[C++]: ?processCloseContainer@Game@@IAEXH@Z

**Comment by TheSumm** [comment]
Fixed in https://github.com/edubart/otclient/commit/4c4e0b9d073394058d293c0b8c132ac518eda547

Cannot reproduce thingPos being a nil value
