### ISSUE TITLE
Settings aren't saved(windows 7)

### ISSUE THREAD

**Issue by Zbizu** [edubart/otclient#468]
as in title - administrator account name on my pc contains "Ł" letter and there is no way to load/save settings and minimap (some files are created, but they are never loaded again)

can these be saved in client directory as default path?

software: windows 7 home 64 bit

**Comment by kungen32** [comment]
> Otclient made empty file called otclient instead of creating a new folder.
> Replacing empty file to new folder solves this problem.
> I'll leave this issue open till someone fix it.

Hello

Can you be more simplistic in your answer ?
I just found c:users:otclient, contains 2 files, not emptys
Also %appdata% otclient/otclient/otclient ( 3 times ) then a config.

Where i remplace the file for the new one, and which file ?

**Comment by Zbizu** [comment]
The issue was with my user name containing an unhandled character probably (Ł).
