### ISSUE TITLE
OTClient can't load older dat files.

### ISSUE THREAD

**Issue by otclient** [edubart/otclient#477]
Hello,
Today i noticed that OTClient can't load older dat file. Every tibia.dat less than 7.6 doesn't work for example i want to load 7.4 tibia.dat. This error appear:

> ERROR: Failed to read dat '/things/740/Tibia.dat': corrupt data'

How to fix this?

**Comment by raphaelsc** [comment]
I still have problems with it. Look: ERROR: Failed to read dat '/things/740/Tibia.dat': corrupt data (id: 102, category: 0, count: 255, lastAttr: 129)' How should I proceed here?
