### ISSUE TITLE
OTClient on ARM devices

### ISSUE THREAD

**Issue by ech0123** [edubart/otclient#488]
I tried compiling OTClient on my Raspberry Pi by following the compiling guide for Linux, everything compiles just fine however I first got the error “Fatal error: glx not supported” which means that I’ve compiled the OpenGL version and Raspberry Pi which is ARM-based is running OpenGL ES 2.0. So I changed OPENGLES=OFF to OPENGLES=ON but I still got “Fatal error: GLX not supported” and then I changed it to OPENGLES=2.0 instead, it’s compiling fine but when I try to run it with ./otclient I get the “Error: Cannot initialize egl” and that’s where I am right now, anyone with suggestions? I got the impression that otclient would work with opengles 2.0 and ARM based devices like mobile platforms and so forth. Perhaps there's something I'm missing regarding the cmake settings.

**Comment by sonaldo** [comment]
Someone who could compile the Raspberry can make a tutorial?

How many FPS you get?
