### ISSUE TITLE
i cant login 7.72 ots

### ISSUE THREAD

**Issue by Pacan123** [edubart/otclient#517]
Ihave this massage
Enter your network or the server went down (ERROR2)
but i know that i use good port and ip adress usually i thin about classicus ots

**Comment by xNarkon** [comment]
I'm developing new OTS with OTClient and have the same problem. Server is 101% ok because I can connect through old cipsoft client, but with OTClient I'm getting message "Enter your network or the server went down (ERROR2)". What can be wrong?
