### ISSUE TITLE
7.4 Protocol problem

### ISSUE THREAD

**Issue by Duxi3** [edubart/otclient#554]
I have many problems using original 7.4 protocol.
Magic effectr looks diferent, maybe new version offset.
Sometimes player stop working and just hold, i can't say anything, monsters dont die(dont always)
Sometimes  a clone of my char left next to me ;p
Green bar (to next level) shows different values when attack monster(140 percent )
I see that 7.4 is just for test ;)
Thanks

**Comment by TheSumm** [comment]
There are no pure 7.4 servers in use I guess.
