### ISSUE TITLE
Bug walking under a tree

### ISSUE THREAD

**Issue by osmarjunior** [edubart/otclient#558]
When I walk under a tree, the player is drawn on top of the tree, as in the image below:

![bugarvore](https://cloud.githubusercontent.com/assets/284147/4005544/5364c930-2994-11e4-8b36-44e0b051dc10.png)

In that case I don't know how to resolve :( Does anyone have an idea?

**Comment by TheSumm** [comment]
There might be several conflicts when drawing but I doubt there is a way to draw every case correctly.
