### ISSUE TITLE
WSASocketA

### ISSUE THREAD

**Issue by ghost** [edubart/otclient#560]
Hi,
I have a problem with the compilation OTclient, error list
Error    1    error C4996: 'WSASocketA': Use WSASocketW() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings (..\src\client\container.cpp)    D:\otclient-msvc13-libs\boost_1_55_0\include\boost\asio\detail\impl\socket_ops.ipp    1346    1    otclient
and 38 the same mistakes.
Build,
http://pastebin.com/dgbD6BvF
I hope to help.

**Comment by Zbizu** [comment]
why is that closed? what was the solution? I'm having the same problem now
