### ISSUE TITLE
Centered outfit

### ISSUE THREAD

**Issue by 4drik** [edubart/otclient#562]
I'm trying to center outfits more than 32x32 (like 64x64, 96x96 etc.)

I changed in creature.cpp this:
    internalDrawOutfit(dest + animationOffset \* scaleFactor, scaleFactor, animate, animate, m_direction);
    m_footStepDrawn = true;

To this:
    int exactSize;
    if (m_outfit.getCategory() == ThingCategoryCreature)
        exactSize = getExactSize();
    else
        exactSize = g_things.rawGetThingType(m_outfit.getAuxId(), m_outfit.getCategory())->getExactSize();
    internalDrawOutfit(dest + ((animationOffset + Point((exactSize - 32) / 2, 0))) \* scaleFactor, scaleFactor, animate, animate, m_direction);
    m_footStepDrawn = true;

But now the outfit is not full.
![outfit](https://cloud.githubusercontent.com/assets/8080528/4112465/f59a2522-3229-11e4-96a3-af416bb5858c.png)

**Comment by welistonbelles** [comment]
Hello, maybe someone has the code to make available?

**Comment by raionejunior** [comment]
I have the solution and the code is ready, whoever wants to access this like and have the complete and functional change, just change the codes in mapwiew.cpp, any questions, please contact us.
https://github.com/raionejunior/codes/blob/main/.gitignore

**Comment by Doodiie** [comment]
> I have the solution and the code is ready, whoever wants to access this like and have the complete and functional change, just change the codes in mapwiew.cpp, any questions, please contact us.
> https://github.com/raionejunior/codes/blob/main/.gitignore

but, and the bug of drawing the walls above the ground on another floor? How to solve?

**Comment by raionejunior** [comment]
I had no problems with it here. the only problem is the items above the creature, this you can use the creature's position in the sprite's movement.
