### ISSUE TITLE
DirtectX implementation for Windows.

### ISSUE THREAD

**Issue by dominique120** [edubart/otclient#579]
Does it exist? I know that the tutorial on the wiki explains how to compile with OpenGL ES but isnt this for embedded systems like Android and what not?

I have compiled the latest rev of OTC with the flag(OPENGL_ES=2) enabled but it crashes on start and the debugger points me to:

[win32window.cpp](https://github.com/edubart/otclient/blob/master/src/framework/platform/win32window.cpp#L326)

``` c++
if(m_eglDisplay == EGL_NO_DISPLAY)
        g_logger.fatal("EGL not supported");
```

I'm using Windows 7 and compiled with MSVC 2013 with the [AMD OpenGL ES SDK](http://developer.amd.com/tools-and-sdks/graphics-development/amd-opengl-es-sdk/)

**Comment by Tazer89** [comment]
Any progress on this? :)

**Comment by conde2** [comment]
I succeed by using MinGw compiler instead of Visual Studio

**Comment by Tazer89** [comment]
Oh i give it a try :)

**Comment by Tazer89** [comment]
@conde2 I cant get it work. Are you intressted to share it? :)

**Comment by Tazer89** [comment]
I was click in directx in Cmake but give error.

Please set them or make sure they are set and tested correctly in the CMake files:
DirectX_D3DX9_LIBRARY (ADVANCED)

**Comment by conde2** [comment]
Just put OPENGL_ES=2 and dont use the checkbox

**Comment by Tazer89** [comment]
@conde2 in cmake it says only OPENGL not OPENGL_ES and when a change OPENGL to 2 does not enable it. I also tried to add an entry with OPENGL_ES but dident work either. Where shall i add the OPENGL_ES=2?
