### ISSUE TITLE
New Animations

### ISSUE THREAD

**Issue by conde2** [edubart/otclient#591]
I want to discuss what is needed to add the new Tibia animations.
What was changed and what need to be done in the client and server.

If someone want to implement this features feel free to do it and i will appreciate.

**Comment by djseban** [comment]
Hey guys, and how the works on it are going? Unfortunately I'm not too familiar with OTClient's code, would fix it myself. Anyway, maybe someone have some clues?

**Comment by Nu77** [comment]
Looking forward for this too

**Comment by LuigiLazzari** [comment]
Any updates on this?

**Comment by iryont** [comment]
Please stop spamming issues. You are welcome to do it by yourself and make a pull request...

**Comment by Mignari** [comment]
This has been added in 74af47f
