### ISSUE TITLE
OTClient causes server console errors

### ISSUE THREAD

**Issue by Vanderlay** [edubart/otclient#608]
Hello,

This issue is nothing serious but can probably annoy some OT-owners who doesn't know how to code.
I am currently running a server and there's a player using OTC to play on my server.
He told me he uses version 0.6.5 rev0

The user case:
A player talks to NPC and opens trade dialog window.
He then takes some sell-able items from the inventory and puts it in a bag on the ground.
Now he presses "Sell all" button and the OTC have not refreshed the item list, causing the client to try to sell non-sell-able items(those that are on the ground).

This causes console errors on the server saying someone is trying to sell non-sell-able items.

Easy way to fix this is to just refresh the sell-able items when items are moved around in the inventory.

Thanks,
Vanderlay

**Comment by TheSumm** [comment]
Most likely a server issue.
