### ISSUE TITLE
Ghost outfit idling when walk!!!!

### ISSUE THREAD

**Issue by k7aesa7r** [edubart/otclient#609]
Trying edit the source to work with animations that have more than 3 phases like cipsoft new outfits from cliente 10.5+ as they dont have anymore 3 phases, they now have 6 or 9 frames per outfit, not sure.

I edited here:

    int footAnimPhases = getAnimationPhases() - 1;
    int footDelay = getStepDuration(true) / 3;

To

    int footAnimPhases = getAnimationPhases() - 1;
    int footDelay = (getStepDuration(true));

As my outfits dont have 3 phases and 9 i removed the / 3.
Also already tried with:

    int footAnimPhases = getAnimationPhases() - 1;
    int footDelay = getStepDuration(true) / 9;

The animation working perfeclty, from low to high speed but theres a 'ghost'.
I dont know why, but it show's a idle outfit each time i walk, could someone help?

There's a video:
https://www.youtube.com/watch?v=yR7_x9E6VfM&feature=youtu.be

**Comment by k7aesa7r** [comment]
Closed without any solution or answer, that Summ are the best!

**Comment by TheSumm** [comment]
From what I read this seems to be an issue with your modification and not something directly related to the existing code.
