### ISSUE TITLE
OTClient BUG OPCODE ?

### ISSUE THREAD

**Issue by SuggestName** [edubart/otclient#611]
I cant use opcodes in my otclient i got this erro

ERROR: Unable to send extended opcode 10, extended opcodes are not enabled
ERROR: Unable to send extended opcode 11, extended opcodes are not enabled
ERROR: Unable to send extended opcode 12, extended opcodes are not enabled

and in the server i got this

http://i.imgur.com/n2iG6kP.png

when i try to use function to check if is using the otclient.

My Client version

GPU GeForce GTX 550 Ti/PCIe/SSE2
OpenGL 4.4.0 NVIDIA 344.48
ERROR: unable to open audio device
Found work dir at 'C:/otclient-master/'
== application started at Dec 21 2014 00:53:38
OTClient 0.6.3 rev 0 (devel) built on Dec 14 2014 for arch x86

How i can active the opcodes ?

**Comment by TheSumm** [comment]
This should be fixed after https://github.com/edubart/otclient/commit/24b1526534abe99df25127e5e3f42c57d458b2c0.
If the issue still persists tell us.
