### ISSUE TITLE
OTClient Error with audio device

### ISSUE THREAD

**Issue by SuggestName** [edubart/otclient#612]
GPU GeForce GTX 550 Ti/PCIe/SSE2
OpenGL 4.4.0 NVIDIA 344.48
ERROR: unable to open audio device
Found work dir at 'C:/otclient-master/'
== application started at Dec 21 2014 00:53:38
OTClient 0.6.3 rev 0 (devel) built on Dec 14 2014 for arch x86

how i can solve this error ERROR: unable to open audio device

**Comment by conde2** [comment]
Same as:

https://github.com/edubart/otclient/issues/521

Please search before create a new issue.
