### ISSUE TITLE
Last hit gets the loot

### ISSUE THREAD

**Issue by Draco01** [edubart/otclient#619]
Hi,

I'm having a problem with the loot owner on my server 0.3.6, the player who gets the loot is the one who made the last hit. For example:
The player 1 is killing a creature with 100 of HP, he hits 95 poins. Then, come the player 2 that hit the last 5 points, and the player 2 gets the loot.

For me, that is annoying and unfair, so i want to change it. It want that the player who hited more (in my example, it would be player 1) gets the loot.

Please, can you help me? I have no ideia where should i change my source.

Thanks for any help =D

**Comment by iryont** [comment]
Your problem lies within the server itself, not within the game client.
