### ISSUE TITLE
Outfit Frame

### ISSUE THREAD

**Issue by JoseEduardo** [edubart/otclient#620]
I wonder how the animation of the outfits of the tibia . have an outfit that is in a loop , " Animate Always" , but when I put it on a player he never starts frame 1 , starts in a random way (sometimes starts on Frame 2 , sometimes in the frame 3 ) .

Could someone explain to me why that happens and you have to work around this situation ?

Thank U

**Comment by TheSumm** [comment]
Which client version?

**Comment by JoseEduardo** [comment]
I'm using 10.41

**Comment by Mignari** [comment]
In outfit with "animated always" flag the frame is calculated by the client clock, so it appears in the same frame on all clients.
eg: A creature appears on client "A" and "B", but the client "B" has a small lag. When it appears on the client "B", will start in frame 1, but on the client "A" it's already in frame 2. To solve this, the frame is calculated by the clock.

```Lua
-- frame_count   total of frames
-- duration      duration of each frame. The value is 1000 milliseconds divided by frame_count.
-- elapsed_time  client clock

local duration = 1000 / frame_count
local frame = (elapsed_time % (duration * frame_count)) / duration;
```
