### ISSUE TITLE
[OPCODE] NOT THIS Sending OperatingSystem_t Correct

### ISSUE THREAD

**Issue by JoseEduardo** [edubart/otclient#622]
I'm trying to put OpCode in my server but not working , analyzing the source realized that this sending to the server as if it were CLIENTOS_WINDOWS when to send CLIENTOS_OTCLIENT_WINDOWS , anyone know where can I fix this ?

Thank U

**Comment by TheSumm** [comment]
Server version?

**Comment by JoseEduardo** [comment]
TFS 1.0
I have the latest version also do OtClient

**Comment by TheSumm** [comment]
I will check it these days.

**Comment by JoseEduardo** [comment]
You know me say Where should I look ?

**Comment by TheSumm** [comment]
Should be fixed in https://github.com/edubart/otclient/commit/24b1526534abe99df25127e5e3f42c57d458b2c0
