### ISSUE TITLE
Warnings compiling on Mac OS X and fatal error trying to run client

### ISSUE THREAD

**Issue by richigarza** [edubart/otclient#624]
after problems with lua library, i get this warnings:

In file included from /Users/richigarza/otclient/src/framework/net/outputmessage.cpp:24:
In file included from /Users/richigarza/otclient/src/framework/../framework/util/crypt.h:29:
In file included from /usr/local/include/boost/uuid/uuid.hpp:203:
/usr/local/include/boost/uuid/detail/uuid_x86.hpp:42:5: warning: 'register'
      storage class specifier is deprecated [-Wdeprecated-register]
    register __m128i mm = uuids::detail::load_unaligned_si128(data);
    ^~~~~~~~~
/usr/local/include/boost/uuid/detail/uuid_x86.hpp:53:5: warning: 'register'
      storage class specifier is deprecated [-Wdeprecated-register]
    register __m128i mm_this = uuids::detail::load_unaligned_si128(data);
    ^~~~~~~~~
/usr/local/include/boost/uuid/detail/uuid_x86.hpp:54:5: warning: 'register'
      storage class specifier is deprecated [-Wdeprecated-register]
    register __m128i mm_rhs = uuids::detail::load_unaligned_si128(rhs.data);
    ^~~~~~~~~
/usr/local/include/boost/uuid/detail/uuid_x86.hpp:61:5: warning: 'register'
      storage class specifier is deprecated [-Wdeprecated-register]
    register __m128i mm_left = uuids::detail::load_unaligned_si128(lhs.data);
    ^~~~~~~~~
/usr/local/include/boost/uuid/detail/uuid_x86.hpp:62:5: warning: 'register'
      storage class specifier is deprecated [-Wdeprecated-register]
    register __m128i mm_right = uuids::detail::load_unaligned_si128(rhs.data);
    ^~~~~~~~~
/usr/local/include/boost/uuid/detail/uuid_x86.hpp:64:5: warning: 'register'
      storage class specifier is deprecated [-Wdeprecated-register]
    register __m128i mm_cmp = _mm_cmpeq_epi32(mm_left, mm_right);
    ^~~~~~~~~
/usr/local/include/boost/uuid/detail/uuid_x86.hpp:74:5: warning: 'register'
      storage class specifier is deprecated [-Wdeprecated-register]
    register __m128i mm_left = uuids::detail::load_unaligned_si128(lhs.data);
    ^~~~~~~~~
/usr/local/include/boost/uuid/detail/uuid_x86.hpp:75:5: warning: 'register'
      storage class specifier is deprecated [-Wdeprecated-register]
    register __m128i mm_right = uuids::detail::load_unaligned_si128(rhs.data);
    ^~~~~~~~~
8 warnings generated.

In file included from /Users/richigarza/otclient/src/client/client.cpp:27:
In file included from /Users/richigarza/otclient/src/client/game.h:27:
In file included from /Users/richigarza/otclient/src/client/item.h:29:
/Users/richigarza/otclient/src/client/effect.h:38:10: warning: 'Effect::draw'
      hides overloaded virtual function [-Woverloaded-virtual]
    void draw(const Point& dest, float scaleFactor, bool animate, int of...
         ^
/Users/richigarza/otclient/src/client/thing.h:39:18: note: hidden overloaded
      virtual function 'Thing::draw' declared here: different number of
      parameters (4 vs 6)
    virtual void draw(const Point& dest, float scaleFactor, bool animate...
                 ^
1 warning generated.

AND when i try to run the client i get this error:

Linking CXX executable otclient
[100%] Built target otclient
macbook:build richigarza$ ./otclient 
FATAL ERROR: Unable to open X11 display
Assertion failed: (e == 0), function ~recursive_mutex, file /SourceCache/libcxx/libcxx-120/src/mutex.cpp, line 82.
Abort trap: 6

Greetings

**Comment by iryont** [comment]
These are just warnings. you have nothing to worry about. The client works just fine.

I will fix them as soon as I release the next version of my client for OS X.

**Comment by iryont** [comment]
```
FATAL ERROR: Unable to open X11 display
```

It seems like Quartz is missing from your computer or something is wrong with it, have you installed it?

**Comment by richigarza** [comment]
works if i run the client with the xterm console.

And crash with this error:
Assertion failed: (alGetError() == AL_NO_ERROR), function ~SoundBuffer, file /User/richigarza/otclient/src/framework/sound/soundbuffer.cpp, line 36.

**Comment by iryont** [comment]
Have a look at #340 

It hasn't been resolved yet, and personally I do not use sound.

**Comment by reyhammer** [comment]
Just remove the asserts functions, and it will work just fine.
There will be a bug when you try to decrease the sound of something to 0, however it all will work just fine.
