### ISSUE TITLE
ERROR: got a network message with invalid checksum (Latest TFS Sources)

### ISSUE THREAD

**Issue by jollejkpg** [edubart/otclient#625]
Otclient does not work anymore with the latest sources from TFS.

I get this error when I try to log in:
ERROR: got a network message with invalid checksum
at:
    [C++]: ?internalRecvData@Protocol@@AAEXPAEG@Z

**Comment by TheSumm** [comment]
Related to: https://github.com/otland/forgottenserver/commit/baa9263fe0c13310381381aba686726e0df25a3e
