### ISSUE TITLE
problem with the saving of map and etc..

### ISSUE THREAD

**Issue by Syeno** [edubart/otclient#626]
for some reason it is not saving nothing of the data that gets from the actual server like map and hotkeys... so I went into the log and saw this

== application started at Jan 26 2015 01:43:22
OTClient 0.6.5 rev 2197 (117833a) built on Jan  6 2014 for arch x86
ERROR: Unable to create write directory 'C:\Users\Dante12\otclient': unsupported
Startup done :]
Exiting application..

I also had a error message of a openAL32.dll missing...

**Comment by TheSumm** [comment]
Check if the folder was created

**Comment by Syeno** [comment]
it still doesn't work :(

**Comment by Exedenes** [comment]
im having the same issue, on kali linux x64. 
the folder was created but is empty. I have tried to change the permissions but it doesnt seem to make any difference.


OTClient 0.6.6 rev 0 (devel) built on Nov 29 2017 for arch x64
ERROR: Unable to create write directory '/root/.otclient': unsupported
