### ISSUE TITLE
Tibia client 8.5 ERROR when loading dat

### ISSUE THREAD

**Issue by b3liar** [edubart/otclient#634]
I try make my own Tibia Ot client on anime server.
I start from testing ot client on my server, i just download https://github.com/edubart/otclient this folder and put into it http://otland.net/threads/otclient-builds-windows.217977/ this latest client everything start normally all are great, but when i want to enter game i got error : "

GPU GeForce GTX 660/PCIe/SSE2
OpenGL 4.5.0 NVIDIA 347.25
== application started at Feb 09 2015 09:21:13
OTClient 0.6.5 rev 0 (devel) built on Jul 15 2014 for arch x86
Startup done :]
ERROR: Failed to read dat '/things/850/Tibia.dat': corrupt data'

And client say " You connection has been lost.
Either your network or the server went down. (ERROR 2)"

**Comment by b3liar** [comment]
no one answer lol

**Comment by TheSumm** [comment]
Test it with the latest commit "lol"

**Comment by b3liar** [comment]
tested with "otclient-fe585d27d8"

**Comment by b3liar** [comment]
i can upload my Dat and Spr for you if you want ;)

**Comment by b3liar** [comment]
I must edit something in my server to able ot client connect ?

**Comment by TheSumm** [comment]
Cannot reproduce this issue, not corrupt data exception on latest commit.
