### ISSUE TITLE
Space between tab buttons.

### ISSUE THREAD

**Issue by Anastaciaa** [edubart/otclient#635]
Where can i set space between these tab buttons?
![nowy obraz mapy bitowej](https://cloud.githubusercontent.com/assets/6841661/6116215/e34aceec-b0a2-11e4-9d42-905eee54e9db.png)
Couldn't find myself

**Comment by hrsantiago** [comment]
Maybe you can add a margin-left to the $!first button.

**Comment by Anastaciaa** [comment]
If you mean in 20-tabbars.otui im almost sure i tried everything. $!first and $first just doesn't react on any changes.

**Comment by Anastaciaa** [comment]
Summ any ideas how to fix it?

**Comment by margohq** [comment]
Probably in data/styles/20-tabbars.otui

**Comment by TheSumm** [comment]
Use
```
consoleTabBar:setTabSpacing(4)
```
or
```
tab-spacing: 4
```

**Comment by Anastaciaa** [comment]
Great Summ!
