### ISSUE TITLE
RSA_decrypt

### ISSUE THREAD

**Issue by b3liar** [edubart/otclient#639]
When i try log in from ot client on my server i got error : "[Warning - Protocol::RSA_decrypt] First byte != 0" 

Hmm i dont know how to fix it, any help ? :)

**Comment by TheSumm** [comment]
Which server is it?

**Comment by Anastaciaa** [comment]
Wrong rsa

**Comment by b3liar** [comment]
TFS 0.3.5 link to ot serv : bleachwo.zapto.org

**Comment by TheSumm** [comment]
That's a custom server..
