### ISSUE TITLE
Right clicking and Usewith bug

### ISSUE THREAD

**Issue by conde2** [edubart/otclient#644]
Everything started before this commit  !!!!!!
https://github.com/edubart/otclient/commit/900ebbd985200e2ab52c77d900d6174255f04023

Protocol 10.41
Latest Update.

Problem with Usewith !

![image](https://cloud.githubusercontent.com/assets/2137569/6453601/73ac822e-c11e-11e4-8aa9-7c5d34974774.png)

When trying to usewith in itemId 1490 it uses item 4722 (border) !!!

Problem with Right clicking !

What I have is:
Stakcpos: 0 itemId: 413 -- ground
Stakcpos: 1 itemId: 4804 -- border
Stakcpos: 2 itemId: 1644 -- counter
Stakcpos: 3 itemId: 1414 -- coffin

When trying to use itemId 1414 it does not use the item instead it uses something else.
The problem seems to be with the counter !
OBS: Works on tibia client !!

**Comment by Mignari** [comment]
@BenDol  I checked and 'thing->isGroundBorder' is necessary in this line:
https://github.com/edubart/otclient/blob/900ebbd985200e2ab52c77d900d6174255f04023/src/client/tile.cpp#L488

BWT: Why not use just one loop? like:
```C++
ThingPtr Tile::getTopMultiUseThing()
{
    if(isEmpty())
        return nullptr;

    if(CreaturePtr topCreature = getTopCreature())
        return topCreature;

    for(uint i = 0; i < m_things.size(); ++i) {
        ThingPtr thing = m_things[i];
        if(thing->isForceUse())
            return thing;

        if(!thing->isGround() && !thing->isGroundBorder() && !thing->isOnBottom() && !thing->isOnTop()) {
            if (i > 0 && thing->isSplash())
                return m_things[i - 1];
            return thing;
        }

        if(!thing->isGround() && !thing->isOnTop())
            return thing;
    }

    return m_things[0];
}

```

**Comment by BenDol** [comment]
I didn't write this method so you would have to ask @edubart why he did it this way, probably just code progression traces through updates just didn't get merged or something. Also why is thing->isGroundBorder() necessary here?

**Comment by hrsantiago** [comment]
In many loops, isForceUse items in the tile have priority over others. In a single for, an isForceUse item might not be used because it's below on the stack.

**Comment by Mignari** [comment]
Hmm. I'm not sure, but 'MultiUse' is used for 'UseWith', so in this case is more important to find it first that 'ForceUse'. Maybe that is the issue. I will make more tests later.

This is an AS3 function based on flash client:
```ActionScript
public function getTopMultiUseObject():Thing
{
    if (m_thingsCount > 0)
    {
        var index:uint = 0;
        while (index < m_thingsCount) {
            var tmp:Thing = m_things[i];
            if (tmp.isForceUse || (!tmp.isGround && !tmp.isGroundBorder && !tmp.isOnBottom && !tmp.isOnTop)) {
                break;
            }
            index++;
        }

        var thing:Thing = m_things[index];
        if (index > 0 && !thing.isForceUse && thing.isLiquidPool) {
            thing = m_things[index - 1];
        }
        return thing;
    }
    return null;
}
```

**Comment by hrsantiago** [comment]
It's probably trickier than that. This behaviour might change between different versions.

**Comment by Zbizu** [comment]
https://github.com/otland/forgottenserver/issues/1225

**Comment by Mignari** [comment]
My pull request still does not fix all the reported bugs. Sorry.
I have tested an implementation based on flash client which seems to work well for all cases.
I need some people to test this before I do a PR.

https://github.com/ottools/otclient/commit/5213569662ebfa9e6dc626d6d101507c18a5828c

**Comment by Zolias** [comment]
Does anyone have a working fix for this? I still have the issue with the latest commits.

**Comment by vfjpl** [comment]
https://github.com/edubart/otclient/pull/1113
