### ISSUE TITLE
Compiling on Debian Wheezy 7.8

### ISSUE THREAD

**Issue by marcosx86** [edubart/otclient#646]
Ello Guys,

A week ago I've build successfully the master branch on my Linux host (64-bits). But just now I pulled the last changes and tried to CMake, when I got this:

make[2]: *** No rule to make target `/usr/lib/libGL.so', needed by `otclient'.  Stop.
make[1]: *** [CMakeFiles/otclient.dir/all] Error 2
make: *** [all] Error 2

Maybe a CMake script typo?

**Comment by marcosx86** [comment]
My ldconfig -p:

root@desktop:~# ldconfig -p | grep libGL
	libGLU.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libGLU.so.1
	libGLU.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libGLU.so
	libGLEW.so.1.7 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libGLEW.so.1.7
	libGLEW.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libGLEW.so
	libGL.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libGL.so.1
	libGL.so (libc6,x86-64, OS ABI: Linux 2.4.20) => /usr/lib/x86_64-linux-gnu/libGL.so
root@desktop:~# 

As you can see, I have it, but the current config cannot find it, the previous was ok.

**Comment by Anastaciaa** [comment]
i recommended VS 2013 to compile

**Comment by marcosx86** [comment]
Actualy I'm on Debian Linux, I've compiled before, now it doesn't.

--
Marcos Silva Cunha
Enviado do meu Android

**Comment by marcosx86** [comment]
This is my "cmake ..":

-- Link to static libraries: ON
-- Build type: RelWithDebInfo
-- Build commit: devel
-- Build revision: 0
-- Boost version: 1.49.0
-- Found the following Boost libraries:
--   system
--   thread
--   filesystem
--   chrono
-- LuaJIT: OFF
-- Debug information: ON
-- Crash handler: ON
-- OpenGL ES: OFF
-- Bot protection: ON
-- Use precompiled header: OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /home/marcos/Laboratory/Git/edubart_otclient/build

Is there missing something?

**Comment by marcosx86** [comment]
Nevermind, just worked. I forgot to delete build dir after reinstalling my Linux box, was linked with last system platform. Current "cmake ..", this one worked.

-- The C compiler identification is GNU 4.7.2
-- The CXX compiler identification is GNU 4.7.2
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Link to static libraries: ON
-- Build type: RelWithDebInfo
-- Build commit: devel
-- Build revision: 0
-- Boost version: 1.49.0
-- Found the following Boost libraries:
--   system
--   thread
--   filesystem
--   chrono
-- Found Lua: /usr/lib/x86_64-linux-gnu/liblua5.1.a  
-- LuaJIT: OFF
-- Found PHYSFS: /usr/lib/libphysfs.a  
-- Found OPENSSL: /usr/lib/x86_64-linux-gnu/libssl.a;/usr/lib/x86_64-linux-gnu/libcrypto.a  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.a  
-- Debug information: ON
-- Crash handler: ON
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found GLEW: /usr/lib/x86_64-linux-gnu/libGLEW.so  
-- OpenGL ES: OFF
-- Found OPENAL: /usr/lib/x86_64-linux-gnu/libopenal.so  
-- Found VORBISFILE: /usr/lib/x86_64-linux-gnu/libvorbisfile.a  
-- Found VORBIS: /usr/lib/x86_64-linux-gnu/libvorbis.a  
-- Found OGG: /usr/lib/x86_64-linux-gnu/libogg.a  
-- Bot protection: ON
-- Use precompiled header: OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /home/marcos/Laboratory/Git/edubart_otclient/build
