### ISSUE TITLE
Client works on pc but not notebook

### ISSUE THREAD

**Issue by Muphet** [edubart/otclient#651]
Hi,

i recently started playing tibia for fun (nostalgia) and downloaded otclient 0.6.5 branch pre-compiled.
It works perfectly on my pc, but when i copy/paste files to my notebook, which uses same OS, same latest drivers and all of that, client DOESN'T START at all. just nothing happens after launching .exe

I know it worked earlier because i've played on random pokemon~ server that was using otclient.
Whats the issue?

**Comment by TheSumm** [comment]
Always use the latest version, if the issue still persists try to help us reproduce it.

**Comment by Muphet** [comment]
actually, it worked with older version..
