### ISSUE TITLE
Compiled on OSX, but failed to start binary

### ISSUE THREAD

**Issue by G4BB3R** [edubart/otclient#652]
After much pain I sucessfull compiled otclient on OSX, because I am still new to it.
Then it generates otclient file in otclient/build/ folder.
But when I do sudo ./otclient or ./otclient appear this message:

FATAL ERROR: Unable to open X11 display
Assertion failed: (e == 0), function ~recursive_mutex, file /SourceCache/libcxx/libcxx-120/src/mutex.cpp, line 82.
Abort trap: 6

How to solve ?
Thanks

**Comment by G4BB3R** [comment]
Bump ?

**Comment by diath** [comment]
>FATAL ERROR: Unable to open X11 display
As far as I know OS X doesn't provide X11 out of the box (it uses a different display server), you need to install XQuartz.
