### ISSUE TITLE
Connect DAT / SPR one version and connect to a different version of server

### ISSUE THREAD

**Issue by JoseEduardo** [edubart/otclient#656]
What I would like to know if this is possible, connect ha a server with the SPR and DAT another version, I can load an SPR / DAT and I connect on another version, however is that returns me many mistakes and ends up mangled the sprites.

**Comment by JoseEduardo** [comment]
One thing I do not understand is why close the issues without giving at least one explanation ....

**Comment by TheSumm** [comment]
Because you asked a question and did not report a issue.B

**Comment by JoseEduardo** [comment]
This seeing is already a explanation ^^
