### ISSUE TITLE
Fast attack dont work 

### ISSUE THREAD

**Issue by Ravene** [edubart/otclient#657]
hi 
when i try use fast attack work on 7.6 tibia client but when i use otclient this dont work i see sloow attack

**Comment by TheSumm** [comment]
Fast attack is not client sided, the server handles attacking..

**Comment by Ravene** [comment]
@TheSumm 100% client side when i use tibia client 7.6 working!!! when i use otclientdont work

**Comment by Nu77** [comment]
Where are you testing ? TFS 1.x not support a high number of fast attack and i think this 7.6 server support :)

**Comment by Ravene** [comment]
@Nu77 on my own source code 7.6 and is 100% client side the same problem i have on light when i use spells is limited on client side

**Comment by Nu77** [comment]
Damage is the same on both clients? If yes, the damage numbers are being merged.

**Comment by Ravene** [comment]
on a normal working client
