### ISSUE TITLE
TALKTYPE_PRIVATE_NP 10.76

### ISSUE THREAD

**Issue by gugahoa** [edubart/otclient#658]
ERROR: unhandled onTalk message mode 50: Welcome Elwyn! Do you want to go to the {decay village}?

On CipSoft's Client it works

**Comment by LeandroPerrotta** [comment]
You can fix the problem editing the file modules/game_console/console.lua adding the following code in the begin of function onTalk:

```
  if mode == MessageModes.NpcFromStartBlock then
    mode = MessageModes.NpcFrom
  end
```

Credits go to Summ:

https://otland.net/threads/10-76-cant-talk-with-npcs.230021/
