### ISSUE TITLE
Static libs not working

### ISSUE THREAD

**Issue by iLeet** [edubart/otclient#662]
I compiled OTClient for Windows using the CMake option to use static libs, so others can use it.
However it asks for a libboost_crono dll on start. Any idea?

**Comment by dominique120** [comment]
If it asks for it then why dont you download it and place it with the executable?

**Comment by iLeet** [comment]
It wasn't one I was able to find it, since the name changes if you change
the project name. However compiling with static libs should avoid this all
together.

**Comment by iryont** [comment]
CMake does not always link to valid libraries, so in your case I would just remove dynamic libraries and let cmake find the proper ones.

In any case it's not related to the client itself.
