### ISSUE TITLE
Cleaning OTClient

### ISSUE THREAD

**Issue by conde2** [edubart/otclient#663]
@iryont
@edubart 
@hrsantiago
@TheSumm 

In the past we had an idea that OTC could work for any propose, from a Map Editor to a Dat Editor so a lot of code has been added to OTC in order to supply this need, in my opinion we need to focus in only one thing, the Client itself !! For other propose forks can be done !
So I would like to know if we can clean the sources from this codes and get a smaller and faster OTC optimize to what its suppose to be ( a Client for OpenTibia). Another point is that by doing this I think it will be easier to maintain and update.

**Comment by iryont** [comment]
I do understand what you mean, but is there really a point in that? The extra code does not impact performance of the client itself at all, and barely makes the whole executable any larger (it's 3.9 MB here with release build using msvc, boost statically linked).

Also, most of those extra features are within separated "modules" (otbm loader, house loader, and so on) and they are not used by any current client module (unless you create one). Besides making the executable a bit larger there are no other disadvantages, however, on the other hand we have plenty of advantages.

**Comment by edubart** [comment]
I agree with @iryont, the extra code does not impact on performance and gives us other possibilities. The project was not intended to be just a client, it mainly is but is also a framework for creating tools. The fact that there aren't much great tools made with otclient out there yet does not mean that they doesn't exist or will exist and I don't want to remove that possibility.

**Comment by conde2** [comment]
In my opinion the code is getting confuse because those additions, to much complexity has been added. This may be keeping newcomers away...
