### ISSUE TITLE
Link Broken to download the code in "Compiling in windows"

### ISSUE THREAD

**Issue by Obsdark** [edubart/otclient#666]
That it's the issue

i suggest to fix it, it send the person to the download page of another person, go ahead, try it.

Thanks in advance for the proyect & your work

Cheers up

**Comment by ronpetit** [comment]
Is just a old tutorial, go here to download the code:

https://github.com/edubart/otclient/archive/master.zip

**Comment by TheSumm** [comment]
Should work now.
