### ISSUE TITLE
Maximum of 100 child widgets

### ISSUE THREAD

**Issue by mockthebear** [edubart/otclient#667]
Ive noticed that when you keep adding widgetds with the function
eg: g_ui.createWidget('ConsoleLabel', consoleBuffer)
and set an id like "thisid"..n
the maximum widget show is 100. Ive checked almost all options and the sourcecode and found nothing. I've just found the shared_object_ptr in framework and nothing...
Where is the place to raise the children limit on a widget? o.o

**Comment by iryont** [comment]
https://github.com/edubart/otclient/blob/master/modules/game_console/console.lua#L55
https://github.com/edubart/otclient/blob/master/modules/game_console/console.lua#L584

**Comment by mockthebear** [comment]
oh my god. i should kill myself now. this was in my face and i didnt see

**Comment by iryont** [comment]
It happens, nothing to worry about.
