### ISSUE TITLE
sendAttack and sendFollow, sequence number?

### ISSUE THREAD

**Issue by gesior** [edubart/otclient#668]
In **client/protocolgamesend.cpp** there is:

    void ProtocolGame::sendAttack(uint creatureId, uint seq)
    {
        OutputMessagePtr msg(new OutputMessage);
        msg->addU8(Proto::ClientAttack);
        msg->addU32(creatureId);
        msg->addU32(seq);
        send(msg);
    }

    void ProtocolGame::sendFollow(uint creatureId, uint seq)
    {
        OutputMessagePtr msg(new OutputMessage);
        msg->addU8(Proto::ClientFollow);
        msg->addU32(creatureId);
        msg->addU32(seq);
        send(msg);
    }

I don't know why, but no matter if I send 'seq' or not (comment code) it works fine with my 7.72 server.
As I remember 'seq' part of packet was introduced in 8.60 protocol [on server side it was 'always 0'].

In 7.72 server code there is only one uInt32 read:

    void ProtocolGame::parseAttack(NetworkMessage& msg)
    {
        uint32_t creatureId = msg.GetU32();

        addGameTask(&Game::playerSetAttackedCreature, player->getID(), creatureId);
    }

**Comment by iryont** [comment]
Indeed, the function should look like that:

```cpp
void ProtocolGame::sendFollow(uint creatureId, uint seq)
{
    OutputMessagePtr msg(new OutputMessage);
    msg->addU8(Proto::ClientAttack);
    msg->addU32(creatureId);
    if(g_game.getFeature(Otc::GameAttackSeq))
        msg->addU32(seq);
    send(msg);
}
```

I will fix soon enough.
