### ISSUE TITLE
Error on boost??

### ISSUE THREAD

**Issue by mockthebear** [edubart/otclient#675]
I am trying compile the client. One day it was okay, i was compiling. But then:

||=== Build: all in otclient (compiler: GNU GCC Compiler) ===|
c:\mingw\include\boost\asio\detail\impl\socket_select_interrupter.ipp||In member function 'void boost::asio::detail::socket_select_interrupter::open_descriptors()':|
0|8|error: expected unqualified-id before numeric constant|
c:\mingw\include\boost\asio\detail\impl\socket_select_interrupter.ipp|81|error: request for member 'get' in '1', which is of non-class type 'int'|
c:\mingw\include\boost\asio\detail\impl\socket_select_interrupter.ipp|84|error: request for member 'get' in '1', which is of non-class type 'int'|
c:\mingw\include\boost\asio\detail\impl\socket_select_interrupter.ipp|94|error: request for member 'get' in '1', which is of non-class type 'int'|
c:\mingw\include\boost\asio\detail\impl\socket_select_interrupter.ipp|99|error: request for member 'get' in '1', which is of non-class type 'int'|
c:\mingw\include\boost\asio\detail\impl\socket_select_interrupter.ipp|113|error: request for member 'release' in '1', which is of non-class type 'int'|
CMakeFiles\otc_framework.dir\build.make|54|recipe for target 'CMakeFiles/otc_framework.dir/src/framework/luafunctions.cpp.obj' failed|
CMakeFiles\Makefile2|59|recipe for target 'CMakeFiles/otc_framework.dir/all' failed|
C:\Users\Mock\Documents\GitHub\otPokemon-Cliente\client2\otclient-master\Makefile|116|recipe for target 'all' failed|
||=== Build failed: 9 error(s), 0 warning(s) (0 minute(s), 21 second(s)) ===|

i have changed nothing, this just started from nowhere. I haven't updated the libs

**Comment by gesior** [comment]
Did you install Visual Studio or compile 'forgottenserver 1.0+' between compilations?

**Comment by mockthebear** [comment]
Actually i did not.
This just happened. I get in my notebook <i havent touched it in months> and i got the same error.
i will check the #670

**Comment by mockthebear** [comment]
#670 not worked at all.
i am using mingw32-make to compile and got the same problem.
