### ISSUE TITLE
Problem on compiling with mac

### ISSUE THREAD

**Issue by mockthebear** [edubart/otclient#679]
Actually i was helping a friend to compile. i found one issue on tutorial. you have to instal openal...

An then i got this error:

MacBook-Pro-de-Felipe:build felipeaugusto$ make -j4
[  0%] [  1%] [  2%] [  3%] Building CXX object CMakeFiles/otclient.dir/src/framework/util/color.cpp.o
Building CXX object CMakeFiles/otclient.dir/src/framework/luafunctions.cpp.o
Building CXX object CMakeFiles/otclient.dir/src/framework/util/crypt.cpp.o
Building CXX object CMakeFiles/otclient.dir/src/framework/stdext/demangle.cpp.o
error: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Werror,-Wunknown-warning-option]
make[2]: *** [CMakeFiles/otclient.dir/src/framework/util/color.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
error: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Werror,-Wunknown-warning-option]
make[2]: *** [CMakeFiles/otclient.dir/src/framework/luafunctions.cpp.o] Error 1
make[2]: *** [CMakeFiles/otclient.dir/src/framework/util/crypt.cpp.o] Error 1
error: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Werror,-Wunknown-warning-option]
make[2]: *** [CMakeFiles/otclient.dir/src/framework/stdext/demangle.cpp.o] Error 1
make[1]: *** [CMakeFiles/otclient.dir/all] Error 2
make: *** [all] Error 2

Probly the compiler in mac dont reconize this flag and abort.

**Comment by iryont** [comment]
That's most likely because your compiler is highly outdated.

Get a clang from newest Xcode and use it instead of outdated gcc.
