### ISSUE TITLE
ARM (Rpi2) compilation problem

### ISSUE THREAD

**Issue by marek677** [edubart/otclient#681]
I tried to compile OTC on my raspberry pi. It worked. To enchance FPS (1 was not enough) i changed one of the graphics options from OFF to 2.0 - that was responsible for OpenGL ES 2.0 i believe.

CMake returned me some errors - here is full log:
pi@raspberrypi ~/otclient/build $ cmake ..
-- The C compiler identification is GNU 4.6.3
-- The CXX compiler identification is GNU 4.6.3
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Link to static libraries: ON
-- Build type: RelWithDebInfo
-- Build commit: devel
-- Build revision: 0
-- Boost version: 1.49.0
-- Found the following Boost libraries:
--   system
--   thread
--   filesystem
--   chrono
-- Found Lua: /usr/lib/arm-linux-gnueabihf/liblua5.1.a
-- LuaJIT: OFF
-- Found PHYSFS: /usr/lib/libphysfs.a
-- Found OPENSSL: /usr/lib/arm-linux-gnueabihf/libssl.a;/usr/lib/arm-linux-gnueabihf/libcrypto.a
-- Found ZLIB: /usr/lib/arm-linux-gnueabihf/libz.a
-- Debug information: ON
-- Crash handler: ON
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:97 (MESSAGE):
  Could NOT find OpenGLES2 (missing: OPENGLES2_LIBRARY OPENGLES2_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:288 (_FPHSA_FAILURE_MESSAGE)
  src/framework/cmake/FindOpenGLES2.cmake:15 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/framework/CMakeLists.txt:295 (find_package)
  CMakeLists.txt:12 (include)

Hope someone could help me ;)
Thanks in advance, regars,
Marek

**Comment by iryont** [comment]
You had 1 fps because it was running under software rasterizer :)

Take a look inside /var/opt/include and /var/opt/lib whether you have OpenGL ES 2.0 stuff there. If so, you can always manually set the path which is really easy.
