### ISSUE TITLE
Consuming too much memmory after long time open

### ISSUE THREAD

**Issue by mockthebear** [edubart/otclient#684]
Well, i have made some testes. With the client loged in any server and still, the memmory keeps the same. But when you walk the memmory keeps increasing.

The reason its because the map cache stills in memmory. When you walk through a an area, this keep saved on memmory. You can see if by pressing zoom out.

The problem is that when you walk long distances with the client, you can get around 500mb use on client.

There is some whay to clear this map cache?

**Comment by iryont** [comment]
https://github.com/edubart/otclient/blob/master/src/client/map.cpp#L490

You can include another piece of code there to free invisible tiles.
