### ISSUE TITLE
#Bug. Client can't load game window when you send more game tiles to it.

### ISSUE THREAD

**Issue by DarkShinz** [edubart/otclient#685]
This bug happens, SOMETIMES, if you have set up your client to receive more tiles than usual and when you try to login in game or change floors, if the floor above you is fulfilled with any type of ground.

How do I know that is it? I've done many sources tries, from server side and I've figured out that the server don't call MoveUP or MoveDown functions, but it's not related at all with the bug. So, when the character was in a bugged spot and I try a login, the server informs that the character logged sucessfully in, but the client doesn't load the game window, it freezes at the loading screen and popup some errors related to these functions "parseCreatureMove" "getMappedThing". 

So, I've made map tests and remove whatever was below the character and kept cleaning the floor above until the client loads the game window sucessfully. I've done it many times, and in all situations it worked. But at some map structures you can't just clean the floor above.

If someone can help me to fix this, it would be great to improve the support of OTClient at adding more game window tiles.

I think this bug is somewhere between the parsing skills of OTClient related to the "sendMapDescription" function from the server.

**Comment by TheSumm** [comment]
What did you change in Otclient?

**Comment by DarkShinz** [comment]
I did changed this in map.h, so it can load the new value sent by the server. This is the only change regarding to this issue. 

{              static const int32_t maxViewportX = 15;
		static const int32_t maxViewportY = 15; 
		static const int32_t maxClientViewportX = 14;
		static const int32_t maxClientViewportY = 8;                                                    }

At parseCreatureMove or getMappedThing I tried a few things, but then I reverted it back to the original.

**Comment by 4drik** [comment]
I've made more tiles in the old 7.6 and everything is working,
At higher protocols it is trivially easy.
You have not changed everything you should.

**Comment by DarkShinz** [comment]
@4drik could you tell me where else I should go?

**Comment by DarkShinz** [comment]
@4drik Oh sorry, I've added a change I've made at the server at the topic you saw before. I've fixed it.
