### ISSUE TITLE
#Bug.. Client don't load/draw game window.

### ISSUE THREAD

**Issue by DarkShinz** [edubart/otclient#686]
![bugotclient](https://cloud.githubusercontent.com/assets/12613256/9984903/769dc416-5ff7-11e5-84fb-83507294b508.jpg)

Client ins't drawing or loading the game map when at some random places of the map and while configured properly to receive more tiles. (Tested it with brand new OTClient and Forgotten server at 10.76 protocol and at different maps).

Any guesses?

**Comment by iryont** [comment]
It's a bug within your game server.

**Comment by DarkShinz** [comment]
How can this be, if the client doesn't load the screen? and at the server it login the character?

**Comment by hrsantiago** [comment]
The server is sending some information that the client can't understand. It doesnt mean that it's the client fault and probably it's your server fault as this feature is used by some users with no complaints.
