### ISSUE TITLE
RSA Key

### ISSUE THREAD

**Issue by Warchas** [edubart/otclient#687]
I have googled and searched but I cannot find where to change the RSA key in the sources?
The only thing I found is a post by Summ but it makes no sense in how to change it.
He wrote and I quote 

"g_crypt.rsaSetPublicKey(YOUR_RSA, 65537);

Adjust gamelib/game.lua so it does not set the rsa too."

This makes no sense at all to me

**Comment by TheSumm** [comment]
https://github.com/edubart/otclient/blob/master/modules/gamelib/const.lua#L205-L215

**Comment by Warchas** [comment]
But that isn't for sources is it? That is simply the RSA in the game client, then a player can easily copy the RSA and then make their own client with a bot. Or am I wrong?

**Comment by Warchas** [comment]
Does this even show for you when I write now or do I need to make a new issue for you to see it?

**Comment by TheSumm** [comment]
g_game.setRsa just calls the function g_crypt.rsaSetPublicKey.
See: https://github.com/edubart/otclient/blob/master/modules/gamelib/game.lua#L42-L46

Crypt::rsaSetPublicKey is implemented in C++ so you can call it in C++ with your custom RSA public key. However, that will hardly make it more challenging for someone to find your RSA key as it still is a huge string..
https://github.com/edubart/otclient/blob/master/src/framework/util/crypt.h#L53

**Comment by Warchas** [comment]
Yes but you can compress the OTClient file to be not as easily read, just like you can do with the Tibia Client
