### ISSUE TITLE
RSA Key still not answered

### ISSUE THREAD

**Issue by Warchas** [edubart/otclient#688]
Below is what I wrote in my last post, I guess you don't see it since you closed my issue.
However if I change the RSA in the const.lua the players can simply take the const.lua and use their own modified client with bot or whatever. This is why I am asking how I change the RSA in the sources and not just on the surface where anyone can see it.

Thanks in advance

Warchas commented 3 hours ago
I have googled and searched but I cannot find where to change the RSA key in the sources?
The only thing I found is a post by Summ but it makes no sense in how to change it.
He wrote and I quote

"g_crypt.rsaSetPublicKey(YOUR_RSA, 65537);

Adjust gamelib/game.lua so it does not set the rsa too."

This makes no sense at all to me
 @TheSumm
Collaborator
TheSumm commented an hour ago
https://github.com/edubart/otclient/blob/master/modules/gamelib/const.lua#L205-L215
@TheSummTheSumm closed this an hour ago
@Warchas
  
Warchas commented an hour ago
But that isn't for sources is it? That is simply the RSA in the game client, then a player can easily copy the RSA and then make their own client with a bot. Or am I wrong?

**Comment by iryont** [comment]
Closed issues can still be addressed. Please do not create next issues since obviously it's not a bug within the client.

If you want to discuss it you are free to do so on otland.net within OTClient sub-forum.

RSA key is within const.lua and the key is set within lua. It can be changed anywhere, within terminal as well.

**Comment by Warchas** [comment]
Since I had no clue that they could still be addressed I opened the new, I won't do that again since you informed me otherwise now.

To my point though, is it possible to change the RSA key within the client? So that it is hidden and not in a file that can be opened with a regular textedit program?

Sincerely, 
Warchas.

Ps. sorry if I am stupid but I really do not understand if the const.lua is the way to do it, please elaborate if it is

**Comment by iryont** [comment]
Yes, you are correct. At the moment const.lua is the only way to change your RSA key. The key is set during login (client_entergame module).

https://github.com/edubart/otclient/blob/master/modules/client_entergame/entergame.lua#L332
https://github.com/edubart/otclient/blob/master/modules/gamelib/game.lua#L19

**Comment by Warchas** [comment]
But the client can be compiled with a bot, right? This is super easy for a player to use for botting then just simply recompile the client for your own use with a bot
