### ISSUE TITLE
AnimatedText merge crash.

### ISSUE THREAD

**Issue by ziomagic** [edubart/otclient#692]
When I am getting a lot of AnimatedText messages (No numbers), OTclient crash in AnimatedText::Merfe function.

I don't know why, but I am getting OTClient crased on all kind of exceptions (Even if LuaScript has some error, I am getting Visual Runtine Error)

What can be wrong?

**Comment by iryont** [comment]
Any specific line within the merge function?

**Comment by ziomagic** [comment]
safe_cast << When trying to cast text to number.
It should be handled by the catch(...) clause, but I am getting crash >.>

**Comment by iryont** [comment]
Which one exactly? There are two of those.

Can you include the whole crash log?
