### ISSUE TITLE
Using custom .dat .spr files.

### ISSUE THREAD

**Issue by slavidodo** [edubart/otclient#693]
Hello, gentles.
I am facing error when i add custom .dat files.
It gives error ->
         "ERROR: Failed to read dat '/things/1076/Tibia.dat': corrupt data (id: 3, category: 1, count: 255, lastAttr: 0)'"

Hmm , maybe there is a way to add custom .dat files, if there is so? help.
Thanks in advance.

**Comment by hrsantiago** [comment]
Ironyt closed this as it is not an otclient's issue. Check how you generated your dat file. For help you can access otland.net or any other forum. I believe that otclient's wiki has links to these places.
