### ISSUE TITLE
writeFileContents error

### ISSUE THREAD

**Issue by Anastaciaa** [edubart/otclient#696]
I was adding writeFileContents patch to save channel messages and then i noticed this error:

ERROR: protected lua call failed: LUA ERROR:
/game_console/console.lua:738: attempt to call field 'writeFileContents' (a nil value)
stack traceback:
    [C]: in function 'writeFileContents'
    /game_console/console.lua:738: in function 'optionCallback'
    /corelib/ui/uipopupmenu.lua:62: in function </corelib/ui/uipopupmenu.lua:60>

My corelib/util.lua contains new "protectedcall" function

**Comment by diath** [comment]
The function doesn't seem to be registered to Lua, try adding it here: https://github.com/edubart/otclient/blob/master/src/framework/luafunctions.cpp#L176

**Comment by iryont** [comment]
Apparently I did forget to register it.

**Comment by Anastaciaa** [comment]
Thanks
