### ISSUE TITLE
How to cycleEvent with botProtection?

### ISSUE THREAD

**Issue by Anastaciaa** [edubart/otclient#701]
Hello otclient masters,

It's possible to use functions in event with bot_protection feature?
for example i want to excute event like this one but bot protection caught it

>cycleEvent(function()
 >g_game.talkChannel(7, 5, "text")
>end, 2000)

**Comment by hrsantiago** [comment]
Probably you should rethink what you're doing. Isn't there another way to do it?

**Comment by Anastaciaa** [comment]
Im trying to make trade messager every 2 mins, but bot protection doesnt allow me to do that.
Any ideas how to solve it without removing bot protection?

**Comment by hrsantiago** [comment]
Make it server side

**Comment by Anastaciaa** [comment]
Yea i thought about it but before i had to see your opinion. Not possible to do through client side with bot protection so ill close this issue.
