### ISSUE TITLE
OTClient arm android

### ISSUE THREAD

**Issue by Szybol7** [edubart/otclient#703]
Hi i have problem.
Android version otclient wrong decode xtea.

LOG:
01-10 22:05:22.617 32685 32704 I OTClientMobile: ERROR: invalid decrypted network message
01-10 22:05:22.617 32685 32704 I OTClientMobile: at:
01-10 22:05:22.617 32685 32704 I OTClientMobile:        [C++]: Protocol::xteaDecrypt
01-10 22:05:22.617 32685 32704 I OTClientMobile: ERROR: failed to decrypt message
01-10 22:05:22.617 32685 32704 I OTClientMobile: at:
01-10 22:05:22.617 32685 32704 I OTClientMobile:        [C++]: Protocol::internalRecvData

**Comment by Tulioh** [comment]
Yeah. I don't know the cause of this problem, because sometimes it works. :/

**Comment by hrsantiago** [comment]
It usually happens when the message is too big. So the packet comes incomplete.

**Comment by Tulioh** [comment]
Why the same code works on desktop and not on mobile?

**Comment by hrsantiago** [comment]
It might be related with the area that you login or what data is sent. Maybe in your case additional information is sent to mobile clients.

**Comment by Tulioh** [comment]
The same code including lua files are used. I did not changed the packages
sent and nor additionals info.

**Comment by Nu77** [comment]
It happens when you try to login or in client setup?

**Comment by Tulioh** [comment]
It happens on login.

2016-01-11 13:01 GMT-02:00 Nu77 <notifications@github.com>:

**Comment by Nu77** [comment]
@Tulioh Maybe it's related to client_stats module? Can you try removing it and test again?

**Comment by Tulioh** [comment]
Hmm... I will try. Thanks ;)

2016-01-11 14:12 GMT-02:00 Nu77 <notifications@github.com>:

**Comment by Tulioh** [comment]
@Nu77 I tried removing client_stats and the error kept. :(

**Comment by Anastaciaa** [comment]
print the message on windows and android then compare

**Comment by iryont** [comment]
It happens due to architecture difference between x86 and ARM. I won't solve it for you, but the issue is trivial and I will give you a hint of how to solve it . However, I expect someone to actually fix it within the repository.

The issue happens when the key parts (saved as four integer values) are "bigger" than 0x7fffffff. That kind of hint should be more than enough for someone to solve it in no time.
