### ISSUE TITLE
Market place

### ISSUE THREAD

**Issue by Tazer89** [edubart/otclient#707]
When try to open market place this error shows on terminal and no windows popups.

ERROR: /game_market/market.lua:729: bad argument #1 to 'insert' (table expected, got nil)

**Comment by TheSumm** [comment]
Which server did you play on, which client version?
Do you know which server engine was used?

**Comment by eduardodantas95** [comment]
@TheSumm I have this error, using version 1099 and .dat of 10 (sprites of tibia 12)
If i use the .dat of tibia 1099 no have the erro. 
You can help ?
