### ISSUE TITLE
Compilation ERROR with BOOST

### ISSUE THREAD

**Issue by ricardozanardo** [edubart/otclient#708]
Hello guys, I've tried thousands of times with lots of combinations, using VS2015 and VS2013, lots of versions of bost and everytime I got a bunch of erros.

The only set of libs that really worked (or at least looked like it was working) was VS2013 + boost 1.59.0.0

Everything was building fine until the very end, when I got this error message:

cannot open file 'libboost_thread-vc120-mt-1_59.lib'

Can someone explain me or tell me how to solve it? I'm out of ideas to keep trying.

Just remembering : with ms2013 and boost 1.59 I didn't even get a warning message, nothing, just this error at the very end.

Thanks in advance!!!!

**Comment by WibbenZ** [comment]
Next time; https://otland.net/forums/support.16/
Try VS15 and boost 1.60, works just fine but you will get a couple of warnings.
Regarding the error, download the new libs for VS15.

**Comment by linkinbr** [comment]
Sorry for posting it here, I had no other place to try!
I tried what u said but now its complaining that "libvorbis" was compiled with an older version or something... I tried but couldn't find the other necessary libs by my own... 

can you please help me? if you could please contact me by email ricardo.zanardo@gmail.com

thanks in advance and sorry again!

**Comment by WibbenZ** [comment]
Recompile vorbis and one more (can't remember the name) using vs15, then recompile the project.
