### ISSUE TITLE
Follow square doesn't disappear

### ISSUE THREAD

**Issue by Anastaciaa** [edubart/otclient#709]
Hello,
Today i noticed that follow square won't disappear if FOLLOWED player will go upstairs and back downstairs. It happens only if FOLLOWER staing and doesn't move before followed player will disappear.

<a href="http://imgup.pl/pm/97DT/nowy-obraz-mapy-bitowej.html" title="Nowy obraz mapy bitowej" ><img src="http://imgup.pl/dm/97DT/nowy-obraz-mapy-bitowej.jpg" alt="Nowy obraz mapy bitowej" /></a>

**Comment by Fluppix** [comment]
void Game::processAttackCancel(uint seq)
{
  if(isAttacking() && (seq == 0 || m_seq == seq))
    cancelAttack();

  if(isFollowing())
    cancelFollow();
}
