### ISSUE TITLE
Smooth walking - solution.

### ISSUE THREAD

**Issue by Anastaciaa** [edubart/otclient#712]
The idea of smoother walking i took from Medivia.org this is a solution for every complains about walking system in the OTClient. Actually it's like Tibia client works. Mostly i adressing this post to contributor Iyront because he made it for his server. Would be great if he share or aleast explain how to fix this.

Here is the screen how it works.

<a  href="http://ifotos.pl/z/sehpppe/"><img src="http://s5.ifotos.pl/img/smoothwjp_sehpppe.jpg"></a>

"Game Client will schedule next walk before finishing previous step"

I know such post shouldn't be in issues but couldn't find better place.

**Comment by jollejkpg** [comment]
No image by that name was found!

**Comment by Anastaciaa** [comment]
Updated img

**Comment by Schneider3000** [comment]
Did you ever find a solution to this?
