### ISSUE TITLE
Compilation error on rpi2.

### ISSUE THREAD

**Issue by 0xNear** [edubart/otclient#714]
http://pastebin.com/VQgFX9Dx
Here is my compilation log. It's running under Raspbian on rpi2.

**Comment by diath** [comment]
The chances are you're running out of memory when building otclient, try increasing the swap size and see if that helps.

**Comment by 0xNear** [comment]
Compilation worked, thanks ;)

**Comment by 0xNear** [comment]
Compiling was done correctly, thanks.
