### ISSUE TITLE
Libraries link?

### ISSUE THREAD

**Issue by diath** [edubart/otclient#720]
@TheSumm @edubart @hrsantiago 
Can either of you confirm that @ChamapgnePapi is a legit person? It struck me as odd that a newly created account just replaced one of the download links on the Wiki.

**Comment by hrsantiago** [comment]
I doubt it's legit. I wasn't even aware that anyone can edit the Wiki.

**Comment by ChamapgnePapi** [comment]
It is legit I made this account just so I could update the link as I saw none had and I was searching like crazy the other day for a working link, you can check my post on otland if you'd like. I changed the link as the previous one was linked to a dropbox and it was disabled this is still the case for the MSVC libs.

https://otland.net/threads/ot-client-libs.240918/#post-2330062

**Comment by ChamapgnePapi** [comment]
@edubart Also on a side note the download link for both the MSVC lib and the MingW32 still direct to the dropbox links which have been disabled.
