### ISSUE TITLE
Talk with NPC (10.41)

### ISSUE THREAD

**Issue by poxis** [edubart/otclient#723]
Error with NPC. When I say hi, he stops and nothing more  (no open NPC Channel)
Server:  10.41
OTClient: lates src

> ERROR: ProtocolGame parse message exception (21 bytes unread, last opcode is 170, prev opcode is -1): InputMessage eof reached
> ERROR: ProtocolGame parse message exception (21 bytes unread, last opcode is 170, prev opcode is -1): InputMessage eof reached
> ERROR: ProtocolGame parse message exception (9 bytes unread, last opcode is 1, prev opcode is 178): unhandled opcode 1
> ERROR: ProtocolGame parse message exception (21 bytes unread, last opcode is 170, prev opcode is -1): InputMessage eof reached

**Comment by conde2** [comment]
@TheSumm please close this
#799 closes this
