### ISSUE TITLE
Visual Studio 2013

### ISSUE THREAD

**Issue by ghost** [edubart/otclient#724]
Hello im have thais error:
1>------ Rebuild All started: Project: otclient, Configuration: Release x64 ------
1>cl : Command line warning D9002: ignoring unknown option '/arch:SSE2'
1>cl : Command line warning D9002: ignoring unknown option '/arch:SSE2'
1>  animatedtext.cpp
1>cl : Command line warning D9002: ignoring unknown option '/arch:SSE2'

and this :8ball: 
Error   7   error C1083: Cannot open include file: 'al.h': No such file or directory (..\src\framework\core\graphicalapplication.cpp)   c:\otclient-master\src\framework\sound\declarations.h   30  1   otclient

**Comment by wgrriffel** [comment]
use codeblocks instead and follow wiki's tutorial

**Comment by Shawak** [comment]
Whats the reason you are trying to compile using vs 2013 and not vs 2015?

**Comment by ronpetit** [comment]
You need the libraries for MSVC 2013, but the link over the description is broken, try to search for it on OTLand or ask somebody over here. (@edubart, @TheSumm, @Mignari)

It will be good to have those libraries for MSVC 2015.
