### ISSUE TITLE
Unable to compile on Ubuntu 15 x64

### ISSUE THREAD

**Issue by Dublerq** [edubart/otclient#726]
I couldn't finish CMAKE because of lack of physfs in debian 15. I've installed latest libphysfs-dev, but still can't link the project to final the file. The result of make is:

`Linking CXX executable otclient
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libphysfs.a: error adding symbols: Archive has no index; run ranlib to add one
collect2: error: ld returned 1 exit status
CMakeFiles/otclient.dir/build.make:3702: recipe for target 'otclient' failed
make[2]: *** [otclient] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/otclient.dir/all' failed
make[1]: *** [CMakeFiles/otclient.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2`

I've found some tips that I should compile it with static libs being off, but result is the same. My guess is that Physfs is unavailable for x64 compiler. What can I do about that?

**Comment by edubart** [comment]
Compile and install physfs by hand, or try to run ranlib as suggested:
ranlib /usr/lib/gcc/x86_64-linux-gnu/libphysfs.a

**Comment by Dublerq** [comment]
ranlib results with: `ranlib: '/usr/lib/gcc/x86_64-linux-gnu/libphysfs.a': No such file`. I'll try to compile and install physfs later

**Comment by Dublerq** [comment]
Solution is to get latest physfs source, `cmake` it, `make`, and then  `sudo make install`. Then check where the libphysfs.a is installed.
This line of `sudo make install` will tell you that information:
`-- Installing: /usr/local/lib/libphysfs.a`
then just copy or make a link of this file to lib directory of your compiler, in my case it was:
`/usr/lib/gcc/x86_64-linux-gnu/`

Have a nice day guys, and somebody please update the ubuntu installation guide

**Comment by rowaraujo** [comment]
I have found libphysfs.a in `/usr/lib/x86_64-linux-gnu/libphysfs.a` instead `/usr/lib/gcc/x86_64-linux-gnu/libphysfs.a`

**Comment by pzaj2** [comment]
Does not work Ubuntu 16.04.
