### ISSUE TITLE
Skill by vocation and color box

### ISSUE THREAD

**Issue by blackz13** [edubart/otclient#727]
I have two issues..
1º- is possible set to show skill by vocation? Ex: to sorcerer appears only magic level, shielding and fishing

2º- is possible show only the color i want on color box (to color the outfits)? Something about 6-10 colors only?

**Comment by wgrriffel** [comment]
ok where's the issues? you showed up two questions, and both answers are yes, also you must know how client-server protocols works to do that, if haven't clue how to do ask on supports board, not in an issue tracker.
