### ISSUE TITLE
NPC Issue

### ISSUE THREAD

**Issue by omanacleto** [edubart/otclient#732]
I got this problem whenever i talk to a NPC the NPC channel doesn't open so i can't continue talking with him. I'm using the latest otclient source and TFS 0.4 on tibia 8.6. Cipsoft's client is working normally

I get these error messages:

```
ERROR: ProtocolGame parse message exception (47 bytes unread, last opcode is 170, prev opcode is 107): InputMessage eof reached
ERROR: ProtocolGame parse message exception (45 bytes unread, last opcode is 170, prev opcode is -1): InputMessage eof reached
```

First one being when i talk to then and second one being when i get out of their range.
Any help would be appreciated.

**Comment by VictorAmaral** [comment]
I too

**Comment by maxepowers** [comment]
Got the same problem!
Using otclient on kernel 4.6.2-1-ARCH
