### ISSUE TITLE
Where to place data after compilation for android?

### ISSUE THREAD

**Issue by KoukiShichirou** [edubart/otclient#734]
Hello ;)
I compiled OTClient for Android succesfully following the tutorial using Windows 10, but I got an 16kB .apk file without an data.
How to get an .apk with data, like Szybol7 did? Or where I should place everything on my android device?

**Comment by KoukiShichirou** [comment]
Problem solved.

**Comment by hrsantiago** [comment]
What's the solution? This might help someone in the future.

**Comment by KoukiShichirou** [comment]
Place data on /sdcard/OTClient/ and properly compile an the whole 
.apk (i had about 500kB after wrong compilation and 17,5mB after correct).  This was due to lib linking because of my mistake.
