### ISSUE TITLE
IntelliSense: cannot open source file "al.h"

### ISSUE THREAD

**Issue by EmersonHenriique** [edubart/otclient#737]
```
1   IntelliSense: cannot open source file "al.h"    c:\otclient-master\src\framework\sound\declarations.h   30  1   otclient
2   IntelliSense: cannot open source file "alc.h"   c:\otclient-master\src\framework\sound\declarations.h   31  1   otclient
```

VS 2013

**Comment by margohq** [comment]
1st, install boost through installer.
2nd, change from #include "al.h"and "alc.h" to "AL/al.h" and "AL/alc.h". It solved problem for me.

**Comment by EmersonHenriique** [comment]
Error	1	error LNK1181: cannot open input file 'libeay32MD.lib'	C:\otclient-master\vc12\LINK	otclient

**Comment by conde2** [comment]
@theSumm please close this issue
#806 close this
