### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by Szybol7** [edubart/otclient#741]
Is it possible to add multithreading by std :: thread or boost :: thread.
For graphics create new thread and use other cpu core.
This solution increase fps in game.

**Comment by HeavenIsLost** [comment]
@edubart as OTClient uses smart pointers everywhere, how hard it would be to make it use a exclusive  thread for rendering/drawing?

**Comment by hrsantiago** [comment]
A lot of work and really hard.

**Comment by HeavenIsLost** [comment]
@hrsantiago And i think it would not improve the performance because OTClient performance is more gpu bond than cpu bond? Instead of focusing on multithreading we should improve the drawing method...
