### ISSUE TITLE
problem compiling on ubuntu

### ISSUE THREAD

**Issue by blackz13** [edubart/otclient#742]
when i try it on ubuntu: sudo apt-get install libboost1.55-all-dev libphysfs-dev libssl-dev liblua5.1-dev
i got this message
Note, a seleccionar 'liblua5.1-0-dev' em vez de 'liblua5.1-dev'
E: Impossível encontrar o pacote libboost1.55-all-dev
E: Couldn't find any package by glob 'libboost1.55-all-dev'
E: Não foi possível encontrar o pacote através da expressão regular 'libboost1.55-all-dev'

**Comment by rodolfowtf** [comment]
`sudo apt-get install libboost-all-dev`

http://stackoverflow.com/questions/12578499/how-to-install-boost-on-ubuntu
