### ISSUE TITLE
NPC-Chat wont show up.

### ISSUE THREAD

**Issue by maxepowers** [edubart/otclient#743]
Hello all,

using newest release of otclient on 4.6.2-1-ARCH, self compiled, i noticed that i cant talk with any npc in game. Its seems like they still react to the "hello" or "hi" because they turn in my direction.
but the npc chat wont open and no trade windows or further interaction is possible, like depositing all my gold.

The following error appears in the otclient logs:
`ERROR: ProtocolGame parse message exception (132 bytes unread, last opcode is 170, prev opcode is 170): InputMessage eof reached
ERROR: ProtocolGame parse message exception (14 bytes unread, last opcode is 170, prev opcode is 109): InputMessage eof reached
ERROR: ProtocolGame parse message exception (207 bytes unread, last opcode is 170, prev opcode is 170): InputMessage eof reached
`

The value befor "bytes" varies as you can see, but "last opcode" ist always 170, also "prev opcode".

I hope someone knows a solution for this because using otclient seems like the only real way to play on ot-tibia servers on linux. and not being able to talk to npc's sucks.

Iam playing on a server with the game version 8.6, but also on higher versions this bug appears.

greetings

**Comment by TheSumm** [comment]
https://github.com/edubart/otclient/commit/408b3c5125b67a1a6e75148a47ca51492c694364#commitcomment-15595678

**Comment by maxepowers** [comment]
Thanks for the reply!
Made the change in otclient/src/client/protocolcodes.cpp
any need to recompile that?
for now, the change hasnt fixed the bug.
still no way to talk to npc's.

**Comment by margohq** [comment]
You need to recompile :d Normal if you do changes to files inside src folder

**Comment by maxepowers** [comment]
Sorry for the delay of my reply.
Should have tought about it before i ask if i have to recompile it :)

It worked by the way. I can now talk with the npcs.
Thanks for the help guys and great work here!

**Comment by maxepowers** [comment]
Iam sorry for reposting here, but it seems that in the latest Update the solution
posted by TheSumm doenst work anymore.
Again, i cant talk to any NPC's.
How do i have to change the protocolcodes.cpp file so it works again in the newest Version?
I tired serveral combinations but none worked.

**Comment by fbolanos** [comment]
I figured out how to fix this:
Open up modules/gamelib/const.lua
And change NPCFromStartBlock to 51, and I guess Last to 52.
It works on 8.6 and 10.77. Also worth noting I did't use the above proposed fix, I also have latest committed code.
It's a bit strange that this code is the only one that jumps more than 1 unit... I wonder if it's a server bug or something.

**Comment by A-Syntax** [comment]
Thanks @fbolanos that worked with the new 10.98/99 client.
