### ISSUE TITLE
Support for OpenGL version 3/OpenGL ES 3

### ISSUE THREAD

**Issue by HeavenIsLost** [edubart/otclient#747]
I think the most expensive operation that is reducing OTClient fps is the absurd amount of texture binds. With texture arrays(which as been added in OpenGL 3) we can use one texture for all the graphic objects instead of using one texture per graphic object like we are doing now. 
Another solution is to build texture atlas for smaller scenario sprites that are being used in the screen, it would also reduce texture binds.

About ANGLE and OpenGL ES 3: https://github.com/google/angle check readme

**Comment by iryont** [comment]
This proposal makes no sense whatsoever. If a specific GPU supports core functions of OpenGL 3.0 it can definitely run the game client just fine.
