### ISSUE TITLE
Create a mana bar beneath players health bar

### ISSUE THREAD

**Issue by BenDol** [edubart/otclient#75]
Should provide the option to display a mana bar beneath the players health bar.

**Comment by Felipe1993** [comment]
any tutorial regarding how to use this feature?

**Comment by Felipe1993** [comment]
i had edited the source for a mana baar now i need the script to display it
any idea?

**Comment by TheSumm** [comment]
Implemented in #909.

Showing the current mana of all players is not possible at this point due to game server limitations. As I have not seen the feature on any server, I would also argue that it is not common enough to warrant adding it to the client at this point.
