### ISSUE TITLE
Higher FPS fixes

### ISSUE THREAD

**Issue by Schneider3000** [edubart/otclient#751]
I am going through the latest commits dating back to 2014 right now since Im using an older version of OT Client. What I started wondering is, have there been any major or even small time fixes that have affected the performance / FPS of OTClient? I couldnt see any that mentioned FPS/Performance specifically but I assume any of them could have made improvements to OTC. Is anyone aware of anything that has been done lately that could boost the performance? I was never able to tweak it to work further due to lack of skills. Im currently on a version from early 2014.

**Comment by daniofordon** [comment]
on otland it is already on, and soon unless something moves in optimizing :)

https://otland.net/threads/otclient-graphics-discussion-anyone-out-there-more-knowledgeable-than-me.244015/page-6#post-2401740
