### ISSUE TITLE
Compiling with Microsoft Visual 2015

### ISSUE THREAD

**Issue by bangbus** [edubart/otclient#754]
Has anyone successfully compiled with Microsoft Visual Studio Enterprise 2015?

Ttying to compile gives me `cannot open file libboost_thread-vc140-mt-1_61.lib'`. Any ideas?

Have latest boost, the sdks and also followed the guide in the wiki

**Comment by Codex-NG** [comment]
Use boost 1.60 with VS 2015, although the original post is old for anyone that runs into this problem check out this link below.

https://otland.net/threads/problems-while-compiling-otclient.246597/

**Comment by conde2** [comment]
@assamy please close this issue 
#806 fixes this
