### ISSUE TITLE
Monster remove ladder

### ISSUE THREAD

**Issue by diegorodriguesvieira** [edubart/otclient#756]
**I'm use this source:**
https://github.com/TwistedScorpio/OTHire

**This is the bug:**
https://media.giphy.com/media/l0HlNp0Tuu4ecj7mE/giphy.gif

Can anyone help me find this bug? :/

I found a solution, please close it! =)
https://github.com/TwistedScorpio/OTHire/issues/72#issuecomment-244267970

**Comment by Riverlance** [comment]
https://github.com/edubart/otclient/issues/790
