### ISSUE TITLE
MinGW libraries broken??

### ISSUE THREAD

**Issue by nullptr128** [edubart/otclient#759]
Hello.

I have trouble with compiling OTClient (recent version) with Code::Blocks+MinGW on Windows.
I've followed steps carefully and did it like 4 times but still I have same issue. I've also tried with VS2015 and I've got very similar message as well.

I've had error with compiler complaining that "wcscat has not been declared" and a list of very similar names. I've found out on google that it is because CMake creates a build that calls g++ with -std=c++11 while it should call with -std=gnu++11. I've managed to alter CMakeLists.txt and compillation passed by.

But now this happen when I am trying to compile project (at linking phase), linking fails at libboost_system.
http://pastebin.com/CKVz7Wjs

I am fighting this 2nd day in a row and I have no idea how to proceed.
Libraries I've copied over my MinGW installation are from this link (from wiki):
https://mega.nz/#!1Zg0jK6Q!gA5jHmL4qU92XnDdy98UfS2y1KFQQvbjS_L5p5UHDYk

I cant proceed any further.

**Comment by Codex-NG** [comment]
If you use a new compiler on the same project, always delete the object files (files with the extension **o** are object files) and then recompile the project.

**Comment by Felipe1993** [comment]
where i delete those object files @Codex-NG pls help im having issue with the new migw libraries
