### ISSUE TITLE
OTClient wont compile on LUbuntu 16.04

### ISSUE THREAD

**Issue by zexusemail** [edubart/otclient#762]
I've install all what was necessary to compile my OTClient
[code]
sudo apt-get install build-essential cmake git-core
sudo apt-get install libboost-all-dev libphysfs-dev libssl-dev liblua5.1-dev
sudo apt-get install libglew1.6-dev libvorbis-dev libopenal-dev libz-dev
[/code](libboost1.55-all-dev can't be found/installed, i installed libboost-all-dev...)

I got the same error then this topic creator: https://otland.net/threads/otclient-wont-compile-on-ubuntu-16-04.242662/#post-2394962
And in helps me to fix...
Then:

physfs
(I've putted all steps, because i got a lot problems, and if somebody got the same can solved follow this):

[code]sudo apt-get install libc6-dev-i386[/code]
[code]sudo apt-get install doxygen[/code]
[code]sudo apt-get install libncurses5-dev[/code]
[code]sudo apt-get install libncurses5-dev[/code]
[code]apt install mercurial[/code]
[code]
hg clone -r stable-2.0 http://hg.icculus.org/icculus/physfs/
cd physfs
sudo mkdir build
cd build
sudo cmake ..
sudo make
sudo make install
sudo mv /usr/local/lib/libphysfs.a /usr/lib/gcc/x86_64-linux-gnu/
[/code]

otclient:

cmake ..
[code]
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_KNOWS_CXX11
-- Performing Test COMPILER_KNOWS_CXX11 - Success
-- Performing Test COMPILER_KNOWS_STDLIB
-- Performing Test COMPILER_KNOWS_STDLIB - Failed
-- Link to static libraries: ON
-- Build type: RelWithDebInfo
-- Build commit: devel
-- Build revision: 0
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   thread
--   filesystem
--   chrono
--   date_time
--   atomic
-- Found Lua: /usr/lib/x86_64-linux-gnu/liblua5.1.a
-- LuaJIT: OFF
-- Found PHYSFS: /usr/lib/x86_64-linux-gnu/libphysfs.a
-- Found OPENSSL: /usr/lib/x86_64-linux-gnu/libssl.a;/usr/lib/x86_64-linux-gnu/libcrypto.a
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.a
-- Debug information: ON
-- Crash handler: ON
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so
-- Found GLEW: /usr/lib/x86_64-linux-gnu/libGLEW.so
-- OpenGL ES: OFF
-- Found OPENAL: /usr/lib/x86_64-linux-gnu/libopenal.so
-- Found VORBISFILE: /usr/lib/x86_64-linux-gnu/libvorbisfile.a
-- Found VORBIS: /usr/lib/x86_64-linux-gnu/libvorbis.a
-- Found OGG: /usr/lib/x86_64-linux-gnu/libogg.a
-- Bot protection: ON
-- Use precompiled header: OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /home/carlos/otclient/build
[/code]

make
[code]
Scanning dependencies of target otclient
[  0%] Building CXX object CMakeFiles/otclient.dir/src/framework/luafunctions.cpp.o
[  1%] Building CXX object CMakeFiles/otclient.dir/src/framework/util/color.cpp.o
[  2%] Building CXX object CMakeFiles/otclient.dir/src/framework/util/crypt.cpp.o
[  2%] Building CXX object CMakeFiles/otclient.dir/src/framework/stdext/demangle.cpp.o
[  3%] Building CXX object CMakeFiles/otclient.dir/src/framework/stdext/math.cpp.o
[  4%] Building CXX object CMakeFiles/otclient.dir/src/framework/stdext/net.cpp.o
[  4%] Building CXX object CMakeFiles/otclient.dir/src/framework/stdext/string.cpp.o
[  5%] Building CXX object CMakeFiles/otclient.dir/src/framework/stdext/time.cpp.o
[  6%] Building CXX object CMakeFiles/otclient.dir/src/framework/core/application.cpp.o
[  6%] Building CXX object CMakeFiles/otclient.dir/src/framework/core/adaptativeframecounter.cpp.o
[  7%] Building CXX object CMakeFiles/otclient.dir/src/framework/core/asyncdispatcher.cpp.o
[  8%] Building CXX object CMakeFiles/otclient.dir/src/framework/core/binarytree.cpp.o
[  8%] Building CXX object CMakeFiles/otclient.dir/src/framework/core/clock.cpp.o
[  9%] Building CXX object CMakeFiles/otclient.dir/src/framework/core/config.cpp.o
[ 10%] Building CXX object CMakeFiles/otclient.dir/src/framework/core/configmanager.cpp.o
[ 10%] Building CXX object CMakeFiles/otclient.dir/src/framework/core/event.cpp.o
[ 11%] Building CXX object CMakeFiles/otclient.dir/src/framework/core/eventdispatcher.cpp.o
[ 12%] Building CXX object CMakeFiles/otclient.dir/src/framework/core/filestream.cpp.o
[ 13%] Building CXX object CMakeFiles/otclient.dir/src/framework/core/logger.cpp.o
[ 13%] Building CXX object CMakeFiles/otclient.dir/src/framework/core/module.cpp.o
[ 14%] Building CXX object CMakeFiles/otclient.dir/src/framework/core/modulemanager.cpp.o
[ 15%] Building CXX object CMakeFiles/otclient.dir/src/framework/core/resourcemanager.cpp.o
[ 15%] Building CXX object CMakeFiles/otclient.dir/src/framework/core/scheduledevent.cpp.o
[ 16%] Building CXX object CMakeFiles/otclient.dir/src/framework/core/timer.cpp.o
[ 17%] Building CXX object CMakeFiles/otclient.dir/src/framework/luaengine/luaexception.cpp.o
[ 17%] Building CXX object CMakeFiles/otclient.dir/src/framework/luaengine/luainterface.cpp.o
[ 18%] Building CXX object CMakeFiles/otclient.dir/src/framework/luaengine/luaobject.cpp.o
[ 19%] Building CXX object CMakeFiles/otclient.dir/src/framework/luaengine/luavaluecasts.cpp.o
[ 19%] Building CXX object CMakeFiles/otclient.dir/src/framework/luaengine/lbitlib.cpp.o
[ 20%] Building CXX object CMakeFiles/otclient.dir/src/framework/otml/otmldocument.cpp.o
[ 21%] Building CXX object CMakeFiles/otclient.dir/src/framework/otml/otmlemitter.cpp.o
[ 21%] Building CXX object CMakeFiles/otclient.dir/src/framework/otml/otmlexception.cpp.o
[ 22%] Building CXX object CMakeFiles/otclient.dir/src/framework/otml/otmlnode.cpp.o
[ 23%] Building CXX object CMakeFiles/otclient.dir/src/framework/otml/otmlparser.cpp.o
[ 23%] Building CXX object CMakeFiles/otclient.dir/src/framework/platform/unixcrashhandler.cpp.o
[ 24%] Building CXX object CMakeFiles/otclient.dir/src/framework/platform/win32crashhandler.cpp.o
[ 25%] Building CXX object CMakeFiles/otclient.dir/src/framework/platform/win32platform.cpp.o
[ 26%] Building CXX object CMakeFiles/otclient.dir/src/framework/platform/unixplatform.cpp.o
[ 26%] Building CXX object CMakeFiles/otclient.dir/src/framework/platform/platform.cpp.o
[ 27%] Building CXX object CMakeFiles/otclient.dir/src/framework/graphics/animatedtexture.cpp.o
[ 28%] Building CXX object CMakeFiles/otclient.dir/src/framework/graphics/cachedtext.cpp.o
[ 28%] Building CXX object CMakeFiles/otclient.dir/src/framework/graphics/coordsbuffer.cpp.o
[ 29%] Building CXX object CMakeFiles/otclient.dir/src/framework/graphics/bitmapfont.cpp.o
[ 30%] Building CXX object CMakeFiles/otclient.dir/src/framework/graphics/fontmanager.cpp.o
[ 30%] Building CXX object CMakeFiles/otclient.dir/src/framework/graphics/framebuffer.cpp.o
[ 31%] Building CXX object CMakeFiles/otclient.dir/src/framework/graphics/framebuffermanager.cpp.o
[ 32%] Building CXX object CMakeFiles/otclient.dir/src/framework/graphics/graphics.cpp.o
[ 32%] Building CXX object CMakeFiles/otclient.dir/src/framework/graphics/hardwarebuffer.cpp.o
[ 33%] Building CXX object CMakeFiles/otclient.dir/src/framework/graphics/image.cpp.o
[ 34%] Building CXX object CMakeFiles/otclient.dir/src/framework/graphics/painter.cpp.o
[ 34%] Building CXX object CMakeFiles/otclient.dir/src/framework/graphics/ogl/painterogl.cpp.o
[ 35%] Building CXX object CMakeFiles/otclient.dir/src/framework/graphics/ogl/painterogl1.cpp.o
[ 36%] Building CXX object CMakeFiles/otclient.dir/src/framework/graphics/ogl/painterogl2.cpp.o
[ 36%] Building CXX object CMakeFiles/otclient.dir/src/framework/graphics/paintershaderprogram.cpp.o
[ 37%] Building CXX object CMakeFiles/otclient.dir/src/framework/graphics/particleaffector.cpp.o
[ 38%] Building CXX object CMakeFiles/otclient.dir/src/framework/graphics/particle.cpp.o
[ 39%] Building CXX object CMakeFiles/otclient.dir/src/framework/graphics/particletype.cpp.o
[ 39%] Building CXX object CMakeFiles/otclient.dir/src/framework/graphics/particleemitter.cpp.o
[ 40%] Building CXX object CMakeFiles/otclient.dir/src/framework/graphics/particleeffect.cpp.o
[ 41%] Building CXX object CMakeFiles/otclient.dir/src/framework/graphics/particlemanager.cpp.o
[ 41%] Building CXX object CMakeFiles/otclient.dir/src/framework/graphics/particlesystem.cpp.o
[ 42%] Building CXX object CMakeFiles/otclient.dir/src/framework/graphics/shader.cpp.o
[ 43%] Building CXX object CMakeFiles/otclient.dir/src/framework/graphics/shaderprogram.cpp.o
[ 43%] Building CXX object CMakeFiles/otclient.dir/src/framework/graphics/texture.cpp.o
[ 44%] Building CXX object CMakeFiles/otclient.dir/src/framework/graphics/texturemanager.cpp.o
[ 45%] Building CXX object CMakeFiles/otclient.dir/src/framework/graphics/apngloader.cpp.o
[ 45%] Building CXX object CMakeFiles/otclient.dir/src/framework/ui/uianchorlayout.cpp.o
[ 46%] Building CXX object CMakeFiles/otclient.dir/src/framework/ui/uiboxlayout.cpp.o
[ 47%] Building CXX object CMakeFiles/otclient.dir/src/framework/ui/uigridlayout.cpp.o
[ 47%] Building CXX object CMakeFiles/otclient.dir/src/framework/ui/uihorizontallayout.cpp.o
[ 48%] Building CXX object CMakeFiles/otclient.dir/src/framework/ui/uilayout.cpp.o
[ 49%] Building CXX object CMakeFiles/otclient.dir/src/framework/ui/uimanager.cpp.o
[ 50%] Building CXX object CMakeFiles/otclient.dir/src/framework/ui/uiparticles.cpp.o
[ 50%] Building CXX object CMakeFiles/otclient.dir/src/framework/ui/uitextedit.cpp.o
[ 51%] Building CXX object CMakeFiles/otclient.dir/src/framework/ui/uitranslator.cpp.o
[ 52%] Building CXX object CMakeFiles/otclient.dir/src/framework/ui/uiverticallayout.cpp.o
[ 52%] Building CXX object CMakeFiles/otclient.dir/src/framework/ui/uiwidgetbasestyle.cpp.o
[ 53%] Building CXX object CMakeFiles/otclient.dir/src/framework/ui/uiwidget.cpp.o
[ 54%] Building CXX object CMakeFiles/otclient.dir/src/framework/ui/uiwidgetimage.cpp.o
[ 54%] Building CXX object CMakeFiles/otclient.dir/src/framework/ui/uiwidgettext.cpp.o
[ 55%] Building CXX object CMakeFiles/otclient.dir/src/framework/platform/platformwindow.cpp.o
[ 56%] Building CXX object CMakeFiles/otclient.dir/src/framework/platform/win32window.cpp.o
[ 56%] Building CXX object CMakeFiles/otclient.dir/src/framework/platform/x11window.cpp.o
[ 57%] Building CXX object CMakeFiles/otclient.dir/src/framework/input/mouse.cpp.o
[ 58%] Building CXX object CMakeFiles/otclient.dir/src/framework/core/graphicalapplication.cpp.o
[ 58%] Building CXX object CMakeFiles/otclient.dir/src/framework/sound/combinedsoundsource.cpp.o
[ 59%] Building CXX object CMakeFiles/otclient.dir/src/framework/sound/oggsoundfile.cpp.o
[ 60%] Building CXX object CMakeFiles/otclient.dir/src/framework/sound/soundbuffer.cpp.o
[ 60%] Building CXX object CMakeFiles/otclient.dir/src/framework/sound/soundchannel.cpp.o
[ 61%] Building CXX object CMakeFiles/otclient.dir/src/framework/sound/soundfile.cpp.o
[ 62%] Building CXX object CMakeFiles/otclient.dir/src/framework/sound/soundmanager.cpp.o
[ 63%] Building CXX object CMakeFiles/otclient.dir/src/framework/sound/soundsource.cpp.o
[ 63%] Building CXX object CMakeFiles/otclient.dir/src/framework/sound/streamsoundsource.cpp.o
[ 64%] Building CXX object CMakeFiles/otclient.dir/src/framework/net/connection.cpp.o
[ 65%] Building CXX object CMakeFiles/otclient.dir/src/framework/net/inputmessage.cpp.o
[ 65%] Building CXX object CMakeFiles/otclient.dir/src/framework/net/outputmessage.cpp.o
[ 66%] Building CXX object CMakeFiles/otclient.dir/src/framework/net/protocol.cpp.o
[ 67%] Building CXX object CMakeFiles/otclient.dir/src/framework/net/protocolhttp.cpp.o
[ 67%] Building CXX object CMakeFiles/otclient.dir/src/framework/net/server.cpp.o
[ 68%] Building CXX object CMakeFiles/otclient.dir/src/framework/xml/tinyxml.cpp.o
[ 69%] Building CXX object CMakeFiles/otclient.dir/src/framework/xml/tinystr.cpp.o
[ 69%] Building CXX object CMakeFiles/otclient.dir/src/framework/xml/tinyxmlerror.cpp.o
[ 70%] Building CXX object CMakeFiles/otclient.dir/src/framework/xml/tinyxmlparser.cpp.o
[ 71%] Building CXX object CMakeFiles/otclient.dir/src/client/luafunctions.cpp.o
[ 71%] Building CXX object CMakeFiles/otclient.dir/src/client/client.cpp.o
[ 72%] Building CXX object CMakeFiles/otclient.dir/src/client/animatedtext.cpp.o
[ 73%] Building CXX object CMakeFiles/otclient.dir/src/client/animator.cpp.o
[ 73%] Building CXX object CMakeFiles/otclient.dir/src/client/container.cpp.o
[ 74%] Building CXX object CMakeFiles/otclient.dir/src/client/creature.cpp.o
[ 75%] Building CXX object CMakeFiles/otclient.dir/src/client/effect.cpp.o
[ 76%] Building CXX object CMakeFiles/otclient.dir/src/client/game.cpp.o
[ 76%] Building CXX object CMakeFiles/otclient.dir/src/client/shadermanager.cpp.o
[ 77%] Building CXX object CMakeFiles/otclient.dir/src/client/item.cpp.o
[ 78%] Building CXX object CMakeFiles/otclient.dir/src/client/localplayer.cpp.o
[ 78%] Building CXX object CMakeFiles/otclient.dir/src/client/map.cpp.o
[ 79%] Building CXX object CMakeFiles/otclient.dir/src/client/mapio.cpp.o
[ 80%] Building CXX object CMakeFiles/otclient.dir/src/client/mapview.cpp.o
[ 80%] Building CXX object CMakeFiles/otclient.dir/src/client/minimap.cpp.o
[ 81%] Building CXX object CMakeFiles/otclient.dir/src/client/lightview.cpp.o
[ 82%] Building CXX object CMakeFiles/otclient.dir/src/client/missile.cpp.o
[ 82%] Building CXX object CMakeFiles/otclient.dir/src/client/outfit.cpp.o
[ 83%] Building CXX object CMakeFiles/otclient.dir/src/client/player.cpp.o
[ 84%] Building CXX object CMakeFiles/otclient.dir/src/client/spritemanager.cpp.o
[ 84%] Building CXX object CMakeFiles/otclient.dir/src/client/statictext.cpp.o
[ 85%] Building CXX object CMakeFiles/otclient.dir/src/client/thing.cpp.o
[ 86%] Building CXX object CMakeFiles/otclient.dir/src/client/thingtypemanager.cpp.o
[ 86%] Building CXX object CMakeFiles/otclient.dir/src/client/thingtype.cpp.o
/home/carlos/otclient/src/client/thingtype.cpp: In member function ‘void ThingType::unserialize(uint16, ThingCategory, const FileStreamPtr&)’:
/home/carlos/otclient/src/client/thingtype.cpp:275:15: warning: variable ‘frameGroupType’ set but not used [-Wunused-but-set-variable]
         uint8 frameGroupType = FrameGroupDefault;
               ^
[ 87%] Building CXX object CMakeFiles/otclient.dir/src/client/itemtype.cpp.o
[ 88%] Building CXX object CMakeFiles/otclient.dir/src/client/tile.cpp.o
[ 89%] Building CXX object CMakeFiles/otclient.dir/src/client/houses.cpp.o
[ 89%] Building CXX object CMakeFiles/otclient.dir/src/client/towns.cpp.o
[ 90%] Building CXX object CMakeFiles/otclient.dir/src/client/creatures.cpp.o
[ 91%] Building CXX object CMakeFiles/otclient.dir/src/client/luavaluecasts.cpp.o
[ 91%] Building CXX object CMakeFiles/otclient.dir/src/client/protocolcodes.cpp.o
[ 92%] Building CXX object CMakeFiles/otclient.dir/src/client/protocolgame.cpp.o
[ 93%] Building CXX object CMakeFiles/otclient.dir/src/client/protocolgameparse.cpp.o
/home/carlos/otclient/src/client/protocolgameparse.cpp: In member function ‘void ProtocolGame::parseStore(const InputMessagePtr&)’:
/home/carlos/otclient/src/client/protocolgameparse.cpp:484:13: warning: variable ‘highlightState’ set but not used [-Wunused-but-set-variable]
         int highlightState = 0;
             ^
/home/carlos/otclient/src/client/protocolgameparse.cpp: In member function ‘void ProtocolGame::parseCoinBalance(const InputMessagePtr&)’:
/home/carlos/otclient/src/client/protocolgameparse.cpp:504:9: warning: variable ‘coins’ set but not used [-Wunused-but-set-variable]
     int coins = -1;
         ^
/home/carlos/otclient/src/client/protocolgameparse.cpp:505:9: warning: variable ‘transferableCoins’ set but not used [-Wunused-but-set-variable]
     int transferableCoins = -1;
         ^
[ 93%] Building CXX object CMakeFiles/otclient.dir/src/client/protocolgamesend.cpp.o
[ 94%] Building CXX object CMakeFiles/otclient.dir/src/client/uicreature.cpp.o
[ 95%] Building CXX object CMakeFiles/otclient.dir/src/client/uiitem.cpp.o
[ 95%] Building CXX object CMakeFiles/otclient.dir/src/client/uimap.cpp.o
[ 96%] Building CXX object CMakeFiles/otclient.dir/src/client/uiminimap.cpp.o
[ 97%] Building CXX object CMakeFiles/otclient.dir/src/client/uiprogressrect.cpp.o
[ 97%] Building CXX object CMakeFiles/otclient.dir/src/client/uimapanchorlayout.cpp.o
[ 98%] Building CXX object CMakeFiles/otclient.dir/src/client/uisprite.cpp.o
[ 99%] Building CXX object CMakeFiles/otclient.dir/src/main.cpp.o
[100%] Linking CXX executable otclient
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libphysfs.a: error adding symbols: Archive has no index; run ranlib to add one
collect2: error: ld returned 1 exit status
CMakeFiles/otclient.dir/build.make:3857: recipe for target 'otclient' failed
make[2]: **\* [otclient] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/otclient.dir/all' failed
make[1]: **\* [CMakeFiles/otclient.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2
root@carlos-PC:/home/carlos/otclient/build#
[/code]

Error make:
[code]
[ 99%] Building CXX object CMakeFiles/otclient.dir/src/main.cpp.o
[100%] Linking CXX executable otclient
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libphysfs.a: error adding symbols: Archive has no index; run ranlib to add one
collect2: error: ld returned 1 exit status
CMakeFiles/otclient.dir/build.make:3857: recipe for target 'otclient' failed
make[2]: **\* [otclient] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/otclient.dir/all' failed
make[1]: **\* [CMakeFiles/otclient.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: **\* [all] Error 2
root@carlos-PC:/home/carlos/otclient/build#
[/code]

What I supossed to do now? :(

**Comment by zexusemail** [comment]
I've tried to
ranlib /usr/lib/gcc/x86_64-linux-gnu/libphysfs.a

But:
[code]
root@carlos-PC:/home/carlos/otclient/build# ranlib /usr/lib/gcc/x86_64-linux-gnu/libphysfs.a
root@carlos-PC:/home/carlos/otclient/build# cmake ..
-- Link to static libraries: ON
-- Build type: RelWithDebInfo
-- Build commit: devel
-- Build revision: 0
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   thread
--   filesystem
--   chrono
--   date_time
--   atomic
-- LuaJIT: OFF
-- Debug information: ON
-- Crash handler: ON
-- OpenGL ES: OFF
-- Bot protection: ON
-- Use precompiled header: OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /home/carlos/otclient/build
root@carlos-PC:/home/carlos/otclient/build# make
[  1%] Linking CXX executable otclient
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libphysfs.a: error adding symbols: Archive has no index; run ranlib to add one
collect2: error: ld returned 1 exit status
CMakeFiles/otclient.dir/build.make:3857: recipe for target 'otclient' failed
make[2]: *** [otclient] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/otclient.dir/all' failed
make[1]: *** [CMakeFiles/otclient.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
root@carlos-PC:/home/carlos/otclient/build#
[/code]



RME wont compile too, its because anything i did here?
https://otland.net/threads/rme-wont-compile-on-lubuntu-16-04.246346/

**Comment by robertov82008** [comment]
Hi, Look this.
https://gist.github.com/robertov82008/3af0461b31b14887506af84f3a00c1ac

**Comment by XtrmJosh** [comment]
`sudo apt-get install libncurses5-dev
sudo apt-get install mercurial

# PhysicsFS is a library to provide abstract access to various archives
hg clone -r stable-2.0 http://hg.icculus.org/icculus/physfs/
cd physfs
sudo mkdir build
cd build
sudo cmake ..
sudo make
sudo make install
sudo mv /usr/local/lib/libphysfs.a /usr/lib/x86_64-linux-gnu/.`

This fixed it for me from @robertov82008 snippet. Basically physfs library isn't installed properly by apt, so you have to manually install the libs. Should be added to the build docs really.
