### ISSUE TITLE
OTClient for 7.4 till 7.7x

### ISSUE THREAD

**Issue by dev1lwalks** [edubart/otclient#767]
Where can I modify the cap interface part since it is showing wrong values
Cap / 100 actually.

**Comment by diegorodriguesvieira** [comment]
Remove / 100 and recompile...

https://github.com/edubart/otclient/blob/master/src/client/protocolgameparse.cpp#L1303-L1311

**Comment by dev1lwalks** [comment]
thank you very much good sir! I had to change it for getu16 too :)

**Comment by hrsantiago** [comment]
You should make a pull request adding this as a GameFeature, activated on versions 7.4 to 7.7x. Other users would appreciate that.
