### ISSUE TITLE
error when death

### ISSUE THREAD

**Issue by daniofordon** [edubart/otclient#769]
hello I have a problem when the monster will kill me my body lying on the ground is not alive, but nothing pops up just chatting writes that killed

http://snap.ashampoo.com/uploads/2016-10-28/zZ5wgBmn.png

after I press the button, for example, up to the character stands up and stutters and now the only way to log out and log in again

http://snap.ashampoo.com/uploads/2016-10-28/NbKYVtKR.png

**Comment by Codex-NG** [comment]
The scripts you are using on the server + the distribution version have a lot to do with the behavior of the client. A bit more information would be needed to determine how this problem evolved and then a possible solution could be found.

If you don't provide any other information than your problem will persist.

**Comment by daniofordon** [comment]
already I solved the problem of data change pack to another :)
