### ISSUE TITLE
Compile Sucess and Bug

### ISSUE THREAD

**Issue by EmersonHenriique** [edubart/otclient#772]
1>  Finished generating code
1>libvorbis_static.lib(info.obj) : warning LNK4204: 'C:\OTClientE\vc12\Release\vc120.pdb' is missing debugging information for referencing module; linking object as if no debug info
1>libvorbis_static.lib(block.obj) : warning LNK4204: 'C:\OTClientE\vc12\Release\vc120.pdb' is missing debugging information for referencing module; linking object as if no debug info
1>libvorbis_static.lib(synthesis.obj) : warning LNK4204: 'C:\OTClientE\vc12\Release\vc120.pdb' is missing debugging information for referencing module; linking object as if no debug info
1>libvorbis_static.lib(registry.obj) : warning LNK4204: 'C:\OTClientE\vc12\Release\vc120.pdb' is missing debugging information for referencing module; linking object as if no debug info
1>libvorbis_static.lib(sharedbook.obj) : warning LNK4204: 'C:\OTClientE\vc12\Release\vc120.pdb' is missing debugging information for referencing module; linking object as if no debug info
1>libvorbis_static.lib(codebook.obj) : warning LNK4204: 'C:\OTClientE\vc12\Release\vc120.pdb' is missing debugging information for referencing module; linking object as if no debug info
1>libvorbis_static.lib(psy.obj) : warning LNK4204: 'C:\OTClientE\vc12\Release\vc120.pdb' is missing debugging information for referencing module; linking object as if no debug info
1>libvorbis_static.lib(smallft.obj) : warning LNK4204: 'C:\OTClientE\vc12\Release\vc120.pdb' is missing debugging information for referencing module; linking object as if no debug info
1>libvorbis_static.lib(envelope.obj) : warning LNK4204: 'C:\OTClientE\vc12\Release\vc120.pdb' is missing debugging information for referencing module; linking object as if no debug info
1>libvorbis_static.lib(mdct.obj) : warning LNK4204: 'C:\OTClientE\vc12\Release\vc120.pdb' is missing debugging information for referencing module; linking object as if no debug info
1>libvorbis_static.lib(bitrate.obj) : warning LNK4204: 'C:\OTClientE\vc12\Release\vc120.pdb' is missing debugging information for referencing module; linking object as if no debug info
1>libvorbis_static.lib(lpc.obj) : warning LNK4204: 'C:\OTClientE\vc12\Release\vc120.pdb' is missing debugging information for referencing module; linking object as if no debug info
1>libvorbis_static.lib(window.obj) : warning LNK4204: 'C:\OTClientE\vc12\Release\vc120.pdb' is missing debugging information for referencing module; linking object as if no debug info
1>libvorbis_static.lib(res0.obj) : warning LNK4204: 'C:\OTClientE\vc12\Release\vc120.pdb' is missing debugging information for referencing module; linking object as if no debug info
1>libvorbis_static.lib(mapping0.obj) : warning LNK4204: 'C:\OTClientE\vc12\Release\vc120.pdb' is missing debugging information for referencing module; linking object as if no debug info
1>libvorbis_static.lib(floor1.obj) : warning LNK4204: 'C:\OTClientE\vc12\Release\vc120.pdb' is missing debugging information for referencing module; linking object as if no debug info
1>libvorbis_static.lib(floor0.obj) : warning LNK4204: 'C:\OTClientE\vc12\Release\vc120.pdb' is missing debugging information for referencing module; linking object as if no debug info
1>libvorbis_static.lib(lsp.obj) : warning LNK4204: 'C:\OTClientE\vc12\Release\vc120.pdb' is missing debugging information for referencing module; linking object as if no debug info
1>libvorbisfile_static.lib(vorbisfile.obj) : warning LNK4204: 'C:\OTClientE\vc12\Release\vc120.pdb' is missing debugging information for referencing module; linking object as if no debug info
1>  otclient.vcxproj -> C:\OTClientE\vc12\Release\otclient.exe
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

**Comment by tgobira** [comment]
@EmersonHenriique, i've had the same problem, when u try to open otclient.exe you should receive DLL glew32.dll missing error. I've configured the GLEW to load glew32.lib as STATIC and now it loads as I compile the solution with GLEW_STATIC (on preprocessors) the solution shows another problem.

**LNK2001: unresolved external symbol**
