### ISSUE TITLE
Client crashes on startup

### ISSUE THREAD

**Issue by Miens** [edubart/otclient#774]
Hi. After a long fight with visual studio i finally managed to build OTClient. But now right after I start the program it crashes automatically :< Can some one help me with this? Ps: I downloaded latest build and threw .exe file in the same folder im building to and it worked fine.

== application crashed
app name: OTClient
app version: 0.6.3
build compiler: msvc12
build date: Nov 12 2016
build type: RelWithDebInfo
build revision: 0 (devel)
crash date: Nov 12 2016 21:01:58
exception: Access violation (0xc0000005)
exception address: 0x62e84353
  backtrace:
    0: C:\otclient-master\vc12\Release\zlib1.dll(deflateTune+0x13) [0x0000000062E84353]
    1: C:\otclient-master\vc12\Release\otclient.exe(load_apng+0xd63) [0x00000000012A49D3]
    2: C:\otclient-master\vc12\Release\otclient.exe(Image::loadPNG+0xa4) [0x00000000012AA474]
    3: C:\otclient-master\vc12\Release\otclient.exe(Image::load+0x105) [0x00000000012AA305]
    4: C:\otclient-master\vc12\Release\otclient.exe(WIN32Window::setIcon+0x6f) [0x000000000135A7BF]
    5: C:\otclient-master\vc12\Release\otclient.exe(<lambda_900ed0a580071e10fef6cffb96c7e7b5>::operator()+0x181) [0x00000000011EC501]
    6: C:\otclient-master\vc12\Release\otclient.exe(std::_Func_impl<std::_Callable_obj<<lambda_900ed0a580071e10fef6cffb96c7e7b5>,0>,std::allocator<std::_Func_class<int,LuaInterface *> >,int,LuaInterface *>::_Do_call+0x10) [0x0000000001225A00]
    7: C:\otclient-master\vc12\Release\otclient.exe(LuaInterface::luaCppFunctionCallback+0x8b) [0x00000000012BCEEB]
    8: C:\otclient-master\vc12\Release\luajit.dll [0x000000006DBC266F]
    9: C:\Windows\system32\MSVCR120.dll(strerror_s+0x62) [0x0000000071517C00]
    10: C:\otclient-master\vc12\Release\luajit.dll(lua_pcall+0x56) [0x000000006DBC7236]
    11: C:\otclient-master\vc12\Release\otclient.exe(LuaInterface::safeCall+0x105) [0x00000000012BC215]
    12: C:\otclient-master\vc12\Release\otclient.exe(Module::load+0x3b5) [0x000000000129B455]
    13: C:\otclient-master\vc12\Release\otclient.exe(ModuleManager::ensureModuleLoaded+0x68) [0x000000000129DCD8]
    14: C:\otclient-master\vc12\Release\otclient.exe(<lambda_900ed0a580071e10fef6cffb96c7e7b5>::operator()+0x181) [0x00000000011EC501]
    15: C:\otclient-master\vc12\Release\otclient.exe(std::_Func_impl<std::_Callable_obj<<lambda_900ed0a580071e10fef6cffb96c7e7b5>,0>,std::allocator<std::_Func_class<int,LuaInterface *> >,int,LuaInterface *>::_Do_call+0x10) [0x0000000001225A00]
    16: C:\otclient-master\vc12\Release\otclient.exe(LuaInterface::luaCppFunctionCallback+0x8b) [0x00000000012BCEEB]
    17: C:\otclient-master\vc12\Release\luajit.dll [0x000000006DBC266F]
    18: C:\Windows\system32\MSVCR120.dll(strerror_s+0x62) [0x0000000071517C00]
    19: C:\otclient-master\vc12\Release\luajit.dll(lua_pcall+0x56) [0x000000006DBC7236]
    20: C:\otclient-master\vc12\Release\otclient.exe(LuaInterface::safeCall+0x105) [0x00000000012BC215]
    21: C:\otclient-master\vc12\Release\otclient.exe(LuaInterface::safeRunScript+0x48) [0x00000000012BB438]
    22: C:\otclient-master\vc12\Release\otclient.exe(main+0x29a) [0x0000000001399E7A]
    23: C:\otclient-master\vc12\Release\otclient.exe(__tmainCRTStartup+0xfd) [0x00000000013A0175]
    24: C:\Windows\syswow64\kernel32.dll(BaseThreadInitThunk+0x12) [0x00000000753C33AA]
    25: C:\Windows\SysWOW64\ntdll.dll(RtlInitializeExceptionChain+0x63) [0x0000000077C89F72]
    26: C:\Windows\SysWOW64\ntdll.dll(RtlInitializeExceptionChain+0x36) [0x0000000077C89F45]

**Comment by A-Syntax** [comment]
Try using these dlls
http://www.mediafire.com/file/uzs12tdk4bln29s/otclient_dlls.zip

**Comment by chavoz** [comment]
I dont know why people insist in compile with MVS if not have dx9 and people who download it always have dll problems
