### ISSUE TITLE
Compile Error With CodeBlocks - error: 'snprintf' was not declared in this scope

### ISSUE THREAD

**Issue by xSYOx** [edubart/otclient#779]
Hello everybody, there is a strange problem while compiling latest source. I've tested the sources from released 10.44 version and it compiles successful but when I got the master and try to compile this return instead.

c:\mingw\include\boost\asio\detail\impl\win_static_mutex.ipp |51| error: 'swprintf' was not declared in this scope

error: 'snprintf' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]|

why?

**Comment by xSYOx** [comment]
Solved compiling with MSVC instead.

**Comment by chavoz** [comment]
Man i have the same error! And i dont want to compile in MVS due i want DX9 too. Also new players got error with msvcp120.dll and mvscr120.dll instead i putted on the folder xD 

Someone help please!? Whats happening with this new bugged-version code

**Comment by fohs** [comment]
@chavoz 
I had the same issue on master branch and fixed it by checking out a release tag before building,
like:
git checkout v0.6.6

**Comment by Felipe1993** [comment]
omg otclientt dman!
