### ISSUE TITLE
DX9 Visual Studio Compile

### ISSUE THREAD

**Issue by tgobira** [edubart/otclient#780]
Hi there guys.

Anyone tried to compile OTClient with DX9 support?

I`ve downloaded some DX9 DLLs (as said on tutorial) and configured PREPROCESSORS to compile with OPENGL_ES=2, but still got some problems to compile the client.

Does anyone has a tutorial to compile the client with DX9 support?

Ty vm guys!

**Comment by daniofordon** [comment]
otclient no longer supports DX9 you ask pregnancy

**Comment by Riverlance** [comment]
@tgobira You use _OPENGLES=OFF_ for **DX9**, _OPENGLES=2.0_ for **OpenGL**. It's not **OPENGL_ES** and not only **2**.

OFF:
I want to know if is possible to compile DX9 with the Visual Studio.
The actual tutorial does not says anything about this.
If anyone knows, tell me please. Thanks. 😄 👍

**Comment by conde2** [comment]
It does support, you just need to use the right libraries

![image](https://cloud.githubusercontent.com/assets/2137569/22554426/1cd9e8bc-e947-11e6-9044-b0e11d554f57.png)

**Comment by conde2** [comment]
@daniofordon 

It does support DX9, you just need the right libraries, if someone is willing to put a bountry source for this I can build the right libraries and make a tutorial on how to compile using Visual Studio

**Comment by conde2** [comment]
@EaiComeu

**Comment by mestereod** [comment]
Where can i get the libraries?

**Comment by Felipe1993** [comment]
im looking for the libraries too :/
please someone share them :c
