### ISSUE TITLE
 Just a question, sorry if it's bothering you or being repetitive.

### ISSUE THREAD

**Issue by kazumaki** [edubart/otclient#788]
I compiled the newest OTCLIENT and TFS 1.2 repository, but i still getting idle animation bug, can someone tell me if it's for everyone or just me. Protocol 10.98

![image](https://cloud.githubusercontent.com/assets/24276004/20761724/0bfcca78-b70b-11e6-8417-3694f3d89591.png)

**Comment by Zbizu** [comment]
Yeah. Which file stands for animation guys? I could attempt writing a fix.

**Comment by Zbizu** [comment]
(sorry cant edit post on phone) I think all we have to do is to set offset for frames if there are 8 of them.
