### ISSUE TITLE
EGL egl::Surface::initialize(109)

### ISSUE THREAD

**Issue by EmersonHenriique** [edubart/otclient#791]
Good morning, I have a problem when I open the client directx and a log is created with the following message:err: egl::Surface::initialize(109): Unable to set present parameters: 0x80004001

**Comment by Yahcheh** [comment]
same issue, :) 👍

**Comment by Yahcheh** [comment]
i found out my problem,  my case was i did not have the "dll" files for "Directx9," and the other "dll" files that i used to compile the OTClient, :) [DirecktX9 OTClient, Missing  Dll Pack, to Fix Parameters: 0x8004001, ](https://1drv.ms/u/s!AiKt-6ZFSrHhoF3Ln99EhBR92dsX) Place The "DLL", into your "OTClient" Root Folder. 👍
