### ISSUE TITLE
It is no more possible to compile OTClient with CMake

### ISSUE THREAD

**Issue by Fluppix** [edubart/otclient#796]
Following all the tutorials about how to compile OTClient on Windows with CMake, it is no more possible to get this working.

There are serveral errors showing up if you follow the tutorial step-by-step and try to compile then.
Here's a picture of what errors I do get:
http://i.imgur.com/smAGgId.jpg

Could someone approve this?

**Comment by chavoz** [comment]
Happens the same!!!!! 
After 30 seconds of compilling i got this error:
c:\mingw\include\boost\asio\detail\impl\win_static_mutex.ipp|51|error: 'swprintf' was not declared in this scope|

It's so weird, is like it's no more possible compiling with Cmake for now.

**Comment by reyhammer** [comment]
I think the problem is with Boost version that is no longer compatible with the OTClient latest release, I tried using different versions of boost and removed this error, however, other's seems to appear.

**Comment by chavoz** [comment]
Would be nice you upload your exactly mingw with libs included!

**Comment by reyhammer** [comment]
I was unable to compile, however I was able to suppress the actual error, as I don't have enough time I did not worked in charge of compiling this new version.

**Comment by theguxi** [comment]
+1 @Fluppix Have you resolved this issue?

**Comment by Felipe1993** [comment]
i have the same issue
