### ISSUE TITLE
Stable Release for 10.98?

### ISSUE THREAD

**Issue by cmarfil** [edubart/otclient#800]
Hello,

I've checked the releases and it seems that no releases have been released since November since 2014.
¿Exists a "secure" version for 10.98?

Master branch version for example?

Thanks!

**Comment by WibbenZ** [comment]
Simple answer no.
The latest stable version is 1.2 (and that is 10.76?)
If you want a higher version either update 1.2 or use the bleeding edge software.

Once again, use the issue template for the second time again this should have been posted on the support over at OTLand not here.
If you are unsure create a thread there and people will tell you if it's related to the source code or not.
