### ISSUE TITLE
Kicking bug

### ISSUE THREAD

**Issue by Riverlance** [edubart/otclient#803]
I compiled the latest OTClient source with VS2013, latest TFS, with 10.99 protocol.

How to reproduce:
1. Login into your character.
2. Just hold Ctrl+Arrow for 3~5 seconds.
3. You will be kicked and get this error message:
![image](https://cloud.githubusercontent.com/assets/2280432/21965029/9041c6d8-db3e-11e6-8302-d31983d4731d.png)

E.g.,
Ctrl+ArrowUp
Ctrl+ArrowDown
Ctrl+ArrowLeft
Ctrl+ArrowRight

**Comment by Znote** [comment]
Looks similar to this:
https://github.com/otland/forgottenserver/issues/1964#issuecomment-262395646

Client 11 sends potentially 10 times more packets to the server. You should check out how many packets OTClient sends to the server and adjust maxPacketsPerSecond to match the clients output.

**Comment by Riverlance** [comment]
Found this.

![image](https://cloud.githubusercontent.com/assets/2280432/21979131/cb0e20f0-dbc4-11e6-8a36-5a491a25e4c8.png)

**Comment by Riverlance** [comment]
I changed now from:
maxPacketsPerSecond = **25**
to
maxPacketsPerSecond = **250**
as @Znote recommended and it worked 100%.

No error on server or client consoles, and also no kicks.
So, I think we should set this to 250 instead 25, based on @Znote tests at:
https://github.com/otland/forgottenserver/issues/1964#issuecomment-262395646

Thanks for paying attention! 😄 👍

**Comment by Znote** [comment]
You should try to put it as low as possible without it disconnecting you, 250 is optimal for client 11, not neccesarily otclient. Just do the CTRL + move stress test and see how low you can go without being kicked. 

I am curious as to how many packets the otclient sends. If it takes you 3-5 seconds I think setting it to 50 may be sufficient.

**Comment by Riverlance** [comment]
How you did these prints for test?:
https://github.com/otland/forgottenserver/issues/1964#issuecomment-262395646

I will check it right now.

**Comment by Riverlance** [comment]
Well, tried this.
I think the packet limit as 25 (default of latest TFS) is not the problem.
I think the problem is that the OTClient should have a limit between each character rotate action.
I mean. If you hold Ctrl+Left, it will send A LOT of packets.

> On my tests using the record packet data in connection.cpp void Connection::parseHeader as recommended by @Znote :
> Test 1: If you hold Ctrl+Left, it was like almost 55 packets each second.
> Test 2: Now, if you hold Ctrl+Left+Right, it will send almost 110 packets each second.
> Test 3: If you hold Ctrl+Up+Left+Right, it will send almost 165 packets each second.
> Test 4: If you hold Ctrl+Up+Down+Left+Right, it will send almost 220 packets each second.
> Test 5: Now, if you click to walk far away on the Mini Map and also hold Ctrl+Up+Down+Left+Right, it will send almost 230 packets each second.

So I think we need to do 3 changes in here.

> 1. Add a minimal exhaust between each packet send of character rotate, at least like 100 or even just 50 milliseconds.
> 2. Should not be able to rotate your character if you are holding more than 1 direction. **I mean, these are okay**: _Ctrl+Up, Ctrl+Down, Ctrl+Left AND Ctrl+Right_. **But like these are not**: _Ctrl+Up+Down, Ctrl+Left+Right, Ctrl+Up+Right, AND SO ON_.
> 3. Block the character rotation if you are walking (just because I think makes no sense be able to rotate your character while you are walking). You will see what I am talking about how weird it seems if you do the Test 5 mentioned above.

Note: I am just talking about what I think is better for the TFS. :)
