### ISSUE TITLE
Compilling error on CMake in the present

### ISSUE THREAD

**Issue by chavoz** [edubart/otclient#809]
Hello! Actually i have tried a lot of times to compile the latest version of otclient... But it's very imposible! i've tried almost all, first it gave various errores about swprintf not declared, and yeah, that have solution. The solution? (obviously the tutorial didn't specified nothing) was setting the flag     set(CMAKE_CXX_LINK_FLAGS "-U__STRICT_ANSI__") on Cmakelists.txt

Anyway, afther that and when is almost ready to compile the exe (20 minutes and 20 minutes and 20 minutes ........ trying ) it gave this errors:
CMakeFiles\otclient.dir\objects.a(resourcemanager.cpp.obj)resourcemanager.cpp|| undefined reference to `boost::filesystem::path::generic_string[abi:cxx11](std::codecvt<wchar_t, char, int> const&) const'|

CMakeFiles\otclient.dir\objects.a(resourcemanager.cpp.obj)resourcemanager.cpp|| undefined reference to `boost::filesystem::path_traits::convert(char const*, char const*, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&, std::codecvt<wchar_t, char, int> const&)'|

It's like the resoursemanager.cpp have undefined functions called convert and generic_string

Anyway, can ANYONE please PLEASE!!!!!! give support and help? And for the love of god edit that OLD tutorial

**Comment by conde2** [comment]
Probably you need to use boost compiled for MinGW if you are trying to compile under code blocks + mingw

**Comment by chavoz** [comment]
I am using the uploaded libs published here which link is one from MEGA and name it's exactly otclient-libs_mingw32-dwarf3.rar

After that, i got compiling OTC removing the function on resoursemanager that uses generic_string. Then i got an otclient.exe that wights 12-13MB and when i open it opens a CMD log and after that, the client. 
But every otclients i compile have this CRASH when i try to log in and the server is offline (always crash in that case)
The crash report.log generated is:

exception: Access violation (0xc0000005)
exception address: 0x004f9d90
  backtrace:
    0: C:\Users\NICO\Desktop\cliente\Cliente DX9.exe(alGetListeneriv+0x31bc0) [0x004F9D90]
    1: Unknown [0x0028FBF8]
    2: C:\Users\NICO\Desktop\cliente\Cliente DX9.exe(alGetListeneriv+0x28240) [0x004F0410]
    3: C:\Users\NICO\Desktop\cliente\Cliente DX9.exe [0x00475E59]
    4: C:\Users\NICO\Desktop\cliente\Cliente DX9.exe [0x0047480F]
    5: C:\Users\NICO\Desktop\cliente\Cliente DX9.exe(alGetListeneriv+0x1873dc) [0x0064F5AC]
    6: C:\Users\NICO\Desktop\cliente\Cliente DX9.exe(alGetListeneriv+0x1861a9) [0x0064E379]
    7: C:\Users\NICO\Desktop\cliente\Cliente DX9.exe(alGetListeneriv+0x185eae) [0x0064E07E]
    8: C:\Users\NICO\Desktop\cliente\Cliente DX9.exe [0x004742DD]
    9: C:\Users\NICO\Desktop\cliente\Cliente DX9.exe [0x00445C8B]
    10: C:\Users\NICO\Desktop\cliente\Cliente DX9.exe [0x00470A77]
    11: C:\Users\NICO\Desktop\cliente\Cliente DX9.exe(alGetListeneriv+0x28f627) [0x007577F7]
    12: C:\Users\NICO\Desktop\cliente\Cliente DX9.exe [0x0040126D]
    13: C:\Windows\SysWOW64\ntdll.dll(RtlInitializeExceptionChain+0x63) [0x777D9F72]

So if any of you guys know why is this happening, please bring a little help! 
Thanks

**Comment by conde2** [comment]
This log doesn't help, but I may say that the crash is because you removed stuff from the source, so we cannot really help you if you have a custom source.
I would recommend you to use newer libraries versions, and make it compile in the right way, or even try an older version of mingw with those old libraries.
