### ISSUE TITLE
[Premium Days]

### ISSUE THREAD

**Issue by Riverlance** [edubart/otclient#811]
I use the latest TFS and OTClient.

> **1. Premdays client crash**:
If you set the account premdays to 65535 of table `accounts` (65535 means it never ends, I think), the client crashes:
![image](https://cloud.githubusercontent.com/assets/2280432/22385561/4a99559e-e4ba-11e6-968b-5c98c25ffadd.png)
![image](https://cloud.githubusercontent.com/assets/2280432/22385719/f931c67c-e4ba-11e6-8332-93d7e426adf9.png)

> How to reproduce it:
1. Close your client (because you need to reload the characters list by trying to log to the login server).
2. Set your the premdays of account that you will use for test to 65535 exactly.
3. Open your client and try to login. It will crashes when tries to connect to the login server.
Note: Any value different of 65535 will work fine, so you need to try with 65535 as the premdays value.

> **2. Premdays text**:
No matter the text value of the Account Status is always 'Free Account'.
I tested with lots of values, and it never changes.
Also, the only issue is the text, because I still have the premium and everything works fine.
![image](https://cloud.githubusercontent.com/assets/2280432/22385842/8e03f496-e4bb-11e6-9ca7-1b29a7f07c38.png)

> How to reproduce it:
1. Close your client (just for be sure it will work).
2. Set any value for the account premdays of table `accounts`.
3. Open your client and try to login. It will still shows as Free Account.

**Comment by conde2** [comment]
Please give us the debug information otherwise it will be really difficult to find the bug.

**Comment by Riverlance** [comment]
@conde2 How can I do this? :)

**Comment by conde2** [comment]
When the bug occur please click on Debug ("Deupurar") and open it with Visual Studio and click break it should give the line where it caused the bug

**Comment by Riverlance** [comment]
![image](https://cloud.githubusercontent.com/assets/2280432/22392187/d0892738-e4dd-11e6-919f-ec70eddb3895.png)

Like this?

**Comment by conde2** [comment]
Have you made any changes in OTC ? please also provide the log generated by OTClient if there is any.

**Comment by conde2** [comment]
I'm pretty sure this is due to LuaJIT, maybe we need to use just LUA as library, I've read @edubart commenting about this while ago, that LuaJit does not support pcalls or something like that. Maybe he can help saying if this is true or not.

**Comment by Riverlance** [comment]
I have no changes on OTClient yet.

Ok! I will wait your update on OTClient-SDK. Thanks. :)

**Comment by Riverlance** [comment]
I think it was fixed now on: https://github.com/edubart/otclient/commit/df422c0991e80d8c579522e727a6693b5b637865

At least here works now.
So I am closing this thread.
