### ISSUE TITLE
Rendering issues

### ISSUE THREAD

**Issue by ranisalt** [edubart/otclient#812]
I'm having rendering issues and I can't use OTClient because the display is completely broken. It started all of a sudden when I pulled the latest commit and I can't make it work again even reverting to the commit I previously used that worked properly.

The character name is not being drawn, too.

Images:

![Imgur](http://i.imgur.com/Hb4aZ2i.png)

![Imgur](http://i.imgur.com/Dp9cWXZ.jpg)

**Environment:**
Arch Linux up to date
GCC 6.3.1
GLEW 2.0.0
GLU 9.0.0
LuaJIT 2.0.4
libXCB 1.12
physfs 2.0.3
Xorg 1.19.1
zlib 1.2.11

I don't know what other libs are related to graphics, if I'm missing any please ask.

**Comment by conde2** [comment]
Zlib are responsible for loading png UI related stuff, are you building in which OS ?

**Comment by conde2** [comment]
I've faced some problems with ZLib trying to use the static build, because physfs does also include ZLib but it uses other version, so in Windows I've solved this by building ZLib as dynamic.
In your case it looks like the glew library is working correct since the game is being draw smooth, the problem really look likes it is ZLib not loading the png files correct.

**Comment by ranisalt** [comment]
I'm building under Arch Linux, just updated. I added physfs and zlib versions to the OP.

**Comment by conde2** [comment]
Try downgrading ZLib, if it has suddenly start it may be because the system updated ZLib. I'm using 1.2.8.8 on windows, maybe this version works for you

**Comment by ranisalt** [comment]
I'm going to downgrade one by one to see if something works.

**Comment by conde2** [comment]
The problem is knowing which change in ZLib is causing this problem and how to fix it. 
I've find problems with following libs:

ZLib > 1.2.8
Lua ~= 5.1 (Eg LuaJit or Lua 5.2)
OpenSSL >= 1.1

**Comment by ranisalt** [comment]
I'm using LuaJIT just fine as it implements Lua 5.1 and backports just some non-breaking stuff from 5.2

**Comment by conde2** [comment]
You are going to be able to use it but whenever an internal error occur it will crash the client trying to output the stacktraceback to the error.

About ZLib, apngloader class uses code from LibPNG and if you check the[ LibPNG website](http://www.libpng.org/pub/png/libpng.html) you will find:

> The current public release, libpng 1.6.28, fixes a bug exposed by building with the just-released zlib 1.2.9 and 1.2.10. The previous public release, libpng 1.6.27, fixed a 21-year-old null-pointer dereference (see warning below) and included some minor build tweaks.

**Comment by ranisalt** [comment]
It is still not working.

**Comment by hrsantiago** [comment]
This is the fix:
https://github.com/edubart/otclient/blob/master/src/framework/graphics/apngloader.cpp#L168

Change the first parameter to:
z_stream& zstream

**Comment by iryont** [comment]
I thought you guys did fix it by replacing zlib. My bad, nevermind then. However, I wonder why it did work before just fine?
