### ISSUE TITLE
[Crash] Animations of the creatures (not the idle)

### ISSUE THREAD

**Issue by Riverlance** [edubart/otclient#813]
I tested **ALL OUTFITS** and the only ones that is bugged is these outfit client ids:
> [24] E.g., Minotaur Archer
[81] E.g., Cobra
[274] E.g., Squirrel

Proof on latest **TFS+OTClient** (on this picture, all of the are looking to the **north**):

![image](https://cloud.githubusercontent.com/assets/2280432/22397777/4b7e6cbe-e560-11e6-8569-27ffa28dbf48.png)

This is also bugged on latest **RME**  (on this picture, all of the are looking to the **north**):

![image](https://cloud.githubusercontent.com/assets/2280432/22397783/68df6e66-e560-11e6-902b-22b80a3ad462.png)

**Important**: If you try to move these outfits, the client will **crash**.
But I debugged it with Visual Studio as @conde2 recommended once, and it gets this error:

![image](https://cloud.githubusercontent.com/assets/2280432/22397840/cca9f136-e561-11e6-97dd-44cc84ae6665.png)

![image](https://cloud.githubusercontent.com/assets/2280432/22397849/0f936a40-e562-11e6-8d3a-1ffaa8bbae67.png)

> 'otclient.exe' (Win32): Loaded 'C:\kingdom-age-client\otclient.exe'. Symbols loaded.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ntdll.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\kernel32.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\KernelBase.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\user32.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\win32u.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\kingdom-age-client\glew32.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\kingdom-age-client\zlib.dll'. Module was built without symbols.
'otclient.exe' (Win32): Loaded 'C:\kingdom-age-client\openal32.dll'. Module was built without symbols.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\gdi32.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\gdi32full.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\shell32.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcrt.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\cfgmgr32.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\windows.storage.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\combase.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ucrtbase.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\rpcrt4.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ole32.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\sspicli.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\opengl32.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\dbghelp.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\cryptbase.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\sechost.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\bcryptprimitives.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\advapi32.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\powrprof.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\shlwapi.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\vcruntime140.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\kernel.appcore.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\SHCore.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\winmm.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\profapi.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ws2_32.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\glu32.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ddraw.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\winmmbase.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\mswsock.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\dciman32.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\imm32.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\userenv.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\uxtheme.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msctf.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\oleaut32.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\msvcp_win.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\dwmapi.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ig7icd32.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\igdusc32.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\wtsapi32.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\clbcatq.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\propsys.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\dsound.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'D:\Program Files\#\Macro ToolsWorks\_aodll.dll'. Module was built without symbols.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\MMDevAPI.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\devobj.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\AudioSes.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\WinTypes.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'D:\Program Files\#\Macro ToolsWorks\_apmousedll.dll'. Module was built without symbols.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\dnsapi.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\nsi.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\IPHLPAPI.DLL'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\rasadhlp.dll'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\FWPUCLNT.DLL'. Cannot find or open the PDB file.
'otclient.exe' (Win32): Loaded 'C:\Windows\SysWOW64\bcrypt.dll'. Cannot find or open the PDB file.
The thread 0xe8 has exited with code 0 (0x0).
Unhandled exception at 0x772B91CB (ucrtbase.dll) in otclient.exe: Fatal program exit requested.

**NOTE**: I opened the `otclient.log`, but I found nothing useful.

**Comment by gexarthas** [comment]
There is any workaround for this issue?

**Comment by Riverlance** [comment]
This is still bugged. I didn't understand why this issue was closed.

**Comment by iryont** [comment]
I did close it due to lack of description of what is actually going on here. Not to mention the lack of steps to reproduce.

**Comment by Riverlance** [comment]
What? lol
I explained everything.

Just log in on your server and summon / create any of the 3 creatures I mentioned. If it's looking to the north, the outfit will be bugged as showed on the picture. If the creature walk on your screen, it will crash the client and get an error. I tried to debug with MSVC and showed the log I got.

That's it. Wish you understand now.

**Comment by iryont** [comment]
It looks more like a damaged dat file or some unknown properties rather than anything else. That is considering the fact that the rest outfits, as you claim, appear to work just fine.

Anyway, the simplest way to track down the issue would be to open spr/dat within your objects editor and check what is the difference between those outfits and the other ones which appear to work just fine. At first glance it looks like the game client thinks that the size of those outfits is 64x64 (width = height = 2) while in fact it should be 32x32 (width = height = 1).

**Comment by Riverlance** [comment]
@iryont Thanks alot. That fixed successful. The error was that on these 3 outfits, when on group 1 it had width==1 and height==1, but when on group 2 it had width==2 and height==2. So the fix was just to set the group 1 as width==2, heigth==2 and updating the correct sprites of idle animation. Again, thanks! :)

**Comment by iryont** [comment]
Lovely :)
