### ISSUE TITLE
Erro on Open Market or Talk with NPC for trade

### ISSUE THREAD

**Issue by JoseEduardo** [edubart/otclient#814]
I'm getting this error to open the market or talk to the NPC, can anyone tell me what it is? Browsing the FLASH client code, I saw that it is something related to the GOLD Balance of the Account, does anyone know anything else about it?

ERROR: ProtocolGame parse message exception (21 bytes unread, last opcode is 238, prev opcode is -1): unhandled opcode 238

**Comment by conde2** [comment]
Please tell us which version of OTClient and client (e.g 10.99) are you using

**Comment by JoseEduardo** [comment]
I'm using the latest version here from GIT, the Master branch.
The server that I am connecting from is version 10 and version 11 support.

From the little I saw, it is related to this:
Https://github.com/comedinha/Flash-News/blob/6ea5ae82083a68606a955101b8e50c5a7280a8fd/scripts/tibia/network/Connection.as#L320

But I do not have the skill or the knowledge to adapt.

**Comment by conde2** [comment]
Please, be more specific 10.99 10.98 ?? I just want to know which version this feature started so I can add to the sources

**Comment by JoseEduardo** [comment]
![image](https://cloud.githubusercontent.com/assets/2284433/22533438/57021414-e8d5-11e6-8596-6c3f5b12a31b.png)

The version I'm using is a 10, a last version before Tibia 11.

**Comment by JoseEduardo** [comment]
Someone to help me?

**Comment by conde2** [comment]
Version 10.100 is not yet supported. The latest version supported is 10.99

**Comment by JoseEduardo** [comment]
Do you have any predictions, or is anyone already implementing this?
