### ISSUE TITLE
OTClient DX9 compiled in VS 2015

### ISSUE THREAD

**Issue by EaiComeu** [edubart/otclient#815]
Hello, I compiled the Otclient with (OPENGL_ES=2) in the Visual Studio, I used the correct lib, but when I try open the executable it does not open and no give erros. I think its not a problem in DLL, cause I use the same with the executable made in CB.

http://imageshack.com/a/img923/3944/8p1ZJb.gif

**Comment by conde2** [comment]
You need libraries compiled for visual studio you cannot use the ones from CodeBlocks

**Comment by EaiComeu** [comment]
You have the libraries?

**Comment by Anastaciaa** [comment]
Can you tell us which libraries will work?

**Comment by EaiComeu** [comment]
@Anastaciaa,  I think my libraries are wrong, because I compile but the client does not open, Talk to @conde2, he has the libraries.

**Comment by mestereod** [comment]
i would like the libraries ;-;

**Comment by wo11ven** [comment]
I have the same problem. Compiled using angle, but client does not open.
Call stack:

>  	ucrtbase.dll!_abort()	Unknown
 	ucrtbase.dll!common_assert_to_stderr<wchar_t>()	Unknown
 	ucrtbase.dll!common_assert<wchar_t>()	Unknown
 	ucrtbase.dll!__wassert()	Unknown
 	otclient.exe!Texture::Texture(const stdext::shared_object_ptr<Image> & image, bool buildMipmaps, bool) Line 56	C++
	otclient.exe!TextureManager::loadTexture(std::basic_stringstream<char,std::char_traits<char>,std::allocator<char> > & file) Line 149	C++
 	otclient.exe!TextureManager::getTexture(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & fileName) Line 111	C++
 	otclient.exe!BitmapFont::load(const stdext::shared_object_ptr<OTMLNode> & fontNode) Line 42	C++
 	otclient.exe!FontManager::importFont(std::basic_string<char,std::char_traits<char>,std::allocator<char> > file) Line 68	C++
 	[External Code]	
 	otclient.exe!luabinder::call_fun_and_push_result<bool,std::function<bool __cdecl(std::basic_string<char,std::char_traits<char>,std::allocator<char> > const &)>,std::basic_string<char,std::char_traits<char>,std::allocator<char> > >(const std::function<bool __cdecl(std::basic_string<char,std::char_traits<char>,std::allocator<char> > const &)> & f, LuaInterface * <args_0>, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > &) Line 63	C++
 	otclient.exe!luabinder::bind_fun_specializer::__l2::<lambda>(LuaInterface * lua) Line 104	C++
 	[External Code]	
 	otclient.exe!LuaInterface::luaCppFunctionCallback(lua_State * L) Line 638	C++
 	[External Code]

**Comment by Felipe1993** [comment]
someone in otland say that he can compile direxct9 and open gl
with msvc 2015 but he wont share the libraries
anyone here got it working?
im looking for it
