### ISSUE TITLE
Rename Win32 to x86 in otclient.sln

### ISSUE THREAD

**Issue by DSpeichert** [edubart/otclient#822]
Unfortunately tools such as AppVeyor CI only allow to select x64 or x86 as build architectures.
Therefore, it is impossible to select Win32. In order to be able to build those automatically, it would be desirable to rename Win32 build configuration to the standard "x86" name.

**Comment by kornholi** [comment]
That's not [true](https://github.com/otland/forgottenserver/commit/9e4c009630d6cfc82116fd6685652d8a0bb3716c).

**Comment by DSpeichert** [comment]
@kornholi It is when you use AppVeyor externally without the appveyor.yml in the project and only rely on the settings on AppVeyor's site.

**Comment by conde2** [comment]
Instead we should deploy a AppVoyer.yml file for otclient, since I've never used it myself I would appreciate if someone makes a pull request or point me any tutorial on how to do it.

**Comment by DSpeichert** [comment]
I wanted to do that after I get it finished. You should expect a PR soon.
