### ISSUE TITLE
Outfit Colors

### ISSUE THREAD

**Issue by mervakis** [edubart/otclient#823]
Hello, I've found little bug in game.cpp and game.h files.

There is word "Oufit" without "t" (in game.cpp occurs 3x, in game.h 1x) instead of correct "Outfit", it causes ingame bug with dispaying color change panel.

The easiest way to fix it (if someone don't want to compile client again) is to change line 118 of outfit.lua. 

Change from: `local outfitColor = getOutfitColor(j*19 + i)` to `local outfitColor = getOufitColor(j*19 + i)` (just delete letter "t").

I hope it will help someone. :)

**Comment by danilopucci** [comment]
This issue is already fixed on commit 2e3bf66. I think it can closed.
