### ISSUE TITLE
bug with open trade window and don't speak npc to me only bug on otclient

### ISSUE THREAD

**Issue by TibiaFun** [edubart/otclient#824]
### Steps to reproduce (include any configuration/script required to reproduce)
1.download tfs 1.0 and otclient run tibia server
2.login go to npc.
3.hi 
4.trade
5. nothing happen

### Actual behaviour
bug with open trade window and don't speak npc to me only bug on otclient
https://s15.postimg.org/uoxee6n6z/Screen_Shot_02_21_17_at_12_33_PM.png

ERROR: unable to open audio device

ERROR: ProtocolGame parse message exception (34 bytes unread, last opcode is 170, prev opcode is -1): InputMessage eof reached
ERROR: ProtocolGame parse message exception (22 bytes unread, last opcode is 170, prev opcode is -1): InputMessage eof reached

**Comment by conde2** [comment]
Olease, tell us the tibia  version and OTClient version

**Comment by TibiaFun** [comment]
@conde2 tibia 10.41 OTClient newest source.
