### ISSUE TITLE
[Transparency]Bug Floor 7->6

### ISSUE THREAD

**Issue by TibiaFun** [edubart/otclient#829]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [ ] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1.create item transparenty on floor 7

### Expected behaviour
1.show transparenty ground from 7 to 6

### Actual behaviour
1.dont show transparenty ground from 7 to 6

**Comment by TheSumm** [comment]
Did you adjust your server to send the data below ground floor?

**Comment by conde2** [comment]
This is not OTClient bug

**Comment by TibiaFun** [comment]
@TheSumm not, i must something change ? 

@conde2 i trying get help from otland. but here people tell me is problem on client side.

**Comment by hrsantiago** [comment]
If you're at floor 7, the server only send information of tiles above you. No underground information is sent. Therefore, if you put a transparent item on floor 7, you'll get something blackish cause there's nothing under it.

**Comment by TibiaFun** [comment]
@hrsantiago  thanks for reply, how i can do floor 7 working as the same as floor 8?

**Comment by hrsantiago** [comment]
I wouldnt do this. You should rethink your maps.  You'll have performance issues if you draw tiles from floor 0 to 15.

**Comment by TibiaFun** [comment]
@hrsantiago you have a better solution?
