### ISSUE TITLE
bug with custom items

### ISSUE THREAD

**Issue by tarantonio** [edubart/otclient#833]
I'm using a custom items.otb on a server.
In OTC when I add my tibia.dat and tibia.spr to things I have this issue with some sprites:
![2017-04-12 10_33_02-otclient](https://cloud.githubusercontent.com/assets/7066891/25170434/cadf6d36-24ea-11e7-808d-240fd72690f8.png)
I don't have the issue on a default tibia client:
![2017-04-12 10_33_44-tibia](https://cloud.githubusercontent.com/assets/7066891/25170452/d97c5aa2-24ea-11e7-8dcc-df13804c986a.png)

**Comment by danilopucci** [comment]
I got the same issue as you. Have you found any solution?

**Comment by danilopucci** [comment]
I found the solution, for whoever maybe interested. It was a mismatched items in items.otb. 
My solution was solve mismatched items clicking on "Reload item attributes" in [this version of item editor](https://github.com/danilopucci/ItemEditor) compatible with otb files 7.x files. The mismatched items was with a red background and after this everything works fine.
My hypothesis is that the original tibia client just does not care for the background while OTClient, 
correctly, cares about it and cannot draw it.

**Comment by chauffaille** [comment]
> I found the solution, for whoever maybe interested. It was a mismatched items in items.otb.
> My solution was solve mismatched items clicking on "Reload item attributes" in [this version of item editor](https://github.com/danilopucci/ItemEditor) compatible with otb files 7.x files. The mismatched items was with a red background and after this everything works fine.
> My hypothesis is that the original tibia client just does not care for the background while OTClient,
> correctly, cares about it and cannot draw it.

Oi Danilo, voce poderia enviar o items.otb que voce arrumou? não estou conseguindo carregar o meu items.otb no programa.

**Comment by danilopucci** [comment]
> > I found the solution, for whoever maybe interested. It was a mismatched items in items.otb.
> > My solution was solve mismatched items clicking on "Reload item attributes" in [this version of item editor](https://github.com/danilopucci/ItemEditor) compatible with otb files 7.x files. The mismatched items was with a red background and after this everything works fine.
> > My hypothesis is that the original tibia client just does not care for the background while OTClient,
> > correctly, cares about it and cannot draw it.
> 
> Oi Danilo, voce poderia enviar o items.otb que voce arrumou? não estou conseguindo carregar o meu items.otb no programa.

The items.otb that I used it can be found [here](https://otland.net/threads/7-4-otx-rlmap-100-port-hope-7-4-poi-demon-oak-war-system-shared-exp.249949/)

**Comment by chauffaille** [comment]
> > > I found the solution, for whoever maybe interested. It was a mismatched items in items.otb.
> > > My solution was solve mismatched items clicking on "Reload item attributes" in [this version of item editor](https://github.com/danilopucci/ItemEditor) compatible with otb files 7.x files. The mismatched items was with a red background and after this everything works fine.
> > > My hypothesis is that the original tibia client just does not care for the background while OTClient,
> > > correctly, cares about it and cannot draw it.
> > 
> > 
> > Oi Danilo, voce poderia enviar o items.otb que voce arrumou? não estou conseguindo carregar o meu items.otb no programa.
> 
> The items.otb that I used it can be found [here](https://otland.net/threads/7-4-otx-rlmap-100-port-hope-7-4-poi-demon-oak-war-system-shared-exp.249949/)



I am unable to open this items.otb with item editor 0.4, the following message appears: could not find a plugin that could handle client version 3.
could you send me the items.otb that you fixed?

**Comment by danilopucci** [comment]
> > > > I found the solution, for whoever maybe interested. It was a mismatched items in items.otb.
> > > > My solution was solve mismatched items clicking on "Reload item attributes" in [this version of item editor](https://github.com/danilopucci/ItemEditor) compatible with otb files 7.x files. The mismatched items was with a red background and after this everything works fine.
> > > > My hypothesis is that the original tibia client just does not care for the background while OTClient,
> > > > correctly, cares about it and cannot draw it.
> > > 
> > > 
> > > Oi Danilo, voce poderia enviar o items.otb que voce arrumou? não estou conseguindo carregar o meu items.otb no programa.
> > 
> > 
> > The items.otb that I used it can be found [here](https://otland.net/threads/7-4-otx-rlmap-100-port-hope-7-4-poi-demon-oak-war-system-shared-exp.249949/)
> 
> I am unable to open this items.otb with item editor 0.4, the following message appears: could not find a plugin that could handle client version 3.
> could you send me the items.otb that you fixed?

I am Sorry, I do not have it anymore.
You can not open that items.otb with Item Editor 0.4, thats why on my text there is a link to the correct Item Editor

**Comment by gabrieldmello** [comment]
> I found the solution, for whoever maybe interested. It was a mismatched items in items.otb. My solution was solve mismatched items clicking on "Reload item attributes" in [this version of item editor](https://github.com/danilopucci/ItemEditor) compatible with otb files 7.x files. The mismatched items was with a red background and after this everything works fine. My hypothesis is that the original tibia client just does not care for the background while OTClient, correctly, cares about it and cannot draw it.

Bro! Can u help me? I tried your solution, but now my server is not openning with the new items.otb... an error when starts to load the map (just a small error window without text, and after that a prompt window asking to press something to close it).  

I tried to save a new version of my RME map putting this "new" items.otb at the RME folder. When I openned the remere showed some errors with some ids... can u help me? I think maybe the error could be because the new items.otb doesnt comes with a new item.xml? can be it? Any suggestion?
