### ISSUE TITLE
OpenSSL API Change

### ISSUE THREAD

**Issue by diath** [edubart/otclient#837]
### Steps to reproduce (include any configuration/script required to reproduce)
1. Build otclient against OpenSSL 1.1.0x version

### Expected behaviour
The crypto module does compile.

### Actual behaviour
The crypto module does not compile.

### Detail
Basically what happens is that the OpenSSL 1.1.0x and up changed the API and broke backwards compatibility. The RSA struct members are no longer accessible directly. Currently one can just build otclient against the older version of OpenSSL but eventually distros will start shipping the newer version so I'm posting it as something to keep in mind.

Some more information on the topic:
https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes
http://stackoverflow.com/a/40550964

**Comment by ranisalt** [comment]
The hard part is OpenSSL documentation is completely useless. It literally does not document anything other than public signature of methods, which anyone already sees.

I think implementing RSA without OpenSSL, on a fashion similar to forgottenserver, is the way to go. OpenSSL code is complete spaghetti.

**Comment by gesior** [comment]
I would like to see Crypt.cpp without OpenSSL. Can't compile it on Linux Mint (OpenSSL 1.1.0f).

If you know how to make it work without OpenSSL or with OpenSSL 1.1.0f and you need 15$:
https://www.bountysource.com/issues/44639063-openssl-api-change [15$ bounty]

-----
Add 'Bounty' label, like on forgottenserver repo. I'm sure that there are many people ready to pay for bug fixes and new features in otclient.

**Comment by diath** [comment]
For the time being you can simply install OpenSSL 1.0x and point CMake to that OpenSSL installation directory instead but yeah ideally we'd either get rid of OpenSSL as a dependency or make it work with both API versions.

**Comment by edubart** [comment]
In https://github.com/edubart/otclient/commit/8b161e1a07a16f4c6af49575a9a92a8a103ec029 I've made to prefer OpenSSL 1.0 over 1.1

**Comment by JSkalskiSBG** [comment]
@diath  @edubart 
I downloaded, compiled and installed OpenSSL 1.0.2:
	
	q@JSkalski /usr/lib/x86_64-linux-gnu $ ls -lah | grep libcry
	-rw-r--r--   1 root root   60K Jun 16 22:58 libcrypt.a
	-rw-r--r--   1 root root  4.7M Jul  6 13:58 libcrypto.a
	lrwxrwxrwx   1 root root    16 Jul  6 13:57 libcrypto.so -> libcrypto.so.1.1
	-rw-r--r--   1 root root  2.3M May 26 12:23 libcrypto.so.1.0.2
	-rw-r--r--   1 root root  2.5M Jul  6 13:58 libcrypto.so.1.1
	lrwxrwxrwx   1 root root    35 Jun 16 22:58 libcrypt.so -> /lib/x86_64-linux-gnu/libcrypt.so.1
	lrwxrwxrwx   1 root root    19 Dec 15  2014 libcrystalhd.so.3 -> libcrystalhd.so.3.6
	-rw-r--r--   1 root root  109K Dec 15  2014 libcrystalhd.so.3.6
	q@JSkalski /usr/lib/x86_64-linux-gnu $ ls -lah | grep libssl
	-rw-r--r--   1 root root  301K Sep 29 15:44 libssl3.so
	lrwxrwxrwx   1 root root    10 Sep 29 15:44 libssl3.so.1d -> libssl3.so
	-rw-r--r--   1 root root  726K Jul  6 13:58 libssl.a
	lrwxrwxrwx   1 root root    13 Jul  6 13:57 libssl.so -> libssl.so.1.1
	-rw-r--r--   1 root root  417K May 26 12:23 libssl.so.1.0.2
	-rw-r--r--   1 root root  428K Jul  6 13:58 libssl.so.1.1

but when I type 'cmake ..' it still finds 1.1.0 files:

	-- Found PHYSFS: /usr/lib/x86_64-linux-gnu/libphysfs.a  
	-- Found OPENSSL: /usr/lib/x86_64-linux-gnu/libssl.a;/usr/lib/x86_64-linux-gnu/libcrypto.a  
	-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.a 

probably, because 1.0.2 files are in:
*/usr/local/ssl/lib*

How can I force cmake to use this path, not */usr/lib/x86_64-linux-gnu/* ?

**Comment by diath** [comment]
@JSkalskiSBG 
Try setting the OpenSSL_INCLUDE_DIR, OPENSSL_LIBRARY, and OPENSSL_CRYPTO_LIBRARY CMake variables with the -D flag to point to these paths.

**Comment by JSkalskiSBG** [comment]
I don't want to see what will happen to other applications, if I change OpenSSL to 1.0 on my machine.
I forgot that I can just comment RSA code for my 'map generator' and it will work fine.

- - - - -
Anyone knows name of padding scheme used by tibia RSA protocol? Decryption looks like this:

	mpz_import(c, 128, 1, 1, 0, 0, msg);
	// m = c^d mod n
	mpz_powm(m, c, d, n);

	size_t count = (mpz_sizeinbase(m, 2) + 7) / 8;
	memset(msg, 0, 128 - count);
	mpz_export(msg + (128 - count), nullptr, 1, 1, 0, 0, m);
 
Is it just filled with ZEROs?

RSA looks like something super easy to implement. As we can see in TFS implementation of RSA there is hardcoded RSA key length equal to 1024 bits. I think I can implement it.

// Gesior at work

**Comment by diath** [comment]
>I don't want to see what will happen to other applications, if I change OpenSSL to 1.0 on my machine.
I was implying that you should simply install it alongside the default installation with a different prefix path that CMake can pick up.

**Comment by JSkalskiSBG** [comment]
I wrote rsaEncrypt and rsaDecrypt functions based on forgottenserver and Wikipedia RSA documentation with pure GMP library. I need few days to test, if it works fine.
Then I will search for sha1/256/512 and md5 pure C++ codes (forgottenserver?) and then I will pull request.

If you know anyone who got idea about cryptography, it would be nice to check my algorithm implementation. I know it's weak 1024 bit and there is no padding scheme, but it's tibia protocol version:

	void Crypt::rsaSetPublicKey(const std::string& nString, const std::string& eString)
	{
		mpz_clear(nEncrypt);
		mpz_clear(e);

		mpz_init2(nEncrypt, 1024);
		mpz_init2(e, 1024);

		mpz_set_str(nEncrypt, nString.c_str(), 10);
		mpz_set_str(e, eString.c_str(), 10);
	}

	void Crypt::rsaSetPrivateKey(const std::string& pString, const std::string& qString, const std::string& dString)
	{
		// load d
		mpz_clear(d);
		mpz_init2(d, 1024);
		mpz_set_str(d, dString.c_str(), 10);

		// calculate n for decrypt
		mpz_t p, q;
		mpz_init2(p, 1024);
		mpz_init2(q, 1024);

		mpz_set_str(p, pString.c_str(), 10);
		mpz_set_str(q, qString.c_str(), 10);

		mpz_mul(nDecrypt, p, q);

		mpz_clear(p);
		mpz_clear(q);
	}

	bool Crypt::rsaCheckKey()
	{
		// unimplemented
		return false;
	}

	bool Crypt::rsaEncrypt(unsigned char *msg, int size)
	{
		if(size != rsaGetSize())
			return false;

		mpz_t c, m;
		mpz_init2(c, 1024);
		mpz_init2(m, 1024);

		mpz_import(m, 128, 1, 1, 0, 0, msg);

		// c=m^e mod n
		mpz_powm(c, m, e, n);

		size_t count = (mpz_sizeinbase(c, 2) + 7) / 8;
		memset(msg, 0, 128 - count);
		mpz_export(msg + (128 - count), nullptr, 1, 1, 0, 0, c);

		mpz_clear(c);
		mpz_clear(m);
	}

	bool Crypt::rsaDecrypt(unsigned char *msg, int size)
	{
		if(size != rsaGetSize())
			return false;

		mpz_t c, m;
		mpz_init2(c, 1024);
		mpz_init2(m, 1024);

		mpz_import(c, 128, 1, 1, 0, 0, msg);

		// m = c^d mod n
		mpz_powm(m, c, d, n);

		size_t count = (mpz_sizeinbase(m, 2) + 7) / 8;
		memset(msg, 0, 128 - count);
		mpz_export(msg + (128 - count), nullptr, 1, 1, 0, 0, m);

		mpz_clear(c);
		mpz_clear(m);
	}

	int Crypt::rsaGetSize()
	{
		return 128;
	}

**Comment by ranisalt** [comment]
MD5 and SHA are never used and can be safely removed. If they are ever needed, they can be implemented in pure Lua with insignificant performance hit.
