### ISSUE TITLE
Black screen problem

### ISSUE THREAD

**Issue by Tommy402** [edubart/otclient#842]
Hello.
I compiled the lastest OTClient for **Android** OS. When I minimize the client (for example by pressing Home button or holding Menu button and selecting other app from Recently list) and after this I go back to the OTClient, the game screen is black. It occurs in all Tibia versions.

I suppose the problem can occur at one of _MainActivity#onPause_, _MainActivity#onResume_ or _NativeSurfaceView#surfaceDestroyed_ (Java side code), but I have no idea how to fix it,

**Comment by BrunoVillanova** [comment]
> Hello. I compiled the lastest OTClient for **Android** OS. When I minimize the client (for example by pressing Home button or holding Menu button and selecting other app from Recently list) and after this I go back to the OTClient, the game screen is black. It occurs in all Tibia versions.
> 
> I suppose the problem can occur at one of _MainActivity#onPause_, _MainActivity#onResume_ or _NativeSurfaceView#surfaceDestroyed_ (Java side code), but I have no idea how to fix it,

Hi @Tommy402 ,

I am facing the same issue.
Did you manage to fix that?

Thanks.
