### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by GustavoBlaze** [edubart/otclient#848]
When I open OTClient it stops working.
So I clicked to debug with visual studio 2015 and I received it. Anyone know what I can do?
Version 10.97
I'm using Windows 10 x64
Edit:
- The OTClient's crashing when I try to login. But the crash happens just sometimes.
- Using breakpoints I saw that the application crash when the variable "ret" != 0. 
- C++ call failed: InputMessage eof reached
stack traceback:
	[builtin#141]: at 0x0146d040
	[C]: in function 'getString'
	/gamelib/protocollogin.lua:192: in function 'parseSessionKey'
	/gamelib/protocollogin.lua:173: in function </gamelib/protocollogin.lua:148>

![crash](https://cloud.githubusercontent.com/assets/25311644/26428862/3c17b5f4-40ba-11e7-84b0-50b20bb3e7f6.png)

**Comment by srjean** [comment]
opa Gustavo conseguiu arruma o erro110?

**Comment by GustavoBlaze** [comment]
erro 110?

**Comment by srjean** [comment]
https://uploaddeimagens.com.br/imagens/screenshot_2017-05-23-20-34-20-png
