### ISSUE TITLE
Perfomance OTClient (table.insert)

### ISSUE THREAD

**Issue by Eternal-Scripts** [edubart/otclient#851]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [ ] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Use for loop to insert in a table 20k+ rows.
2. Use other loop to read if have any value in table.
3. Put a cycleevent or any event where have a repeat function.

### Expected behaviour

Works normal without any problem.

### Actual behaviour

He starts freezing OTClient and have chance of crashing.

### Environment

I think this affect the perfomance of game and to solution this need multithreading for not affect the game.

**Comment by hrsantiago** [comment]
You need to be more specific.
You marked that the bug is in this repository, so point in the source where this cycleEvent with the loop is.

**Comment by Eternal-Scripts** [comment]
Sorry for mistake, i will try to explain better.
In a multithreading software when he support lua scripting when you store many rows in a table and try manipulate he don't lag (with task/thread) but in OTClient when you try store in a table and have 20k rows +- he starts freezing.

Normal Software with thread/task: 20k rows => runs normal.
OTClient without thread/task: 20k rows => freezes client and have chance of crashing.

I tried this issue creating a module where he get all tiles in screen and store in a table the id, pos, stack.
Idk if is a issue of OTClient but in other softwares when i code a .lua where need store many informations don't occurs this problem.

**Comment by hrsantiago** [comment]
OTC is single thread, so if you do something heavy, UI (and everything else) will freeze.
I'd recommend you to use cycleEvent with smaller loops, each time you get parts of the information you need.
As this is not an OTC issue, I'll close this.
