### ISSUE TITLE
Function jump

### ISSUE THREAD

**Issue by stayxtru3** [edubart/otclient#853]
I have a problem, I went to test the jump function and it makes my client crash when the player goes down from the jump, I tested with another client and it works normal, what can it be?

g_game.getLocalPlayer():jump(20, 500)

**Comment by Riverlance** [comment]
Confirmed, same here. Bugging when player goes down.

**Comment by reyhammer** [comment]
The value from the quadratic equation is being casted wrongly, just remove the cast and it will work again.

@edubart - Remove cast from there.
