### ISSUE TITLE
Problem's with login onto 7.72 OTS

### ISSUE THREAD

**Issue by xNarkon** [edubart/otclient#854]
Hello,

I'm developing new OTS with OTClient and have the login problem.
Server is 101% Ok because I can connect through old cipsoft client, but with OTClient I'm getting message "Enter your network or the server went down (ERROR2)". What can be wrong? I can see with debugging the server that the login packet is a little different than this from Cipsoft Client ( on the 19th byte there should be \0 but there is not... )

So maybe this is problem with OTClient 7.72 Protocol?

**Comment by 4drik** [comment]
I connected to 7.72 OTS without any problems just right now.

**Comment by Fibrosis** [comment]
I have the same problem hosting the realots server files.
After changing the RSA key to the old client's RSA (142996239624163995...) I get to the character login screen, but after choosing a character the client is stuck on "Connecting to game server..." while in the console there's the error:
`ERROR: invalid decrypted network message
C++ stack traceback:
	[C++]: Protocol::xteaDecrypt
[...]
ERROR: failed to decrypt message
C++ stack traceback:
	[C++]: Protocol::internalRecvData
[...]`
