### ISSUE TITLE
to 7.4 server error

### ISSUE THREAD

**Issue by Kuhicop** [edubart/otclient#862]
Hello when I try to connect to my server 7.4 it says Error only protocol 10.98 allowed.

How can I solve this?

**Comment by Riverlance** [comment]
Create an otmod inside mods folder like: mods/myserver.otmod
And add this content:
``` lua
Module
  name: myserver
  description: My unique server
  author: Kuhitacop
  website: http://myserver.com
  sandboxed: true
  autoload: true
  autoload-priority: 1000
  @onLoad: |
    EnterGame.setUniqueServer('myserver.com', 7171, 740)
```

Open your client again.
It will automatically set the client IP, port and protocol as unique.
It means you will never need to set it on the server list anymore.
