### ISSUE TITLE
Function Creature::jump

### ISSUE THREAD

**Issue by 4drik** [edubart/otclient#868]
When I use function **_void Creature::jump(int height, int duration)_** my character is not jumping up but teleport to the max height and then falling down.

I think it should moving character up pixel by pixel.
Now it looks more like teleport.

I'm compiling newest source with Code::Blocks.

**Comment by 4drik** [comment]
OK. That's strange but the function from mobile_port works pretty well.

**Comment by reyhammer** [comment]
Remove the cast from the line that has the equation and the problem will be solved !
