### ISSUE TITLE
Erro : tinyxmlparser.cpp 

### ISSUE THREAD

**Issue by Tekadon58** [edubart/otclient#881]
[ 70%] Building CXX object CMakeFiles/otclient.dir/src/framework/xml/tinyxmlparser.cpp.o
/home/anderson/Documentos/otclient/src/framework/xml/tinyxmlparser.cpp: In static member function ‘static void TiXmlBase::ConvertUTF32ToUTF8(long unsigned int, char*, int*)’:
/home/anderson/Documentos/otclient/src/framework/xml/tinyxmlparser.cpp:113:19: warning: this statement may fall through [-Wimplicit-fallthrough=]
             input >>= 6;
             ~~~~~~^~~~~
/home/anderson/Documentos/otclient/src/framework/xml/tinyxmlparser.cpp:114:9: note: here
         case 3:
         ^~~~
/home/anderson/Documentos/otclient/src/framework/xml/tinyxmlparser.cpp:117:19: warning: this statement may fall through [-Wimplicit-fallthrough=]
             input >>= 6;
             ~~~~~~^~~~~
/home/anderson/Documentos/otclient/src/framework/xml/tinyxmlparser.cpp:118:9: note: here
         case 2:
         ^~~~
/home/anderson/Documentos/otclient/src/framework/xml/tinyxmlparser.cpp:121:19: warning: this statement may fall through [-Wimplicit-fallthrough=]
             input >>= 6;
             ~~~~~~^~~~~
/home/anderson/Documentos/otclient/src/framework/xml/tinyxmlparser.cpp:122:9: note: here
         case 1:
         ^~~~

**Comment by edubart** [comment]
No harm in that warning but fixed in https://github.com/edubart/otclient/commit/8b161e1a07a16f4c6af49575a9a92a8a103ec029
