### ISSUE TITLE
Erro thingtype.cpp.o

### ISSUE THREAD

**Issue by Tekadon58** [edubart/otclient#882]
/home/anderson/Documentos/otclient/src/client/thingtype.cpp: In member function ‘void ThingType::unserialize(uint16, ThingCategory, const FileStreamPtr&)’:
/home/anderson/Documentos/otclient/src/client/thingtype.cpp:278:15: warning: variable ‘frameGroupType’ set but not used [-Wunused-but-set-variable]
         uint8 frameGroupType = FrameGroupDefault;
               ^~~~~~~~~~~~~~

**Comment by edubart** [comment]
Duplicate for #883
