### ISSUE TITLE
Erro protocolgameparse.cpp.o

### ISSUE THREAD

**Issue by Tekadon58** [edubart/otclient#883]
[ 93%] Building CXX object CMakeFiles/otclient.dir/src/client/protocolgameparse.cpp.o
/home/anderson/Documentos/otclient/src/client/protocolgameparse.cpp: In member function ‘void ProtocolGame::parseStore(const InputMessagePtr&)’:
/home/anderson/Documentos/otclient/src/client/protocolgameparse.cpp:502:13: warning: variable ‘highlightState’ set but not used [-Wunused-but-set-variable]
         int highlightState = 0;
             ^~~~~~~~~~~~~~
/home/anderson/Documentos/otclient/src/client/protocolgameparse.cpp: In member function ‘void ProtocolGame::parseCoinBalance(const InputMessagePtr&)’:
/home/anderson/Documentos/otclient/src/client/protocolgameparse.cpp:522:9: warning: variable ‘coins’ set but not used [-Wunused-but-set-variable]
     int coins = -1;
         ^~~~~
/home/anderson/Documentos/otclient/src/client/protocolgameparse.cpp:523:9: warning: variable ‘transferableCoins’ set but not used [-Wunused-but-set-variable]
     int transferableCoins = -1;
         ^~~~~~~~~~~~~~~~~
/home/anderson/Documentos/otclient/src/client/protocolgameparse.cpp: In member function ‘void ProtocolGame::parseStoreTransactionHistory(const InputMessagePtr&)’:
/home/anderson/Documentos/otclient/src/client/protocolgameparse.cpp:555:9: warning: variable ‘currentPage’ set but not used [-Wunused-but-set-variable]
     int currentPage;
         ^~~~~~~~~~~
/home/anderson/Documentos/otclient/src/client/protocolgameparse.cpp: In member function ‘void ProtocolGame::parsePlayerStats(const InputMessagePtr&)’:
/home/anderson/Documentos/otclient/src/client/protocolgameparse.cpp:1354:7: warning: suggest explicit braces to avoid ambiguous ‘else’ [-Wdangling-else]
     if(g_game.getFeature(Otc::GameExperienceBonus))
       ^

**Comment by edubart** [comment]
Those warnings do no harm and fixing them in the code would make the code less readable, any case I've disabled those warnings in CXX flags.
