### ISSUE TITLE
error while compiling for Deepin

### ISSUE THREAD

**Issue by Tekadon58** [edubart/otclient#884]
/home/anderson/otclient/src/framework/util/crypt.cpp:315:56: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
     g_logger.info(std::string("p = ") + BN_bn2dec(m_rsa->p));
                                                        ^~
In file included from /home/anderson/otclient/src/framework/util/crypt.cpp:23:0:
/home/anderson/otclient/src/framework/util/crypt.h:31:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^~~~~~
/home/anderson/otclient/src/framework/util/crypt.cpp:316:56: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
     g_logger.info(std::string("q = ") + BN_bn2dec(m_rsa->q));
                                                        ^~
In file included from /home/anderson/otclient/src/framework/util/crypt.cpp:23:0:
/home/anderson/otclient/src/framework/util/crypt.h:31:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^~~~~~
/home/anderson/otclient/src/framework/util/crypt.cpp:317:56: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
     g_logger.info(std::string("d = ") + BN_bn2dec(m_rsa->d));
                                                        ^~
In file included from /home/anderson/otclient/src/framework/util/crypt.cpp:23:0:
/home/anderson/otclient/src/framework/util/crypt.h:31:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^~~~~~
/home/anderson/otclient/src/framework/util/crypt.cpp:318:56: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
     g_logger.info(std::string("n = ") + BN_bn2dec(m_rsa->n));
                                                        ^~
In file included from /home/anderson/otclient/src/framework/util/crypt.cpp:23:0:
/home/anderson/otclient/src/framework/util/crypt.h:31:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^~~~~~
/home/anderson/otclient/src/framework/util/crypt.cpp:319:56: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
     g_logger.info(std::string("e = ") + BN_bn2dec(m_rsa->e));
                                                        ^~
In file included from /home/anderson/otclient/src/framework/util/crypt.cpp:23:0:
/home/anderson/otclient/src/framework/util/crypt.h:31:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^~~~~~
/home/anderson/otclient/src/framework/util/crypt.cpp: In member function ‘void Crypt::rsaSetPublicKey(const string&, const string&)’:
/home/anderson/otclient/src/framework/util/crypt.cpp:326:21: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
     BN_dec2bn(&m_rsa->n, n.c_str());
                     ^~
In file included from /home/anderson/otclient/src/framework/util/crypt.cpp:23:0:
/home/anderson/otclient/src/framework/util/crypt.h:31:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^~~~~~
/home/anderson/otclient/src/framework/util/crypt.cpp:327:21: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
     BN_dec2bn(&m_rsa->e, e.c_str());
                     ^~
In file included from /home/anderson/otclient/src/framework/util/crypt.cpp:23:0:
/home/anderson/otclient/src/framework/util/crypt.h:31:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^~~~~~
/home/anderson/otclient/src/framework/util/crypt.cpp:330:13: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
     if(m_rsa->_method_mod_n) { BN_MONT_CTX_free(m_rsa->_method_mod_n); m_rsa->_method_mod_n = NULL; }
             ^~
In file included from /home/anderson/otclient/src/framework/util/crypt.cpp:23:0:
/home/anderson/otclient/src/framework/util/crypt.h:31:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^~~~~~
/home/anderson/otclient/src/framework/util/crypt.cpp:330:54: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
     if(m_rsa->_method_mod_n) { BN_MONT_CTX_free(m_rsa->_method_mod_n); m_rsa->_method_mod_n = NULL; }
                                                      ^~
In file included from /home/anderson/otclient/src/framework/util/crypt.cpp:23:0:
/home/anderson/otclient/src/framework/util/crypt.h:31:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^~~~~~
/home/anderson/otclient/src/framework/util/crypt.cpp:330:77: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
     if(m_rsa->_method_mod_n) { BN_MONT_CTX_free(m_rsa->_method_mod_n); m_rsa->_method_mod_n = NULL; }
                                                                             ^~
In file included from /home/anderson/otclient/src/framework/util/crypt.cpp:23:0:
/home/anderson/otclient/src/framework/util/crypt.h:31:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^~~~~~
/home/anderson/otclient/src/framework/util/crypt.cpp: In member function ‘void Crypt::rsaSetPrivateKey(const string&, const string&, const string&)’:
/home/anderson/otclient/src/framework/util/crypt.cpp:335:21: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
     BN_dec2bn(&m_rsa->p, p.c_str());
                     ^~
In file included from /home/anderson/otclient/src/framework/util/crypt.cpp:23:0:
/home/anderson/otclient/src/framework/util/crypt.h:31:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^~~~~~
/home/anderson/otclient/src/framework/util/crypt.cpp:336:21: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
     BN_dec2bn(&m_rsa->q, q.c_str());
                     ^~
In file included from /home/anderson/otclient/src/framework/util/crypt.cpp:23:0:
/home/anderson/otclient/src/framework/util/crypt.h:31:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^~~~~~
/home/anderson/otclient/src/framework/util/crypt.cpp:337:21: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
     BN_dec2bn(&m_rsa->d, d.c_str());
                     ^~
In file included from /home/anderson/otclient/src/framework/util/crypt.cpp:23:0:
/home/anderson/otclient/src/framework/util/crypt.h:31:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^~~~~~
/home/anderson/otclient/src/framework/util/crypt.cpp:340:13: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
     if(m_rsa->_method_mod_p) { BN_MONT_CTX_free(m_rsa->_method_mod_p); m_rsa->_method_mod_p = NULL; }
             ^~
In file included from /home/anderson/otclient/src/framework/util/crypt.cpp:23:0:
/home/anderson/otclient/src/framework/util/crypt.h:31:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^~~~~~
/home/anderson/otclient/src/framework/util/crypt.cpp:340:54: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
     if(m_rsa->_method_mod_p) { BN_MONT_CTX_free(m_rsa->_method_mod_p); m_rsa->_method_mod_p = NULL; }
                                                      ^~
In file included from /home/anderson/otclient/src/framework/util/crypt.cpp:23:0:
/home/anderson/otclient/src/framework/util/crypt.h:31:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^~~~~~
/home/anderson/otclient/src/framework/util/crypt.cpp:340:77: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
     if(m_rsa->_method_mod_p) { BN_MONT_CTX_free(m_rsa->_method_mod_p); m_rsa->_method_mod_p = NULL; }
                                                                             ^~
In file included from /home/anderson/otclient/src/framework/util/crypt.cpp:23:0:
/home/anderson/otclient/src/framework/util/crypt.h:31:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^~~~~~
/home/anderson/otclient/src/framework/util/crypt.cpp:341:13: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
     if(m_rsa->_method_mod_q) { BN_MONT_CTX_free(m_rsa->_method_mod_q); m_rsa->_method_mod_q = NULL; }
             ^~
In file included from /home/anderson/otclient/src/framework/util/crypt.cpp:23:0:
/home/anderson/otclient/src/framework/util/crypt.h:31:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^~~~~~
/home/anderson/otclient/src/framework/util/crypt.cpp:341:54: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
     if(m_rsa->_method_mod_q) { BN_MONT_CTX_free(m_rsa->_method_mod_q); m_rsa->_method_mod_q = NULL; }
                                                      ^~
In file included from /home/anderson/otclient/src/framework/util/crypt.cpp:23:0:
/home/anderson/otclient/src/framework/util/crypt.h:31:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^~~~~~
/home/anderson/otclient/src/framework/util/crypt.cpp:341:77: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
     if(m_rsa->_method_mod_q) { BN_MONT_CTX_free(m_rsa->_method_mod_q); m_rsa->_method_mod_q = NULL; }
                                                                             ^~
In file included from /home/anderson/otclient/src/framework/util/crypt.cpp:23:0:
/home/anderson/otclient/src/framework/util/crypt.h:31:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^~~~~~
In file included from /usr/include/openssl/asn1.h:24:0,
                 from /usr/include/openssl/rsa.h:16,
                 from /home/anderson/otclient/src/framework/util/crypt.cpp:35:
/home/anderson/otclient/src/framework/util/crypt.cpp: In member function ‘bool Crypt::rsaCheckKey()’:
/home/anderson/otclient/src/framework/util/crypt.cpp:352:21: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
         BN_mod(m_rsa->dmp1, m_rsa->d, r1, ctx);
                     ^
In file included from /home/anderson/otclient/src/framework/util/crypt.cpp:23:0:
/home/anderson/otclient/src/framework/util/crypt.h:31:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^~~~~~
In file included from /usr/include/openssl/asn1.h:24:0,
                 from /usr/include/openssl/rsa.h:16,
                 from /home/anderson/otclient/src/framework/util/crypt.cpp:35:
/home/anderson/otclient/src/framework/util/crypt.cpp:352:34: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
         BN_mod(m_rsa->dmp1, m_rsa->d, r1, ctx);
                                  ^
In file included from /home/anderson/otclient/src/framework/util/crypt.cpp:23:0:
/home/anderson/otclient/src/framework/util/crypt.h:31:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^~~~~~
In file included from /usr/include/openssl/asn1.h:24:0,
                 from /usr/include/openssl/rsa.h:16,
                 from /home/anderson/otclient/src/framework/util/crypt.cpp:35:
/home/anderson/otclient/src/framework/util/crypt.cpp:353:21: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
         BN_mod(m_rsa->dmq1, m_rsa->d, r2, ctx);
                     ^
In file included from /home/anderson/otclient/src/framework/util/crypt.cpp:23:0:
/home/anderson/otclient/src/framework/util/crypt.h:31:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^~~~~~
In file included from /usr/include/openssl/asn1.h:24:0,
                 from /usr/include/openssl/rsa.h:16,
                 from /home/anderson/otclient/src/framework/util/crypt.cpp:35:
/home/anderson/otclient/src/framework/util/crypt.cpp:353:34: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
         BN_mod(m_rsa->dmq1, m_rsa->d, r2, ctx);
                                  ^
In file included from /home/anderson/otclient/src/framework/util/crypt.cpp:23:0:
/home/anderson/otclient/src/framework/util/crypt.h:31:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^~~~~~
/home/anderson/otclient/src/framework/util/crypt.cpp:355:29: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
         BN_mod_inverse(m_rsa->iqmp, m_rsa->q, m_rsa->p, ctx);
                             ^~
In file included from /home/anderson/otclient/src/framework/util/crypt.cpp:23:0:
/home/anderson/otclient/src/framework/util/crypt.h:31:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^~~~~~
/home/anderson/otclient/src/framework/util/crypt.cpp:355:42: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
         BN_mod_inverse(m_rsa->iqmp, m_rsa->q, m_rsa->p, ctx);
                                          ^~
In file included from /home/anderson/otclient/src/framework/util/crypt.cpp:23:0:
/home/anderson/otclient/src/framework/util/crypt.h:31:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^~~~~~
/home/anderson/otclient/src/framework/util/crypt.cpp:355:52: error: invalid use of incomplete type ‘RSA {aka struct rsa_st}’
         BN_mod_inverse(m_rsa->iqmp, m_rsa->q, m_rsa->p, ctx);
                                                    ^~
In file included from /home/anderson/otclient/src/framework/util/crypt.cpp:23:0:
/home/anderson/otclient/src/framework/util/crypt.h:31:16: note: forward declaration of ‘RSA {aka struct rsa_st}’
 typedef struct rsa_st RSA;
                ^~~~~~
CMakeFiles/otclient.dir/build.make:110: recipe for target 'CMakeFiles/otclient.dir/src/framework/util/crypt.cpp.o' failed
make[2]: *** [CMakeFiles/otclient.dir/src/framework/util/crypt.cpp.o] Error 1
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/otclient.dir/all' failed
make[1]: *** [CMakeFiles/otclient.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by EvulMastah** [comment]
Downgrade openssl.

**Comment by Tekadon58** [comment]
How to do this not Deepin?

**Comment by Tekadon58** [comment]
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
Alguns pacotes não puderam ser instalados. Isto pode significar que
você solicitou uma situação impossível ou, se você está usando a
distribuição instável, que alguns pacotes requeridos não foram
criados ainda ou foram retirados da "Incoming".
A informação a seguir pode ajudar a resolver a situação:

Os pacotes a seguir têm dependências desencontradas:
 libboost1.58-all-dev : Depende: libboost-graph-parallel1.58-dev mas não será instalado
                        Depende: libboost-mpi1.58-dev mas não será instalado
                        Depende: libboost-mpi-python1.58-dev mas não será instalado
E: Impossível corrigir problemas, você manteve (hold) pacotes quebrados.

**Comment by edubart** [comment]
I've make cmake search and prefer OpenSSL 1.0 when installed in https://github.com/edubart/otclient/commit/8b161e1a07a16f4c6af49575a9a92a8a103ec029
Some distros can have both  OpenSSL 1.0 and 1.1 installed, to fix install OpenSSL 1.0

**Comment by miqueiaspenha** [comment]
I had the same problem, I was able to solve this link.

https://otland.net/threads/debian-installing-library-to-compile-otclient-failed.253692/page-3#post-2470640

**Comment by rwxsu** [comment]
add this to the wiki ```apt-get install libssl1.0-dev```
