### ISSUE TITLE
Error compiling for Ubuntu 

### ISSUE THREAD

**Issue by Tekadon58** [edubart/otclient#885]
[  1%] Linking CXX executable otclient
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libphysfs.a: error adding symbols: Aquivo não possui índice; execute ranlib para adicionar um
collect2: error: ld returned 1 exit status
CMakeFiles/otclient.dir/build.make:3857: recipe for target 'otclient' failed
make[2]: *** [otclient] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/otclient.dir/all' failed
make[1]: *** [CMakeFiles/otclient.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by edubart** [comment]
This is your setup problem.

**Comment by miqueiaspenha** [comment]
Sorry for posting.

1. Install mercurial

```
sudo apt-get install mercurial
```

2. Download physfs source:
```
hg clone -r stable-2.0 http://hg.icculus.org/icculus/physfs/
```

3. Run:
```
cd physfs
sudo mkdir build
cd build
```

4. Now we want to start compile/install it:
```
sudo cmake ..
sudo make
sudo make install
sudo cp /usr/local/lib/libphysfs.a /usr/lib/gcc/x86_64-linux-gnu/
```
https://otland.net/threads/otclient-compile.242669/

After continuity to the compilation procedure

https://github.com/edubart/otclient/wiki/Compiling-on-Linux
