### ISSUE TITLE
error compiling for mobile

### ISSUE THREAD

**Issue by Tekadon58** [edubart/otclient#887]
C:\Windows\system32>cd ..

C:\Windows>mkdir build_android
Já existe uma subpasta ou um arquivo build_android.

C:\Windows>cd build_android

C:\Windows\build_android>cmake -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=../android/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a -DANDROID_NATIVE_API_LEVEL=android-16 -DANDROID_TOOLCHAIN_NAME=arm-linux-androideabi-4.6 ..
CMake Error at /usr/share/cmake-3.6.2/Modules/CMakeDetermineSystem.cmake:104 (message):
  Could not find toolchain file: ../android/android.toolchain.cmake
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)

CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

C:\Windows\build_android>make
make: *** No targets specified and no makefile found.  Stop.

C:\Windows\build_android>cd ../

C:\Windows>xcopy /E /Y libs android\project\libs
Arquivo não encontrado  - libs
0 arquivo(s) copiado(s)

C:\Windows>cd android\project
O sistema não pode encontrar o caminho especificado.

C:\Windows>call android update project -p . --name OTClient --target android-16
**************************************************************************
The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools\bin\sdkmanager.bat
and tools\bin\avdmanager.bat
**************************************************************************

Invalid or unsupported command "update project -p . --name OTClient --target android-16"

Supported commands are:
android list target
android list avd
android list device
android create avd
android move avd
android delete avd
android list sdk
android update sdk
Buildfile: build.xml does not exist!
Build failed
O sistema não pode encontrar o caminho especificado.
* daemon not running. starting it now at tcp:5037 *
* daemon started successfully *
error: no devices/emulators found
adb: error: failed to get feature set: no devices/emulators found
- waiting for device -

**Comment by EgzoT** [comment]
The problem is only with higher SDK version. Because newest SDK doesn't work with terminal commands (look your error). You need to download older SDK version, for example r24.4.1.
