### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by davifo** [edubart/otclient#889]
Compiling in windows 10, Visual Studio

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2660	'stdext::time': function does not take 1 arguments	otclient	E:\workspace-ot\otclient\src\framework\stdext\time.cpp	32	

Last Version OtClient

**Comment by EgzoT** [comment]
> Compiling in windows 10, Visual Studio

But what version of Visual Studio?
Recommended version is VS15.

**Comment by matheusalbino** [comment]
I have the same problem, using VS15

**Comment by davifo** [comment]
VS15 Update 3

**Comment by edubart** [comment]
Should be fixed in https://github.com/edubart/otclient/commit/2095951e07a13305ad3b62273044b3abe8372bd6
