### ISSUE TITLE
Unable to put windows inside windows

### ISSUE THREAD

**Issue by andersonfaaria** [edubart/otclient#892]
First of all, I'm trying to do something like this:
![screenshot_6](https://user-images.githubusercontent.com/8560144/32713477-99e36112-c830-11e7-87a8-acb74b798dae.png)

### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Try to insert any of the buttons of the upper bar inside inventory (to mimic tibia's client)
![screenshot_7](https://user-images.githubusercontent.com/8560144/32713520-ba28318c-c830-11e7-9e99-e3b0d0f8623d.png)

2. Get error message saying you can't do that.

### Expected behaviour

OTC should be able to allow modifications to be just like real tibia

### Actual behaviour

It's not allowing to put buttons inside windows of other buttons.

**Comment by Codex-NG17** [comment]
Actually that isn't how the original client works, all the different sections of the layout are loaded in an un-ordered sequence within a container. The otclient behaves in a similar manner, this is how all interfaces behave unless they have float settings where they appear to be on top the ui. You will find this "float" or floating behavior within the otclient.

**Comment by andersonfaaria** [comment]
I don't think I understood your answer, could you please clarify? So changing this float option would allow me to insert the buttons inside a container?

**Comment by diath** [comment]
What's the error you're actually getting? As far as I know OTClient allows you to do anything you want with the UI in a simple way thanks to the anchor layout.

**Comment by andersonfaaria** [comment]
the error happens when you try to insert a window inside other window, it literally says "you cannot put a window inside other window" when I try to insert skill button inside the Inventory window. But I'll try other approaches and comment here my progress

**Comment by diath** [comment]
Simply use anchors to position the buttons relative to the inventory slots rather than embedding an existing window inside of the inventory window. Inside the inventory .otui file you can see how they're positioned relative to each other, you have to do the same for the combat mode buttons.

**Comment by andersonfaaria** [comment]
I have a question, hope no one take it wrong, but, with all these years being a client to tibia, why no one made the changes in order to make more alike as the official client?

I mean, why we don't have something like this:
![image](https://user-images.githubusercontent.com/8560144/32754751-510c0ae6-c8b9-11e7-98f1-98507aaa3a42.png)

**Comment by edubart** [comment]
@andersonfaaria otclient was never mean't to copy tibia client, but to be a customizable client that can connect to otservs, so its interface was already made very customized as an example
