### ISSUE TITLE
Messed up mapmark icons

### ISSUE THREAD

**Issue by andersonfaaria** [edubart/otclient#895]
At least for newest versions of TFS, the mapmarks are all wrong
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Insert mapmarks by script into your minimap
2. Realize they are with wrong id

### Expected behaviour
        registerEnum(MAPMARK_TICK) = 0
	registerEnum(MAPMARK_QUESTION) =1
	registerEnum(MAPMARK_EXCLAMATION) = 2
	registerEnum(MAPMARK_STAR) = 3
	registerEnum(MAPMARK_CROSS) = 4
	registerEnum(MAPMARK_TEMPLE) = 5
	registerEnum(MAPMARK_KISS) = 6
	registerEnum(MAPMARK_SHOVEL) = 10
	registerEnum(MAPMARK_SWORD) = 11
	registerEnum(MAPMARK_FLAG) = 12
	registerEnum(MAPMARK_LOCK) = 13
	registerEnum(MAPMARK_BAG) = 14
	registerEnum(MAPMARK_SKULL) = 15
	registerEnum(MAPMARK_DOLLAR) =  16
	registerEnum(MAPMARK_REDNORTH) = 7
	registerEnum(MAPMARK_REDSOUTH) = 17
	registerEnum(MAPMARK_REDEAST) = 18
	registerEnum(MAPMARK_REDWEST) = 8
	registerEnum(MAPMARK_GREENNORTH) = 9
	registerEnum(MAPMARK_GREENSOUTH) = 19
### Actual behaviour
https://github.com/edubart/otclient/tree/master/data/images/game/minimap
Nothing like this

### Environment

Using latest rev of otc along with 10.76 version of tfs

**Comment by iryont** [comment]
Can this issue be replicated by anyone else?
