### ISSUE TITLE
Problem Compile

### ISSUE THREAD

**Issue by stayxtru3** [edubart/otclient#897]
Hi everyone, I have a problem to compile, when it arrives at the end this message appears

1>..\src\framework\stdext\time.cpp(32): error C2039: 'time': is not a member of 'std'
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\thread(28): note: see declaration of 'std'
1>..\src\framework\stdext\time.cpp(32): error C2660: 'stdext::time': function does not take 1 arguments

**Comment by edubart** [comment]
Should be fixed in https://github.com/edubart/otclient/commit/2095951e07a13305ad3b62273044b3abe8372bd6
