### ISSUE TITLE
Lacking an easy way to compile Lua code and hidden configuration folders

### ISSUE THREAD

**Issue by andersonfaaria** [edubart/otclient#899]
Is too dangerous to have critical files wandering around in the folders.
Not everything is checked by the back-end (tfs) and being allowed to edit such things so easily by just opening the files is way too risky.
I understand many server have encountered a way to hidden or protect this files but since none of them proposed a solution I'm raising this issue to at least keep track of what me (or others) should do.

### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Compile OTC
2. The folders (specially modules) should be compiled together  to avoid people accessing and editing files that tell the client how to act.

### Expected behaviour

In any game client, the files that tell the client how to control shouldn't be so easily accessed to the common player.

### Actual behaviour

The files are one folder away from being edited unless you pass all the functions to src.

**Comment by JSkalskiSBG** [comment]
1. In every game client files which tell it 'how to work' are easy to access.
You may see some weird extensions of files, but most of them you can open in 7zip as they are just zip/7z/tar archives.
Just checked CS:GO: most of scripts are .txt files with plain text!
You can't modify CS:GO client, because it communicates with anti-bot servers when you run/play game and validate checksums of files. If you modify anything, you will get ban, but it's not possible to force people to not modify clients.

2. Compilation takes too much time. We load LUA and UI from files, because we can edit it and restart client in seconds.
Full compilation takes 50 seconds on my PC. It would take even more with LUA and other files. Imagine that you want to set proper margin for some menu items and add +2px every compilation until you make it fit window size.

3. If you release 'your' method of packing (compiling LUA?) files, people will easily understand how it works and unpack client. Only way to stop them is to use 'your' method on your server only. Then there will be less people interested in breaking it's code and there will be no 'source' how you implemented your anti-hack feature.
-----------------------------------
In my client I 'XORed' all files with some short key and added in C++ array with all files checksums - it required compilation of OTC to make smallest change in LUA/OTUI (before release, of course I had 'dev' mode).
It took players 5 weeks to find out that it's just XOR and read files content, but they did never modify them as there were 3-5 places in C++ where it checked SHA1 file sums (sums in sources were also XORed).
XORed OTClient and PHP to generate XORed LUA files:
https://otland.net/threads/how-to-encrypt-client-files-just-tips-not-full-working-code.235838/
My client files were protected, they could not add 'CandyBot' to my OTC.
Of course they wrote classic bots that run in second 'process' and send some actions like 'cast spell' when HP go under X.

**Comment by Felipe21** [comment]
> 1. In every game client files which tell it 'how to work' are easy to access.
>    You may see some weird extensions of files, but most of them you can open in 7zip as they are just zip/7z/tar archives.
>    Just checked CS:GO: most of scripts are .txt files with plain text!
>    You can't modify CS:GO client, because it communicates with anti-bot servers when you run/play game and validate checksums of files. If you modify anything, you will get ban, but it's not possible to force people to not modify clients.
> 2. Compilation takes too much time. We load LUA and UI from files, because we can edit it and restart client in seconds.
>    Full compilation takes 50 seconds on my PC. It would take even more with LUA and other files. Imagine that you want to set proper margin for some menu items and add +2px every compilation until you make it fit window size.
> 3. If you release 'your' method of packing (compiling LUA?) files, people will easily understand how it works and unpack client. Only way to stop them is to use 'your' method on your server only. Then there will be less people interested in breaking it's code and there will be no 'source' how you implemented your anti-hack feature.
> 
> In my client I 'XORed' all files with some short key and added in C++ array with all files checksums - it required compilation of OTC to make smallest change in LUA/OTUI (before release, of course I had 'dev' mode).
> It took players 5 weeks to find out that it's just XOR and read files content, but they did never modify them as there were 3-5 places in C++ where it checked SHA1 file sums (sums in sources were also XORed).
> XORed OTClient and PHP to generate XORed LUA files:
> https://otland.net/threads/how-to-encrypt-client-files-just-tips-not-full-working-code.235838/
> My client files were protected, they could not add 'CandyBot' to my OTC.
> Of course they wrote classic bots that run in second 'process' and send some actions like 'cast spell' when HP go under X.

Man im having problem to get this working can you help me ? the string generated inside the txts files its so big and the compiler wont let me compile
relicaria
#7824
cipsoftstinks at oltand

**Comment by peonso** [comment]
It's a design choice from @edubart 

https://otland.net/threads/modules.176267/page-2#post-1729785

> Otclient is an opensource project, it's goal for the project to get every developer or even players that uses it helping out the project, with contribution from everyone we can achieve a great client for everyone, not just for you, this kind of thought is too selfish. The fact you want to take a whole project made by hours of work from other people and the first thing you think is to lock down all scripts to hide any minor change is kinda rude and pointless, you would be hiding 99% of our open source work which is already out there. Wanting to have just your client to be better than the others in reality would just give more work for you, we gave an amazing client for free and it's fair to deserve something back from you and the community, what we want is contributions and you can do these in two ways, directly in our codebase or by customizing the client for your server while the changes is visible then the main project could benefit from these changes. So the fact that you can't hide the code is a good thing for this project goal, we would like to keep that way so we discourage any change or help that could lock down the otclient scripts. I am not saying that you can't, just saying this is "forbidden" for us, including in this forum.

> Copying just the client is not the same of copying your game, what makes your game is the stuff behind, the server. The client is just an interface to a game, what matters is behind.

>Player messing with the client is a good thing, they can improve your game for you, thus less work for you. More than that they will share improvements with each other and more the players of your game will be happier. Take as example WoW, the client core is surely not opensource, but there are tons of modules to help ingame and change the game interface, players care about that alot, it's hard to find a real wow player that doesn't use addons, which are made in lua too and this is a not a concidence, the idea of players creating modules in otclient for the game was taken from WoW.

> If you insist in this idea please do not ask us or on this forum, you are alone on this. Even if you try alone, there will always be a way to break down and get the scripts, would be a work in vain.

**Comment by andersonfaaria** [comment]
this design choice is pretty failed since every ot that is successfully using OTC today have created a way to make the client compiled. You can't simply put effort to fix every door an open client will create to screw your server source. One simple example is that you can change the modules in OTC to spam packets in server and crash it in a simpler way than using packet editors.

**Comment by okk3** [comment]
The design choice is pretty much the best one out there for an open source project, kudos to edubart. You cannot expect an open source project to be released with a safe and open encryption method everyone can use, those ones can never be together, once you know how something works you can reverse it. Now about the sentence about spamming packets: Packets should be handled by the server, how you do that has and should have nothing to do with the client itself.

Best Wishes,
Okke

**Comment by andersonfaaria** [comment]
"You cannot expect an open source project to be released with a safe and open encryption method everyone can use, those ones can never be together, once you know how something works you can reverse it."
This is how you show everyone you clearly don't know what you're talking about in just a single phrase.
People from OpenTibia community still have to understand that encryption is not about just sha1 and md5, there's plenty options of good encryption methods out there (in fact, all the trustworthy encryptions are open).

**Comment by iryont** [comment]
As @peonso already said - it's a design choice. If you don't like it you are free to change it on your own.

**Comment by okk3** [comment]
Thanks for closing this, Iryont.

@andersonfaaria even without knowing the complete encryption methods of most servers it's fairly easy 
 to backward-engineer their security by just setting breakpoints and watching assembly code once the data's been fed to the program. You then get the buffer length from the memory and export it to your needs, nothing left to be said, you're just lazy to figure out on how to encrypt your shit.
