### ISSUE TITLE
Huge FPS Issues

### ISSUE THREAD

**Issue by andersonfaaria** [edubart/otclient#900]
I'm copying the text of edubart itself from this link https://otland.net/threads/otclient-graphics-discussion-anyone-out-there-more-knowledgeable-than-me.244015/
1. Drawing Less Tiles
The current game map rendering architecture of otclient draws 18*14 = 252 tiles into a framebuffer, however only 15*11 = 165 tiles are visible on screen, so there is a great room for improvement here, 87 extra tiles are being drawn that are not visible, meaning that we could draw ~35% less. But there is a reason for it, 1 row at the top, 2 row at the bottom, 1 column at the left, 2 columns at the right of tiles first are drawn because when you walk you need to see where are you going at, but only when walking you need to see those extra tiles, they are discardable when you are not moving, even more depending on the direction of the walk you need to drawn only a row or a column, nevertheless otclient drawn all these extra rows and columns simple because nobody optimized that yet. Moreover we can't simple discard the bottom/right rows/columns without thinking the 64x64 sprites (trees, creatures 2x2). Therefore an algorithm that could discard those rows/columns of tiles and drawn them only when needed would greatly improve performance.

2. Drawing Even Less Tiles
There is more room for performance improvement, there a function in the map called isCompletelyCovered(), it's basically a function to check if a tile is being completely covered by another tile (meaning that we won't need to draw this covered tile). This function is working in average, however it's not smart enough, there are cases that is simple misses, and it doesn't even take the tiles dimensions into account.

3. Drawing creatures are not the problem
Many here saw that there is a great performance drop when drawing many creatures into the screen, indeed it really happens, however the main cause are not really creatures. The first problem is text drawing for creatures, it needs an algorithm with better caching, everytime a creature moves its name moves too and the engine needs to recalculate all the text glyphs positions, this could be improved by caching the text coords into a vertex array and just translating the vertex array instead of recalculating all again, in fact any moving text in otclient will consume more CPU, the greater the text the more you generally don't notice this because the UI text are static. The second cause is the battle list, which have some algorithms that work poorly when dealing with huge number of creatures. If you hide the creatures name and disable the battle module you will see that the FPS doesn't drop that much with many creatures.

4. Lights doesn't have the best implementation
As some noted the lights are drawn as big bubbles, meaning more lights more bubbles to draw, the bigger the light the bigger the bubble. When you have many lights the FPS will decrease a lot. This was not how I originally intended do implement lights, this algorithm was first introduced by @tarjei who sent me his idea and patch by email, in conjunction with him I adapted the algorithm to otclient, because how cool? We had lights working. However years passed and the algorithm still the same, it works. In a better world the lightning system would use vertex lightning, this would split the final drawn game map framebuffer into squares and each corner of the squares would have a color value associated with the intensity/color of light at the corner, then we would draw the framebuffer in a batch of squares with lightning colors associated with each square. This method would not decrease FPS even with huge amount of lights. Other idea would be to make per pixel lightning, for that using shaders, however would need a recent graphics card.

5. Reduce Texture Binding
As many of you was discussing, this would improved FPS. All sprites are loaded into textures, each time the client draws a sprite on the map it needs to bind the associated texture to that sprite, each binding downgrades the performance. In a perfect world if the whole game map could be drawn without texture bindings switches, even better, in a single batch, there would be a great increase in the FPS. But how to do that? This can be done with a technique called texture atlas, where all current visible and recent sprites are maintained in a few huge textures, thus much less texture switching would be needed, this would need a great refactor in how sprites are handled in otclient.

NOTE: I have ordered those insights in order of difficulty to implement in my opnion.

### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [x] This issue is reproducible without changes to the code in this repository

**Comment by edubart** [comment]
I will leave a note here listing that issues in order of difficulty and performance improvement for those who is willing to try to work on that.

In order of performance improvement: 4,3,1,2,5
In order of difficulty to implement: 3,1,2,4,5 (most difficult)

And I don't think 5 is really needed, that would be huge rework effort for small gain.

**Comment by JSkalskiSBG** [comment]
**Problem 3:**

Try to **reduce number of interface frames**.
Setting it to 'max' reduced FPS from 2200 to 300 with 13 creatures on battle, with 4 creatures I had around 1000 fps.
With closed battle it reduced FPS from 2500 to 2000.

Tested on i7-8700k with GF 1050.
Of course on laptop it would reduce playable 120 fps to unplayable 20 fps.

Test result:
- battle 'on/off' changes 2500 -> 2200 with 60 FPS on interface
- battle 'on/off' changes 2000 -> 300 with 'max' FPS on interface
- **battle 'on'** with 13 creatures **increase CPU usage 3 times** (with frame limit 60, without limit CPU goes 100% all time)

**Fix:**
Remove 'max' option from Options UI (people think 'its just menu' and set it 'max' probably).

**Fix 2:**
Create some simplier battle module with option on/off in menu. People with baaad laptops can change to 'simple text battle window'.

**Fix 3:**
Rewrite whole drawing system to cache texts textures - if you know how to prove, that thing that decrease FPS is exactly text on battle window.

**Comment by JSkalskiSBG** [comment]
**Problem 1:**
1. If anyone decide to implement it, remember that not every OTClient renders same screen area. In OTClient you can zoom out/zoom in and view more/less tiles.
2. Remember that you reduce number of textures to draw, but you should not reduce number of light sources. Light can be visible even when it's few tiles from 'view area' .

**Comment by andersonfaaria** [comment]
I was talking with some guys at otland and one of them gave me a code from a sprite batcher that could be adapted to otc but still I was unable to do so, if anyone wants to help me in this task, I would gladly share the code and the instructions.

**Comment by andersonfaaria** [comment]
@GustavoBlaze add me on fb: fb.com/andercfaria

we can work together and then make the pr to this repo

**Comment by danilopucci** [comment]
@andersonfaaria when you said here about the drawing lights, where that snippet code would fits in?

**Comment by andersonfaaria** [comment]
hi @danilopucci, that you would have to ask @GustavoBlaze. I kinda quit otc development because I got stuck in several things I was unable to resolve. Today I'm mainly focused in fixing tfs first then I would go back and see if it's worth more to go and try OTC learning and development or OTU (the unity version)
