### ISSUE TITLE
New Bar Tibia 11

### ISSUE THREAD

**Issue by Tekadon58** [edubart/otclient#923]
New OTC lifebands based on Tibia 11
I can not add to the folder so I could add it for myself, I'm making these bars available since they are the Archs of Tibia 11

![hpbar_empty - copia](https://user-images.githubusercontent.com/23642470/33464038-35216fe2-d61f-11e7-9a3b-8eceeb58e2d0.png)
![hpbar_empty](https://user-images.githubusercontent.com/23642470/33464039-353eb8a4-d61f-11e7-8f3a-2979560121e3.png)
![hpbar_full - copia](https://user-images.githubusercontent.com/23642470/33464040-355b1936-d61f-11e7-8581-677f1b55fd9e.png)
![hpbar_full](https://user-images.githubusercontent.com/23642470/33464041-3576dc3e-d61f-11e7-8797-5f5d9364f341.png)
![kibar_empty - copia](https://user-images.githubusercontent.com/23642470/33464042-3592bb5c-d61f-11e7-8040-9f60aba7ef75.png)
![kibar_empty](https://user-images.githubusercontent.com/23642470/33464043-35ae935e-d61f-11e7-9078-7f8cdb26b86f.png)
![kibar_full](https://user-images.githubusercontent.com/23642470/33464044-35cda49c-d61f-11e7-9573-590f93f302ea.png)

**Comment by peonso** [comment]
https://github.com/EgzoT/-OTClient-Mod-health_and_mana_circle
