### ISSUE TITLE
OTClient Error

### ISSUE THREAD

**Issue by Tekadon58** [edubart/otclient#924]
I compiled the OTC it works normal but after a while it has presented an error trying to open the error resolves if I compile again.

"otclient.exe" (Win32): Carregado "C:\Users\Anderson\Desktop\otclient-master\otclient.exe". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\ntdll.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\kernel32.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\KernelBase.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Users\Anderson\Desktop\otclient-master\glew32.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\opengl32.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\msvcrt.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\advapi32.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\sechost.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\rpcrt4.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\sspicli.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\cryptbase.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\gdi32.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\user32.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\lpk.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\usp10.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\glu32.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\ddraw.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\dciman32.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\setupapi.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\cfgmgr32.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\oleaut32.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\ole32.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\devobj.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\dwmapi.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Users\Anderson\Desktop\otclient-master\zlib.dll". O módulo foi criado sem símbolos.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\vcruntime140.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\api-ms-win-crt-runtime-l1-1-0.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\ucrtbase.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\api-ms-win-core-timezone-l1-1-0.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\api-ms-win-core-file-l2-1-0.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\api-ms-win-core-localization-l1-2-0.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\api-ms-win-core-synch-l1-2-0.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\api-ms-win-core-processthreads-l1-1-1.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\api-ms-win-core-file-l1-2-0.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\api-ms-win-crt-string-l1-1-0.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\api-ms-win-crt-heap-l1-1-0.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\api-ms-win-crt-stdio-l1-1-0.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\api-ms-win-crt-convert-l1-1-0.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\MinGW\bin\OpenAL32.dll". O módulo foi criado sem símbolos.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\shell32.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\shlwapi.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\winmm.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\dbghelp.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\ws2_32.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\nsi.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\mswsock.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\api-ms-win-crt-locale-l1-1-0.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\api-ms-win-crt-math-l1-1-0.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\api-ms-win-crt-filesystem-l1-1-0.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\api-ms-win-crt-time-l1-1-0.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\api-ms-win-crt-utility-l1-1-0.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\api-ms-win-crt-environment-l1-1-0.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\api-ms-win-crt-conio-l1-1-0.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\api-ms-win-crt-multibyte-l1-1-0.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\imm32.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\msctf.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Program Files\Diebold\Warsaw\wslbscr32.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Program Files\Diebold\Warsaw\wslbscrwh32.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\userenv.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\profapi.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\uxtheme.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\ntmarta.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\Wldap32.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\nvoglv32.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\wtsapi32.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\version.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\wintrust.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\crypt32.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\msasn1.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\nvspcap.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\winsta.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\dsound.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\powrprof.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\clbcatq.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\MMDevAPI.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\propsys.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\AudioSes.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\avrt.dll". Não é possível localizar ou abrir o arquivo PDB.
"otclient.exe" (Win32): Carregado "C:\Windows\SysWOW64\WSHTCPIP.DLL". Não é possível localizar ou abrir o arquivo PDB.
O thread 0x1418 foi fechado com o código 0 (0x0).
O thread 0x61c foi fechado com o código 0 (0x0).
O thread 0x1684 foi fechado com o código 3 (0x3).
O thread 0x1b0c foi fechado com o código 3 (0x3).
O thread 0x1b84 foi fechado com o código 3 (0x3).
O thread 0x116c foi fechado com o código 3 (0x3).
O thread 0x18b0 foi fechado com o código 3 (0x3).
O thread 0x1b1c foi fechado com o código 3 (0x3).
O thread 0x1a40 foi fechado com o código 3 (0x3).
O thread 0x15f0 foi fechado com o código 3 (0x3).
O thread 0x1804 foi fechado com o código 3 (0x3).
O thread 0x1450 foi fechado com o código 3 (0x3).
O thread 0x137c foi fechado com o código 3 (0x3).
O thread 0x181c foi fechado com o código 3 (0x3).
O thread 0x18ac foi fechado com o código 3 (0x3).
O thread 0x1708 foi fechado com o código 3 (0x3).
O thread 0x1498 foi fechado com o código 3 (0x3).
O thread 0x161c foi fechado com o código 3 (0x3).
O programa "[5012] otclient.exe" foi fechado com o código 3 (0x3).

**Comment by Tekadon58** [comment]
I debugged at VSC

**Comment by matheusalbino** [comment]
I have the same problem when build client, and when will execute my client doesn't show character list and close client
