### ISSUE TITLE
Save Settings

### ISSUE THREAD

**Issue by Exedenes** [edubart/otclient#927]
~ ❯❯❯ otclient
GPU Mesa DRI Intel(R) Bay Trail 
OpenGL 3.0 Mesa 17.2.6
ERROR: Unable to save log to '/usr/bin/../share/otclient/otclient.log'
== application started at Dec 14 2017 17:56:05
OTClient 0.6.6 rev 2627 (v0.6.6-222-g47766685) built on Dec  8 2017 for arch x64
ERROR: Unable to create write directory '/home/bastard/.otclient': unsupported
Startup done :]

im using arch linux and the directory exists

**Comment by vamo89** [comment]
The problem is that '/home/bastard/.otclient' is a file and not a folder.
You can fix this with:
`rm /home/bastard/.otclient && mkdir /home/bastard/.otclient`
but we need some way to fix this for good.

**Comment by Exedenes** [comment]
omg thank you
