### ISSUE TITLE
[10.98] Number of premium days left is always 256

### ISSUE THREAD

**Issue by DSpeichert** [edubart/otclient#933]
### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/otclient.494/ for support)
- [ ] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Get a premium account with limited premium days left
2. Enter username/password
3. Look at the number of premium days left below character list

### Expected behaviour
It should show correct number of premium days left (1, 2, 3...) like the native client does.

### Actual behaviour
OTClient is showing 256 as number of premium days left.

### Environment
* Protocol 10.98
* Tested with TFS 1.2
* Compared to native client on the same server and same account - server is sending days left correctly

**Comment by EgzoT** [comment]
Probably packet reading is good:
[protocollogin.lua #L243](https://github.com/edubart/otclient/blob/a6a50fa1624f38fc173f79abdfcafcb29c42c354/modules/gamelib/protocollogin.lua#L243)

Showing too:
[characterlist.lua #L256-L270](https://github.com/edubart/otclient/blob/af92792d4a0348eaa1811979158cfe4c09eca89d/modules/client_entergame/characterlist.lua#L256-L270)

Add under line [protocollogin.lua #L243](https://github.com/edubart/otclient/blob/a6a50fa1624f38fc173f79abdfcafcb29c42c354/modules/gamelib/protocollogin.lua#L243) function who print numer of premium days to console, and we will know where is error.

**Comment by diath** [comment]
@EgzoT 
The problem is that the newer protocol has additional bytes that OTC is not parsing:
1 byte - account status (0 - Ok, 1 - Frozen, 2 - Suspended)
1 byte - premium status (0 - Free, 1 - Premium)
4 bytes - premium end timestamp

I'll look into it later.
