### ISSUE TITLE
Erro OTcliente

### ISSUE THREAD

**Issue by Qwizer** [edubart/otclient#935]
ERROR: lua function callback failed: LUA ERROR:
/client_options/options.lua:231: attempt to call method 'setDrawManaBar' (a nil value)
stack traceback:
    [C]: in function 'setDrawManaBar'
    /client_options/options.lua:231: in function 'setOption'
    /client_options/options.lua:135: in function 'setup'
    /client_options/options.lua:118: in function </client_options/options.lua:118>

**Comment by diath** [comment]
Did you compile the newest source? It looks like you're using the newest modules with an old binary.

**Comment by EgzoT** [comment]
Yes, he did it. The same errors.

@Qwizer 
You must compile lastest source or download lastest version.

Issue to close.
