### ISSUE TITLE
otclient crash

### ISSUE THREAD

**Issue by profitclix25** [edubart/otclient#936]
== application crashed
app name: OTClient
app version: 0.6.3
build compiler: msvc12
build date: Jan 10 2018
build type: RelWithDebInfo
build revision: 0 (devel)
crash date: Jan 10 2018 10:38:33
exception: Access violation (0xc0000005)
exception address: 0x003d0445
  backtrace:
    0: C:\Users\Desktop\otclient-master\otclient.exe(std::basic_istream<char,std::char_traits<char> >::read+0x35) [0x00000000003D0445]
    1: C:\Users\Desktop\otclient-master\otclient.exe(load_apng+0x114) [0x00000000005C9084]
    2: C:\Users\Desktop\otclient-master\otclient.exe(operator new+0x2c) [0x000000000054D267]

I cant even start otc i get crash on startup. using last source with data/module files. I dont change anything, using visual 2017 the project is seted on studio 2015(v140) and log from compiler
1> win32window.cpp
1> C: \ Program Files (x86) \ Windows Kits \ 8.1 \ Include \ um \ imagehlp.h (1873): warning C4091: "typedef": ignored to the left of "" while no variable declaration (compiling the source file. . \ src \ framework \ platform \ win32crashhandler.cpp)
1> C: \ Program Files (x86) \ Windows Kits \ 8.1 \ Include \ um \ imagehlp.h (3519): warning C4091: "typedef": ignored to the left of "" while no variable declaration (compiling the source file. . \ src \ framework \ platform \ win32crashhandler.cpp)
1> combinedsoundsource.cpp
1> oggsoundfile.cpp
1> soundbuffer.cpp
1> soundchannel.cpp
1> soundfile.cpp
1> soundmanager.cpp
1> soundsource.cpp
1> streamsoundsource.cpp
1> demangle.cpp
1> math.cpp
1> net.cpp
1> string.cpp
1> time.cpp
1> C: \ Program Files (x86) \ Windows Kits \ 8.1 \ Include \ um \ dbghelp.h (1544): warning C4091: "typedef": ignored to the left of "" while no variable declaration (compiling the source file. . \ src \ framework \ stdext \ demangle.cpp)
1> C: \ Program Files (x86) \ Windows Kits \ 8.1 \ Include \ um \ dbghelp.h (3190): warning C4091: "typedef": ignored to the left of "" while no variable declaration (compiling the source file. . \ src \ framework \ stdext \ demangle.cpp)
1> uianchorlayout.cpp
1> uiboxlayout.cpp
1> uigridlayout.cpp
1> uihorizontallayout.cpp
1> uilayout.cpp
1> uimanager.cpp
1> uiparticles.cpp
1> uitextedit.cpp
1> uitranslator.cpp
1> uiverticallayout.cpp
1> uiwidget.cpp
1> uiwidgetbasestyle.cpp
1> uiwidgetimage.cpp
1> uiwidgettext.cpp
1> color.cpp
1> crypt.cpp
1> tinystr.cpp
1> tinyxml.cpp
1> tinyxmlerror.cpp
1> tinyxmlparser.cpp
1> main.cpp
1> Creation of C: \ Users \  Desktop \ otclient-master \ vc14 \ ../ otclient.lib libraries and object C: \ Users \ Desktop \ otclient-master \ vc14 \ ../ otclient.exp
1> Code generation is in progress
1> Code generation completed
1> libeay32.lib (cryptlib.obj): warning LNK4099: PDB file "lib.pdb" not found with "libeay32.lib (cryptlib.obj)" or in "C: \ Users \  Desktop \ otclient-" master \ lib.pdb "; consolidated object without debugging information
1> libeay32.lib (mem.obj): warning LNK4099: PDB file "lib.pdb" not found with "libeay32.lib (mem.obj)" or in "C: \ Users \ Desktop \ otclient-" master \ lib.pdb "; consolidated object without debugging information
1> libeay32.lib (mem_dbg.obj): warning LNK4099: PDB file not found "l

there is no problem with visual if the file was created right?

**Comment by diath** [comment]
Could you run otc through a debugger and post the stack frames before load_apng was called along with the parameters?

**Comment by profitclix25** [comment]
I think i cant get stack frames becouse if i set project on debug it ask for compile first but when i try i get some critical errors and it dont start debug. Im release and debug with win32 on x64 i get other errors and cant even release 
Validity Code Description Project File Row Skip status
Error LNK2019 unrecognized external _uncompress @ 16 symbol recalled in the __catch $? Function. LoadImage @ Minimap @@ QAE_NABV? $ Basic_string @ DU? $ Char_traits @ D @ std @@ V? $ Allocator @ D @ 2 @@ std @@ ABVPosition @@ M @ Z $ 0 otclient D: \ otclient-master \ vc14 \ minimap.obj 1
Warning C4091 "typedef": ignored to the left of "" while no variable declaration (compiling the source file .. \ src \ framework \ platform \ win32crashhandler.cpp) otclient C: \ Program Files (x86) \ Windows Kits \ 8.1 \ Include \ m \ imagehlp.h 1873
Warning C4091 "typedef": ignored to the left of "" while no variable declaration (compiling the source file .. \ src \ framework \ platform \ win32crashhandler.cpp) otclient C: \ Program Files (x86) \ Windows Kits \ 8.1 \ Include \ m \ imagehlp.h 3519
Warning C4091 "typedef": ignored to the left of "" while no variable declaration (compiling the source file .. \ src \ framework \ stdext \ demangle.cpp) otclient C: \ Program Files (x86) \ Windows Kits \ 8.1 \ Include \ m \ dbghelp.h 1544
Warning C4091 "typedef": ignored to the left of "" while no variable declaration (compiling the source file .. \ src \ framework \ stdext \ demangle.cpp) otclient C: \ Program Files (x86) \ Windows Kits \ 8.1 \ Include \ m \ dbghelp.h 3190
Warning LNK4098 The default library "MSVCRT" conflicts with other libraries; use the / NODEFAULTLIB option: otclient library D: \ otclient-master \ vc14 \ LINK 1
Error LNK2019 unrecognized external _compress2 @ 20 symbol recalled in function __catch $? LoadOtmm @ Minimap @@ QAE_NABV? $ Basic_string @ DU? $ Char_traits @ D @ std @@ V? $ Allocator @ D @ 2 @@ std @@@ Z $ 0 otclient D: \ otclient-master \ vc14 \ minimap.obj 1
Error LNK2019 unrecognized external _compressBound @ 4 referenced in __catch $? FunctionImage @ Minimap @@ QAE_NABV? $ Basic_string @ DU? $ Char_traits @ D @ std @@ V? $ Allocator @ D @ 2 @@ std @@ ABVPosition @@ M @ Z $ 0 otclient D: \ otclient-master \ vc14 \ minimap.obj 1
Error LNK2019 unrecognized external symbol _deflate @ 8 invoked in the function "void __cdecl save_png (class std :: basic_stringstream <char, struct std :: char_traits <char>, class std :: allocator <char>> &, unsigned int, unsigned int, int, unsigned char *) "(? save_png @@ YAXAAV? $ basic_stringstream @ DU? $ char_traits @ D @ std @@ V? $ allocator @ D @ 2 @@ std @@ IIHPAE @ Z) otclient D: \ otclient- master \ vc14 \ apngloader.obj 1
Error LNK2019 unrecognized external symbol _deflateEnd @ 4 invoked in the function "void __cdecl save_png (class std :: basic_stringstream <char, struct std :: char_traits <char>, class std :: allocator <char>> &, unsigned int, unsigned int, int, unsigned char *) "(? save_png @@ YAXAAV? $ basic_stringstream @ DU? $ char_traits @ D @ std @@ V? $ allocator @ D @ 2 @@ std @@ IIHPAE @ Z) otclient D: \ otclient- master \ vc14 \ apngloader.obj 1
Error LNK2019 unrecognized external symbol _inflate @ 8 invoked in the function "void __cdecl unpack (struct z_stream_s &, unsigned char *, unsigned int, unsigned char *, unsigned int, unsigned int, unsigned int, unsigned char)" (? Unpack @@ YAXAAUz_stream_s @@ @ PAEI1IIIE Z) otclient D: \ otclient-master \ vc14 \ apngloader.obj 1
Error LNK2019 unrecognized external _inflateEnd @ 4 symbol recalled in the function "int __cdecl load_apng (class std :: basic_stringstream <char, struct std :: char_traits <char>, class std :: allocator <char>> &, struct apng_data *)" ( ? load_apng @@ YAHAAV? basic_stringstream $ @ DU? $ char_traits @ D @ std @@ V? $ allocator @ D @ 2 @@ std @@ @@@ PAUapng_data Z) otclient D: \ otclient-master \ vc14 \ apngloader. vol 1
Error LNK2019 unrecognized external symbol _deflateReset @ 4 recalled in the function "void __cdecl save_png (class std :: basic_stringstream <char, struct std :: char_traits <char>, class std :: allocator <char>> &, unsigned int, unsigned int, int, unsigned char *) "(? save_png @@ YAXAAV? $ basic_stringstream @ DU? $ char_traits @ D @ std @@ V? $ allocator @ D @ 2 @@ std @@ IIHPAE @ Z) otclient D: \ otclient- master \ vc14 \ apngloader.obj 1
Error LNK2019 unrecognized external symbol _inflateReset @ 4 invoked in the function "void __cdecl unpack (struct z_stream_s &, unsigned char *, unsigned int, unsigned char *, unsigned int, unsigned int, unsigned int, unsigned char)" (? Unpack @@ YAXAAUz_stream_s @@ @ PAEI1IIIE Z) otclient D: \ otclient-master \ vc14 \ apngloader.obj 1
Error LNK2019 unrecognized external symbol _crc32 @ 12 invoked in the function "void __cdecl write_chunk (class std :: basic_ostream <char, struct std :: char_traits <char>> &, char const *, unsigned char *, unsigned int)" (? Write_chunk @@ YAXAAV? basic_ostream $ @ DU? $ char_traits @ D @ std @@@ @@ std PBDPAEI @ Z) otclient D: \ otclient-master \ vc14 \ apngloader.obj 1
Error LNK2019 unrecognized external symbol _inflateInit_ @ 12 invoked in the function "int __cdecl load_apng (class std :: basic_stringstream <char, struct std :: char_traits <char>, class std :: allocator <char>> &, struct apng_data *)" ( ? load_apng @@ YAHAAV? basic_stringstream $ @ DU? $ char_traits @ D @ std @@ V? $ allocator @ D @ 2 @@ std @@ @@@ PAUapng_data Z) otclient D: \ otclient-master \ vc14 \ apngloader. vol 1
Error LNK2019 unrecognized external symbol _deflateInit2_ @ 32 referenced in the function "void __cdecl save_png (class std :: basic_stringstream <char, struct std :: char_traits <char>, class std :: alloca

**Comment by diath** [comment]
It looks like you're either missing the zlib library or you have one that's not compatible with your VS version.

**Comment by profitclix25** [comment]
some standalone zlib? i downloaded otclient sdk there is some zlib folder in it, should i download newest version or it wont fit? the problem is i had firtsly visual 2015 and there was same problem thout it becouse i have under update 3 so i just download version 2017 becouse i need it anyway for another project. I uinstalled 2015 and installed 2017 with all build tools for v140. You are able to link me all names of needed tools and libs mainly from visual studio?

**Comment by profitclix25** [comment]
i installed visual 2015 update 3 with all packages checked on new formated windows 7 x32 with last otc sdk libs but still same problem and i dont know why. Just found some not updated otc source with visual 2013 i guess i have to work on that
