### ISSUE TITLE
Slow effects in the invisible mode/utana vid and runes (avalanche)

### ISSUE THREAD

**Issue by igorlagoas** [edubart/otclient#941]
Hello,

I'm having problems with the speed of effects like utana vid, avalanche runes and others stuffs. 
I use OTclient 0.6.6 rev 0 (df422c0) with windows 64x.

The animations are so slowly, maybe 2x more slow that it would be. I've looking at the const.h file and changed a lot of things that i think was the problem, but couldn't solve.

The game are in OpenGL 1 and 2 with no limit of FPS.

This slow effect only occurred in OTClient, in the Tibia Client is was normal.
Look the video below:
https://www.youtube.com/watch?v=e9kFR65enz8

**Comment by lromagnoli** [comment]
This also happens with the sleep effect
https://imgur.com/a/BCLep

**Comment by Eternal-Scripts** [comment]
Try using the last rev of otclient repository.

**Comment by igorlagoas** [comment]
@Eternal-Scripts  Hello! Sorry for my ignorance, but i used that version of repository on the link in the description of Edubart's post: 

Commit df422c0
Commit date: 4th February 2017
Lastest version supported: 10.99

Have another updated? I don't know how to compile or create my own build.

Hugs.
