### ISSUE TITLE
Otc Arch Linux

### ISSUE THREAD

**Issue by Tekadon58** [edubart/otclient#943]
If I'm not mistaken I had the option to compile for Arch Linux but I'm not finding it.

**Comment by okk3** [comment]
There was an option as Edubart held a package on AUR (https://aur.archlinux.org/packages/?O=0&K=otclient), sadly it's not avaliable anymore.

Perhaps following the Ubuntu-Guide will lead you to the same results when using the right libs.

**Comment by Tekadon58** [comment]
Já consegui. 
Obrigado.

**Comment by Tekadon58** [comment]
Eu resolvi no mesmo dia. 
Baixei os pacotes de boosters e clonei o repositório

**Comment by okk3** [comment]
Translating his messages to english: 

He downloaded the missing libraries on his Arch Linux and it worked.

This issue can be now closed.

Regards
Okke
