### ISSUE TITLE
MinGW not Compatible

### ISSUE THREAD

**Issue by EmersonHenriique** [edubart/otclient#945]
I'm trying to compile Otclient using CodeBlocks and I'm constantly having problems with MinGW will it be possible to make available some MinGW compatible with that version of the client?

**Comment by okk3** [comment]
Hello EmersonHenriique,

please supply us with a little bit more information on that (Error messages or whatsoever), so we can help you further.

Regards
Okke

**Comment by EmersonHenriique** [comment]
I am trying to compile the latest version using codeblock, in the tutorial it is vague the procedures, asks that we download Cmake and MinGW and provides download of some libs, Cmake generates the file with no problems at all.
`The C compiler identification is GNU 4.8.1
The CXX compiler identification is GNU 4.8.1
Check for working C compiler: C:/MinGW/bin/gcc.exe
Check for working C compiler: C:/MinGW/bin/gcc.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: C:/MinGW/bin/g++.exe
Check for working CXX compiler: C:/MinGW/bin/g++.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Performing Test COMPILER_KNOWS_CXX11
Performing Test COMPILER_KNOWS_CXX11 - Success
Performing Test COMPILER_KNOWS_STDLIB
Performing Test COMPILER_KNOWS_STDLIB - Failed
Link to static libraries: ON
Build type: RelWithDebInfo
Build commit: devel
Build revision: 0
Looking for pthread.h
Looking for pthread.h - not found
Found Threads: TRUE  
Boost version: 1.64.0
Found the following Boost libraries:
  system
  thread
  filesystem
  chrono
  date_time
Found Lua: C:/MinGW/lib/liblua51.a  
LuaJIT: OFF
Found PHYSFS: C:/MinGW/lib/libphysfs.a  
Found OPENSSL: C:/MinGW/lib/libssl.a;C:/MinGW/lib/libcrypto.a  
Found ZLIB: C:/MinGW/lib/libz.a  
Debug information: ON
Crash handler: ON
Found OpenGL: opengl32  
Found GLEW: C:/MinGW/lib/libglew32.a  
OpenGL ES: OFF
Windows console: OFF
Found OPENAL: C:/MinGW/lib/libOpenAL32.a  
Found VORBISFILE: C:/MinGW/lib/libvorbisfile.a  
Found VORBIS: C:/MinGW/lib/libvorbis.a  
Found OGG: C:/MinGW/lib/libogg.a  
Bot protection: ON
Use precompiled header: OFF
Configuring done
Generating done`
Now that it arrives at CodeBlock, it starts giving libs errors.
`||=== Build: all in otclient (compiler: GNU GCC Compiler) ===|
c:\mingw\include\math.h||In function 'float hypotf(float, float)':|
c:\mingw\include\math.h|635|error: '_hypot' was not declared in this scope|
CMakeFiles\otclient.dir\build.make|66|recipe for target 'CMakeFiles/otclient.dir/src/framework/luafunctions.cpp.obj' failed|
CMakeFiles\Makefile2|66|recipe for target 'CMakeFiles/otclient.dir/all' failed|
C:\Compile\build\Makefile|128|recipe for target 'all' failed|
||=== Build failed: 4 error(s), 0 warning(s) (0 minute(s), 32 second(s)) ===|
`

**Comment by EmersonHenriique** [comment]
@edubart @iryont @okk3

**Comment by okk3** [comment]
Just read your error messages carefully and try feeding the compiler what it wants to eat: `Looking for pthread.h - not found`...

**Comment by EmersonHenriique** [comment]
I give up nothing works :(

**Comment by jjunior89** [comment]
Same erros here, any solutions ? :(

**Comment by diath** [comment]
https://stackoverflow.com/a/29489843

**Comment by EmersonHenriique** [comment]
@diath `Looking for pthread.h Looking for pthread.h - not found`

**Comment by EmersonHenriique** [comment]
@GustavoBlaze  |undefined reference to `boost::chrono::steady_clock::now()'|
