### ISSUE TITLE
Dont work -DOPENGLES=2.0 in VS2015 (directx9)

### ISSUE THREAD

**Issue by jjunior89** [edubart/otclient#948]
Hi, i am compiling otclient in VS2015 enterprise but not is enabling directx9 in my client, 
what should I do ? dll libEGL.dll and libGLESv2.dll in same folder.

https://imgur.com/a/nUu0x
https://imgur.com/a/dQIBp

client in 7.72
last source from github
visual studio 2015 enterprise

i tested in codeblocks but have others errors on compiling in the last version of otclient
https://prnt.sc/idqvdd

**Comment by diath** [comment]
I don't know much about the hacky DX support but one obvious mistake in your screenshot is that you're trying to pass **-DOPENGLES=2.0** in the preprocessor definitions field however the prefix is only required when compiling using the cl tool, so try just **OPENGLES=2.0** instead.

**Comment by okk3** [comment]
@jjunior89 You should actually use the *OPENGL_ES=2* preprocessor, also you'll need the GLES-SDK.

Just tried it out and it worked.
