### ISSUE TITLE
Project is Dead?

### ISSUE THREAD

**Issue by JoseEduardo** [edubart/otclient#949]
The Project Died?
Will they not release more updates to continue to upgrade with as newer versions?
What do I need to upgrade to a version 11?

**Comment by EgzoT** [comment]
Previous versions was need a "bit changes", new tibia client 11 is something bigger than some changes in client because it was build from scratch in java.

What you need to upgrade it?
Knowledge and time.

**Comment by diath** [comment]
>client 11 is something bigger than some changes in client, because it was build from scratch in java.

Just to clarify, T11 is written in C++ using the Qt (and QML) library, not Java.

**Comment by JoseEduardo** [comment]
Someone would know, at least above all, what it takes to upgrade.

**Comment by EgzoT** [comment]
Try ask on Otland.net, maybe someone will help you with things needed to upgrade OTClient to support Tibia 11+.

**Comment by conde2** [comment]
In my opinion, TFS and OTclient should drift away from Tibia, and be a Engine for make MMORPGs, prioritize customization and performance instead of trying to mimic Tibia.

**Comment by CristoferMartins** [comment]
@conde2 your vision is kinda correct but we fail even to implement the "simple" game Tibia and now we should try bigger?
