### ISSUE TITLE
otclient crash！ 

### ISSUE THREAD

**Issue by ChooseOne** [edubart/otclient#955]
== application crashed
app name: OTClient
app version: 0.6.6
build compiler: gcc 5.4.0 20160609
build date: Mar 23 2018
build type: RelWithDebInfo
build revision: 0 (devel)
crash date: Mar 23 2018 11:12:15
  at rip = 0x7fdf78cad428
     rax = 0
     rbx = 0x28
     rcx = 0x7fdf78cad428
     rdx = 0x6
     rsi = 0xd3a1
     rdi = 0xd3a1
     rbp = 0x29ba970
     rsp = 0x7ffd8d1adbf8
     efl = 0x202

  backtrace:
    1: /lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38) [0x7fdf78cad428]
    2: /lib/x86_64-linux-gnu/libc.so.6(abort+0x16a) [0x7fdf78caf02a]
    3: /usr/lib/x86_64-linux-gnu/dri/vmwgfx_dri.so(+0x63b99f) [0x7fdf75a8c99f]
    4: /usr/lib/x86_64-linux-gnu/dri/vmwgfx_dri.so(+0x639629) [0x7fdf75a8a629]
    5: /usr/lib/x86_64-linux-gnu/dri/vmwgfx_dri.so(+0x64103d) [0x7fdf75a9203d]
    6: /usr/lib/x86_64-linux-gnu/dri/vmwgfx_dri.so(+0x64b1dd) [0x7fdf75a9c1dd]
    7: /usr/lib/x86_64-linux-gnu/dri/vmwgfx_dri.so(+0x64b47d) [0x7fdf75a9c47d]
    8: /usr/lib/x86_64-linux-gnu/dri/vmwgfx_dri.so(+0x64b7a0) [0x7fdf75a9c7a0]
    9: /usr/lib/x86_64-linux-gnu/dri/vmwgfx_dri.so(+0x257512) [0x7fdf756a8512]
    10: /usr/lib/x86_64-linux-gnu/dri/vmwgfx_dri.so(+0x1aa357) [0x7fdf755fb357]
    11: /usr/lib/x86_64-linux-gnu/dri/vmwgfx_dri.so(+0x20d0ed) [0x7fdf7565e0ed]
    12: /usr/lib/x86_64-linux-gnu/dri/vmwgfx_dri.so(+0x20ed10) [0x7fdf7565fd10]
    13: /usr/lib/x86_64-linux-gnu/dri/vmwgfx_dri.so(+0x199717) [0x7fdf755ea717]
    14: /usr/lib/x86_64-linux-gnu/dri/vmwgfx_dri.so(+0x19b1a0) [0x7fdf755ec1a0]
    15: ./otclient(Texture::setupPixels(int, TSize<int> const&, unsigned char*, int, bool)+0x74) [0x7e6ff2]
    16: ./otclient(Texture::uploadPixels(stdext::shared_object_ptr<Image> const&, bool, bool)+0x1fb) [0x7e75dd]
    17: ./otclient(Texture::Texture(stdext::shared_object_ptr<Image> const&, bool, bool)+0x85) [0x7e7861]
    18: ./otclient(TextureManager::loadTexture(std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >&)+0x52c) [0x7e8070]
    19: ./otclient(TextureManager::getTexture(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x412) [0x7e89d0]
    20: ./otclient(UIWidget::setImageSource(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x67) [0x81aa19]
    21: ./otclient(UIWidget::parseImageStyle(stdext::shared_object_ptr<OTMLNode> const&)+0x820) [0x81b39a]
    22: ./otclient(UIWidget::onStyleApply(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, stdext::shared_object_ptr<OTMLNode> const&)+0xf7) [0x80d31f]
    23: ./otclient(UIWidget::applyStyle(stdext::shared_object_ptr<OTMLNode> const&)+0x7c3) [0x80db81]
    24: ./otclient(UIWidget::setStyleFromNode(stdext::shared_object_ptr<OTMLNode> const&)+0x12) [0x81159a]
    25: ./otclient(UIManager::createWidgetFromOTML(stdext::shared_object_ptr<OTMLNode> const&, stdext::shared_object_ptr<UIWidget> const&)+0x2fa) [0x7f5038]
    26: ./otclient(UIManager::loadUI(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, stdext::shared_object_ptr<UIWidget> const&)+0x467) [0x7f5945]
    27: ./otclient(UIManager::displayUI(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x3e) [0x749176]
    28: ./otclient(std::_Function_handler<stdext::shared_object_ptr<UIWidget> (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), std::function<stdext::shared_object_ptr<UIWidget> (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const& const&)> luabinder::make_mem_func_singleton<stdext::shared_object_ptr<UIWidget>, UIManager, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(stdext::shared_object_ptr<UIWidget> (UIManager::*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), UIManager*)::{lambda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)#1}>::_M_invoke(std::_Any_data const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x3f) [0x74725f]
    29: ./otclient(std::_Function_handler<int (LuaInterface*), std::function<int (LuaInterface*)> luabinder::bind_fun_specializer<stdext::shared_object_ptr<UIWidget>, std::function<stdext::shared_object_ptr<UIWidget> (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>, std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >(std::function<stdext::shared_object_ptr<UIWidget> (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)> const&)::{lambda(LuaInterface*)#1}>::_M_invoke(std::_Any_data const&, LuaInterface*&&)+0x93) [0x77a459]
    30: ./otclient(LuaInterface::luaCppFunctionCallback(lua_State*)+0x71) [0x7b2b79]
    31: ./otclient() [0x980328]
    32: ./otclient() [0x989922]
    33: ./otclient() [0x98077d]
    34: ./otclient() [0x97fa7b]
    35: ./otclient() [0x9808db]
    36: ./otclient(lua_pcall+0x56) [0x97df76]
    37: ./otclient(LuaInterface::pcall(int, int, int)+0x64) [0x7af918]
    38: ./otclient(LuaInterface::safeCall(int, int)+0xa3) [0x7b12f5]
    39: ./otclient(Module::load()+0x3de) [0x7a642e]
    40: ./otclient(Module::load()+0x59f) [0x7a65ef]
    41: ./otclient(ModuleManager::ensureModuleLoaded(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x4b) [0x7a8167]
    42: ./otclient(std::_Function_handler<int (LuaInterface*), std::function<int (LuaInterface*)> luabinder::bind_fun_specializer<void, std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)>, std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >(std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)> const&)::{lambda(LuaInterface*)#1}>::_M_invoke(std::_Any_data const&, LuaInterface*&&)+0x8f) [0x772241]
    43: ./otclient(LuaInterface::luaCppFunctionCallback(lua_State*)+0x71) [0x7b2b79]
    44: ./otclient() [0x980328]
    45: ./otclient() [0x989922]
    46: ./otclient() [0x98077d]
    47: ./otclient() [0x97fa7b]
    48: ./otclient() [0x9808db]
    49: ./otclient(lua_pcall+0x56) [0x97df76]
    50: ./otclient(LuaInterface::pcall(int, int, int)+0x64) [0x7af918]
    51: ./otclient(LuaInterface::safeCall(int, int)+0xa3) [0x7b12f5]
    52: ./otclient(LuaInterface::runScript(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x23) [0x7b32f3]
    53: ./otclient(LuaInterface::safeRunScript(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x2b) [0x7b3325]
    54: ./otclient(main+0x1be) [0x943f57]

**Comment by Tekadon58** [comment]
up
