### ISSUE TITLE
BUG NpcTRADE otclient

### ISSUE THREAD

**Issue by CerberusBR** [edubart/otclient#957]
https://i.imgur.com/ZbrDp6J.png

Problem with the client in windows 10, in my case and the item revives that it costs 10000, when you can to buy it with the backpack it has a price of 20, this happens only in windows 10 and when you only have 10,000 money, when have more money it normalizes charging backpack + 10000 price!

**Comment by CerberusBR** [comment]
up

**Comment by Carelesslol** [comment]
you have configured the NPC's script correctly?

**Comment by CerberusBR** [comment]
yes. erro in windows 10 , windows 7 are perfect.

**Comment by CerberusBR** [comment]
windows 10 the client appears equal in the image the value of 20 and in windows 7, the client sees 10k + 20 price of the backpack + item
