### ISSUE TITLE
GetServerID Returns 0

### ISSUE THREAD

**Issue by tuxico** [edubart/otclient#959]
>  function onInventoryChange(player, slot, item, oldItem)
>   if slot > InventorySlotPurse then return end
> 
>   if slot == InventorySlotPurse then
>     if g_game.getFeature(GamePurseSlot) then
>       purseButton:setEnabled(item and true or false)
>     end
>     return
>   end
>   local itemWidget = inventoryPanel:getChildById('slot' .. slot)
>   if item then
>     itemWidget:setStyle('InventoryItem')
>     itemWidget:setItem(item)
>     itemWidget:setTooltip('Item Id: ' .. item:getServerId())
>   else
>     itemWidget:setStyle(InventorySlotStyles[slot])
>     itemWidget:setItem(nil)
>   end
> end

**Comment by TheSumm** [comment]
You have to use `g_things.loadOtb` to load your `.otb` to properly work with server ids on the client side.

**Comment by tuxico** [comment]
Nice!

**Comment by tuxico** [comment]
I should use g_things.loadOtb() in whereever in the script lua?

**Comment by tuxico** [comment]
ERROR: Failed to load '' (OTB file): unable to open file '/game_inventory/': Acesso negado.

**Comment by tuxico** [comment]
Done... but create massive lag on reload.
