### ISSUE TITLE
Missing DLL files

### ISSUE THREAD

**Issue by TorchwoodPL** [edubart/otclient#961]
On newest commit when I try to run compiled client I get error with missing dlls. can anybody give archive with proper libs?

**Comment by TorchwoodPL** [comment]
Now I have 0xc00007b error, can anybody tell me what is missing?

**Comment by diath** [comment]
@TorchwoodPL 
It could be a mismatch between 32-bit/64-bit otclient and 32-bit/64-bit DLL files.

**Comment by TorchwoodPL** [comment]
Yeap, that was it! Thanks!
