### ISSUE TITLE
forced player position update

### ISSUE THREAD

**Issue by 280411** [edubart/otclient#964]
➤Well, I wanted to ask for help for you, since I looked for the error and I did not find it, well I'm having this problem, the player when it walks for a while (DOES NOT TAKE ADMINS BUT ALSO PLAYERS NORMAL), the screen is all black, and the character starts to disappear, and these errors appear on the console.

`forced player position update
ERROR: no thing at pos:1054 961 5, stackpos:1
at:
    [C++]: ?getMappedThing@ProtocolGame@@QAE?AV?$shared_object_ptr@VThing@@@stdext@@ABV?$shared_object_ptr@VInputMessage@@@3@@Z
ERROR: no creature found to move
at:
    [C++]: ?parseCreatureMove@ProtocolGame@@AAEXABV?$shared_object_ptr@VInputMessage@@@stdext@@@Z`

➤this error repeats itself

 ➤PRINT
![sem titulox](https://user-images.githubusercontent.com/29734988/38972651-4ac4f6cc-4378-11e8-823e-5e8eb76cf4fd.png)

 ➤ I count on the help of all, and I wait!

**Comment by 280411** [comment]
Reply with quote

**Comment by keptsecret** [comment]
Hey, did you ever fix this? I'm facing the same problems.
