### ISSUE TITLE
[0.6.7] Summon needs to walk to appear on Battle window

### ISSUE THREAD

**Issue by CaosJunior** [edubart/otclient#968]
When I create a summon it doesn't appear on Battle window till it walks 1 SQM.
Print of Battle window when summon is created: https://imgur.com/a/F3Z7Ec3
Print of Battle window after summon walks 1 SQM: https://imgur.com/a/HGPyqtL
I'm using OTC 0.6.7 compiled with CodeBlocks on Windows 10.

**Comment by diath** [comment]
I cannot reproduce this, it must be your own modification to the client that causes the issue.

**Comment by CaosJunior** [comment]
I edited only 2 things in sources (changed color of Monster Talk and number of lines above player's head when he speaks), I can't imagine what's causing this... I'll try to compile lastest release without modifications to see if the problem remains.

**Comment by CaosJunior** [comment]
I can't compile lastest release with CodeBlocks, so I downloaded VS17 but I'm getting this errors:
https://prnt.sc/j9zz9p
How can I solve them?

**Comment by diath** [comment]
If you're using the OTC SDK you will have to build the release version instead because two libs from the SDK have been compiled with wrong runtime in debug mode.

**Comment by CaosJunior** [comment]
Thanks.
Unfortunately, the problem remains, take a look: http://prntscr.com/ja0xam
After walking 1 SQM: http://prntscr.com/ja0xqe

Using OTC 0.6.7 latest release compiled with VS17 on Windows 10 and TFS 0.3.6pl1 8.54 compiled with DevCpp, also on Windows 10.

**Comment by diath** [comment]
It must be an issue with your server then, I just tested with current master (4007980c0ccbb0213c170e299b5b6da99c94ebc0) and summons appear on the battle list instantly without moving first - unless it's a protocol issue. As for summon icons, it has been added in protocol version 10.x.

**Comment by CaosJunior** [comment]
As far as is remember, it happens with almost all 8.54 servers (at least with ATS), the only one I saw without this bug is DxP, but it has so many bugs that it's not worth to use as base. I compared DxP OTC sources with mine and probably it's an issue with my server, I'll compare DxP server sources with mine and see if I find something (I'll also try to get the summon icon working on my server, DxP is 8.54 and it has summon icon).
