### ISSUE TITLE
Errors when trying to use runes, the client

### ISSUE THREAD

**Issue by 280411** [edubart/otclient#969]
Well, first of all I'm sorry for my English, it's not good, but come on, when I try to use runes, all of them, I'm having a problem, I've already changed the database, I've already changed .dat, I've done everything myself so I do not get results, since I did not find any post, I decided to create for some help return, here is the ERROR:

`
ERROR: ProtocolGame parse message exception (4492 bytes unread, last opcode is 100, prev opcode is 11): unable to create item with invalid id 41215
WARNING: widget 'tab' destroyed but still have 1 reference(s) left
WARNING: widget 'tab' destroyed but still have 1 reference(s) left
ERROR: ProtocolGame parse message exception (37 bytes unread, last opcode is 233, prev opcode is 120): unhandled opcode 233
ERROR: ProtocolGame parse message exception (18 bytes unread, last opcode is 150, prev opcode is 120): InputMessage eof reached
ERROR: ProtocolGame parse message exception (5 bytes unread, last opcode is 28, prev opcode is 106): unhandled opcode 28`

**Comment by EgzoT** [comment]
[Before add issue read this](https://github.com/edubart/otclient/blob/master/ISSUE_TEMPLATE.md)

> "I've already changed the database, I've already changed .dat, I've done everything myself so I do not get results, since I did not find any post"

So you edited source/.dat or something else? But we here solve problems only from this repository.
So if you edited .dat file, first you must check is it working.

**Comment by 280411** [comment]
No, I did not change the DAT, but the last time I had a bug, but I was looking for this and I saw that this error did not belong to the client, until then I tested the client on an old tibia client

**Comment by EgzoT** [comment]
But you don't write what client version you use. In fact in OTClient protocol +/- 7.6 have some problems with ProtocolGame parse message.

Read ISSUE_TEMPLATE.md and edit this issue.

**Comment by 280411** [comment]
TFS 0.3.6, Otclient 0.6.3

**Comment by EgzoT** [comment]
I have seen too that problem in very modified servers. But I was thinking that is problem with 7.6 protocol.

This may help you:
[ServerOpcodes](https://github.com/edubart/otclient/blob/a6a50fa1624f38fc173f79abdfcafcb29c42c354/modules/gamelib/protocol.lua)

Here you find what type of bytes your OTClient don't read.

**Comment by 280411** [comment]
Oh thanks, this problem was happening due to a modification made in the game_interface, which when giving usewith, all functions related to it, gave problems
