### ISSUE TITLE
[OTC 0.6.7][TFS 0.3.6 8.54] Character Dissapears

### ISSUE THREAD

**Issue by CaosJunior** [edubart/otclient#970]
I'm having some very weird problems using OTC with TFS 0.3.6, I'm using lastest otclient-master.zip and the only thing I changed on it is Distance Missiles to U16 (changing **int shotId = msg->getU8();** to **int shotId = msg->getU16();** in **protocolgameparse.cpp** and adding line **Gam﻿eDistanceMissileU16 = 77,** in **const.h** before **LastGameFeature = 101﻿**), in things.lua I use the following GameFeatures:
`g_game.enableFeature(GameDiagonalAnimatedText)
g_game.enableFeature(GameMagicEffectU16)
g_game.enableFeature(GameDistanceMissileU16)
g_game.enableFeature(GameSpritesU32)
g_game.enableFeature(GameBlueNpcNameColor)`
The problem is, in some parts of the map (or even some especific SQMs with nothing different from the others) the character (or summon) becomes invisible and I get this spam in terminal: http://prntscr.com/jdc8ih other print: http://prntscr.com/jdcf0p
In server sources I didn't change anything related to creature movement, I have no idea on why this is happening...

Edit: In case it makes any difference, I have extended Magic Effects and Shoot Effect in server sources.

**Comment by CaosJunior** [comment]
Nobody answered so... Anyone knows if this bug is server sided or client sided? If it's server side, I'll try to get clean sources and make some tests.

**Comment by Felipe1993** [comment]
Try to get Corán src and check
