### ISSUE TITLE
Randomly client lag on teleport.

### ISSUE THREAD

**Issue by Anastaciaa** [edubart/otclient#973]
Sometimes when i travel in the captain NPC the client lag and this error appear in terminal:

>>ERROR: invalid encrypted network message
>>at:
>>   [C++]: ?xteaDecrypt@Protocol@@AAE_NABV?$shared_object_ptr@VInputMessage@@@stdext@@@Z
>>ERROR: failed to decrypt message
>>at:
>>    [C++]: ?internalRecvData@Protocol@@AAEXPAEG@Z

**Comment by okk3** [comment]
Hello @Anastaciaa,

what server are you using?

Best Wishes,
Okke

**Comment by Anastaciaa** [comment]
Othire

**Comment by okk3** [comment]
Did you add more tiles to the client, did any modification for the protocol or are you using the latest OTC revision?

**Comment by Anastaciaa** [comment]
I didn't add more tiles, i did some changes in the client also im using 7.72 tibia client version.

**Comment by okk3** [comment]
Please state the changes you've done, it's more likely that the problem is there than in the latest revision. :D

**Comment by Anastaciaa** [comment]
I recorded small video, sometimes teleport works normally and sometimes is client lag and error.
https://www.youtube.com/watch?v=gjxOWN_V0fY

This was the first error but later it wont appear:
>>ERROR: ProtocolGame parse message exception (0 bytes unread, last opcode is 100, prev opcode is 108): InputMessage eof reached

I think this guy had same issue:
https://otland.net/threads/random-place-player-freezing.237804/

**Comment by Anastaciaa** [comment]
The weird part is when i call this teleport function from talkactions it works normally but when i call it form npc like this one Cobra it doesnt work:
doTeleportThing(cid,{x=33397, y=32836, z=14, stackpos=1})
