### ISSUE TITLE
Ping is not working [OThire 0.0.3 - 7.72]

### ISSUE THREAD

**Issue by rrodriguesrm** [edubart/otclient#979]
Hello, i'm trying to use OTC stock from this git with OThire 0.0.3, but ping is not working, the "Ping:" tag doesnt appear. Is there some incompatibilitie with OThire - OTC?

**Comment by EgzoT** [comment]
First, check is your server support ping system.

**Comment by rrodriguesrm** [comment]
Yes, I saw the source code on game.cpp, but its why i'm asking, is there some incompatibilitie with othire?

**Comment by okk3** [comment]
It mostly won't work with any TFS 0.x version, be it 0.3, 0.4 or 0.5.

**Comment by Anastaciaa** [comment]
OTClient ping system doesn't work properly and shows wrong ping and jumps like unstable value. I recommend you to make only client side ping system like tibianic old client did. I've already made that  works but the function freezes client for some milisecond on every excute. Maybe someone here will find a solution for this:
game.cpp
https://pastebin.com/v5C5r5LD

**Comment by rrodriguesrm** [comment]
Amazing job @Anastaciaa 
Will try to find a soluticon for freezes...

**Comment by Anastaciaa** [comment]
I already found a solution. You have to call the function ping in separate thread.

**Comment by okk3** [comment]
@Anastaciaa What about you make a PR for this? That'd be lovely.

**Comment by Anastaciaa** [comment]
@okk3 You can do it if you want.

**Comment by rrodriguesrm** [comment]
How I do it @Anastaciaa ?

**Comment by Felipe1993** [comment]
@Anastaciaa  what you means with this? "You have to call the function ping in separate thread."
i dont understand and i want to add ping functions to my otc and make a PR too

**Comment by Anastaciaa** [comment]
Search for Calling functions asynchronous method in google.

**Comment by Felipe21** [comment]
> OTClient ping system doesn't work properly, shows wrong ping and jumps like unstable value. I recommend you to make only client side ping system like tibianic old client did. I've already made that works but the function freezes client for some milisecond on every excute. Maybe someone here will find a solution for this:
> game.cpp
> https://pastebin.com/xUu8nJnT
> Also register it in lua functions:
> 
> > g_lua.bindSingletonFunction("g_game", "getNewPing", &Game::getNewPing, &g_game);
> 
> Usage in lua scripts:
> 
> > print(g_game.getNewPing("85.45.205.2")) -- change ip

mate can you tell me where should i put or register the lua functions and the lua scripts usage?

**Comment by Anastaciaa** [comment]
this:
>> g_lua.bindSingletonFunction("g_game", "getNewPing", &Game::getNewPing, &g_game);
to: client/luafunctions.cpp
this:
>> https://pastebin.com/xUu8nJnT
to: src/client/game.cpp
and register getNewPing(const std::string& ip) in game.h

**Comment by angeliker** [comment]
@Anastaciaa i have to replace all from game.cpp with the little code you posted here? or i should add it somewhere :P about this ---> getNewPing(const std::string& ip) i have to put it in game.h too but where it says IP i have to put my ip? numeric or domain ones

**Comment by AninhaPaula** [comment]
@Anastaciaa does not exist #include <framework/platform/platformwindow.h> to add below in game.cpp

**Comment by Felipe21** [comment]
@Anastaciaa 
where should i put this? in which folder? or lua file?
print(g_game.getNewPing("85.45.205.2")) -- change ip

**Comment by Anastaciaa** [comment]
>function updatePing(ping)
change:
>pingLabel:setText(text)
to 
>pingLabel:setText(g_game.getNewPing("85.45.205.2"))

**Comment by angeliker** [comment]
> gameinterface.lua
> function updatePing(ping)
> change:
> pingLabel:setText(text)
> to:
> pingLabel:setText(g_game.getNewPing("85.45.205.2"))

when you do that the client wont log ingame, when you select the character it just stay like loading and nothing happend

**Comment by Anastaciaa** [comment]
ctrl+t and check for errors

**Comment by angeliker** [comment]
> ctrl+t and check for errors

the problem is that the client i'm using dont have that option since it has removed alot of things to make it feels like a real tibia client so :/
https://otland.net/threads/otclient-7-4-with-real-tibia-features.256423/

**Comment by CristoferMartins** [comment]
Just a input in the subject, the tibia flash client had a good implementation of how to calc the ping using the client/server ping messages(no need for external socket/protocol/whatever).

**Comment by okk3** [comment]
@CristoferMartins do you have either the source or a snippet for that implementation? If it's neat enough I'll do a PR myself.

Best WIshes,
Okke

**Comment by CristoferMartins** [comment]
https://github.com/OXGaming/TibiaFlashClient/blob/master/scripts/tibia/network/Connection.as#L747 and https://github.com/OXGaming/TibiaFlashClient/blob/master/scripts/tibia/network/Connection.as#L873
