### ISSUE TITLE
Chat bug

### ISSUE THREAD

**Issue by EaiComeu** [edubart/otclient#984]
Hello
Some players are suffering from the following bug
![image](https://user-images.githubusercontent.com/3253837/43332331-7edc698a-919e-11e8-9268-a13084ce31dd.png)
The chat no work, how can I fix ?

**Comment by EgzoT** [comment]
Look at this: [Issue Template](https://github.com/edubart/otclient/blob/master/ISSUE_TEMPLATE.md)

**Comment by EmersonHenriique** [comment]
Qual é esse server ? Passa Link ae :)
