### ISSUE TITLE
Error in Login.

### ISSUE THREAD

**Issue by inexperientegame** [edubart/otclient#985]
At the moment I'm going to log in the following error occurs:
Your connection has been lost.
Either you network or the server went down. (ERROR 2)

I put the correct account and password
the Ip and the port is correct.

The server version is 772 and I'm using it myself.

What could be happening?

**Comment by Anastaciaa** [comment]
Rsa key

**Comment by mikhael4ever** [comment]
How can i edit the RSA  ?
