### ISSUE TITLE
Diagonal Movement Bug/Autowalk (OTH/OTXServer)

### ISSUE THREAD

**Issue by cjrz74** [edubart/otclient#993]
stock OTH/OTXServer , compile stock OTC
weird glitch while running with diagonal keys
https://streamable.com/2c4xm
### Expected behaviour
correct smooth walking
### Actual behaviour
Diagonal movement bug/walk animation bug?
### Environment
OTH, OTXServer, (7.7)

**Comment by Aerwix** [comment]
This bug has been detected many times, usually, when the characters get more level, the sensation disappear but not completely.

Even servers like PokeXGames cannot fix this. :(

**Comment by iryont** [comment]
It's a duplicate of an issue already reported.
