### ISSUE TITLE
Cannot open include file: 'boost/thread/future.hpp'

### ISSUE THREAD

**Issue by ricardoianelli** [edubart/otclient#994]
I've followed the [Compiling on Windows](https://github.com/edubart/otclient/wiki/Compiling-on-Windows) tutorial on a just formatted PC but i've stuck on those errors:

<img width="960" alt="erros otclient" src="https://user-images.githubusercontent.com/2482654/47124917-ef620900-d256-11e8-8fcb-573d8946cb5f.png">

I noticed the tutorial is very similar to the [Forgottenserver](https://github.com/otland/forgottenserver) compilation tutorial, but that one compiled just fine, i only get errors on compiling otclient.
Does anybody know what could i do?

Ps.: I've already installed (via VS17) the VS15 workload. 
<img width="552" alt="aasa" src="https://user-images.githubusercontent.com/2482654/47125035-921a8780-d257-11e8-996b-23ef40c7415a.png">

**Comment by ricardoianelli** [comment]
Thanks @okk3 ! But i don't have it installed. I just formatted my PC, installed VS17, downloaded VS13,15,17 c++ redist, downloaded the vcpkg following the tutorial and tried to compile. I have to download boost too? On the vcpkg folder i noticed A LOT of "boost" folders, but don't know which one to use:
<img width="320" alt="sem titulo" src="https://user-images.githubusercontent.com/2482654/47226685-80d89480-d397-11e8-9bc8-bb50b7fcda16.png">

**Comment by soul4soul** [comment]
Since you are using vcpkg you **don't** need to install boost separately.

**Comment by ricardoianelli** [comment]
@soul4soul Sure, but what boost do I need to include on properties -> c++ -> additional includes?
Because it's not compiling. The TFS is compiling with no problems, but otclient just don't and i don't know what to do. :(

**Comment by ras0219-msft** [comment]
@ricardoianelli Have you run `.\vcpkg integrate install`?

If so, could you set the output verbosity to Normal:
Tools -> Options -> Build and Run -> MSBuild project build output verbosity -> Normal

Then do a clean rebuild. In the output window, there should be a message like:
```
1>Target VcpkgTripletSelection:
1>  Using triplet "x86-windows" from "D:\src\vcpkg\installed\x86-windows\"
```

If you don't see this, then there's definitely an issue.

**Comment by ricardoianelli** [comment]
@ras0219-msft Now i did the following:

- Cloned otclient again.
- When asked by Visual Studio if I want to upgrade my project to the last version of VS, i said YES. 
- Changed Output verbosity to Normal.
- Did a clean rebuild.

Now the:

`1>Target VcpkgTripletSelection:
1>  Using triplet "x64-windows" from "C:\Users\User\Zodiac\vcpkg\installed\x64-windows\"`

Shows up, but i still get errors:
https://pastebin.com/dRbSWtNv

`1>    485 Warning(s)
1>    1 Error(s)`

The error is:

`Error	C1083	Cannot open include file: 'al.h': No such file or directory (compiling source file ..\src\framework\core\graphicalapplication.cpp)	otclient	c:\users\user\zodiac\otclient\src\framework\sound\declarations.h	30	
`

**Comment by ras0219-msft** [comment]
`vcpkg install openal-soft` does provide `al.h`, but we prefix it as `AL/al.h`:

```
D:\src\vcpkg2> vcpkg owns /al.h
openal-soft:x86-windows: x86-windows/include/AL/al.h
```

Not sure if otclient is expecting to get it from somewhere else; you could probably hack it to work by explicitly adding that subdirectory (`include/AL/`) to the project include settings, but it would be better to just tweak the #include.

**Comment by ricardoianelli** [comment]
Changed the #include "al.h" and "alc.h" to "AL/al.h" and "AL/alc.h".
Now i have those errors:

<img width="960" alt="errors3" src="https://user-images.githubusercontent.com/2482654/47250412-e6a83900-d3f6-11e8-9446-91cf3791dfbf.png">

**Comment by marmichalski** [comment]
Apply connection.h changes from this MR: https://github.com/edubart/otclient/pull/981/files#diff-ddfc51dd0c629eb213097cceeeb6c2d7

**Comment by ricardoianelli** [comment]
> Apply connection.h changes from this MR: https://github.com/edubart/otclient/pull/981/files#diff-ddfc51dd0c629eb213097cceeeb6c2d7

```
1>    840 Warning(s)
1>    0 Error(s)
1>
1>Time Elapsed 00:04:34.95
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
```

#981 solved the issue! Thank you VERY much!!!
