### ISSUE TITLE
Won't compile in Debug mode.

### ISSUE THREAD

**Issue by ricardoianelli** [edubart/otclient#995]
The issues are:
* Using VS17 and vcpkg and compilling normally in Release mode (x64 and Win32).

- When selected "Debug" mode and x64 i get tons of errors like the "Color" class not existing.
- When selected "Debug" more and Win32 i got the following error:
`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'glew32.lib'	otclient	C:\Users\User\Zodiac\otclient\vc14\LINK	1	
`

**Comment by Oen44** [comment]
Still a thing, any fix for that?
