### ISSUE TITLE
Sprite stack position

### ISSUE THREAD

**Issue by theshibbies** [edubart/otclient#996]
Using latest OTC and protocol 10.98, having an issue with rendering some sprites. For example in image you can see on the west wall the torch is showing underneath the stairs but on north wall the issue doesn't happen. Both are identical in object builder and item editor and I've tried many different flags to resolve the issue but no luck.

![untitled](https://user-images.githubusercontent.com/43316702/48266243-d1726900-e3fc-11e8-872b-dda56c0bfbca.png)

**Comment by iryont** [comment]
That's how the game client draws tiles. Whether it is a bug or not is up to the user. Anyway, please follow the template of an issue next time. You can find the code responsible for drawing tiles in a specific order here:

https://github.com/edubart/otclient/blob/master/src/client/mapview.cpp#L321
