### ISSUE TITLE
Get lib via VCPKG

### ISSUE THREAD

**Issue by TorchwoodPL** [edubart/otclient#997]
When I try to use: vcpkg install boost-iostreams:x64-windows boost-asio:x64-windows boost-system:x64-windows boost-variant:x64-windows boost-lockfree:x64-windows luajit:x64-windows glew:x64-windows boost-filesystem:x64-windows boost-uuid:x64-windows physfs:x64-windows openal-soft:x64-windows libogg:x64-windows libvorbis:x64-windows zlib:x64-windows I get:

```
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: E:/Lib/vcpkg/installed/x64-windows/tools/boost-build/b2.exe;--stagedir=E:/Lib/vcpkg/buildtrees/boost-system/x64-windows-rel/stage;--build-dir=E:/Lib/vcpkg/buildtrees/boost-system/x64-windows-rel;--user-config=E:/Lib/vcpkg/buildtrees/boost-system/x64-windows-rel/user-config.jam;-j4;--debug-configuration;--debug-building;--debug-generators;--disable-icu;--ignore-site-config;--hash;-q;-sZLIB_INCLUDE="E:/Lib/vcpkg/installed/x64-windows/include";-sBZIP2_INCLUDE="E:/Lib/vcpkg/installed/x64-windows/include";threading=multi;threadapi=win32;runtime-link=shared;link=shared;address-model=64;architecture=x86;toolset=msvc-14.0;-sZLIB_BINARY=zlib;-sZLIB_LIBPATH="E:/Lib/vcpkg/installed/x64-windows/lib";-sBZIP2_BINARY=bz2;-sBZIP2_LIBPATH="E:/Lib/vcpkg/installed/x64-windows/lib";variant=release;debug-symbols=on
    Working Directory: E:/Lib/vcpkg/buildtrees/boost-system/src/ost-1.68.0-6f52f8464b/build
    See logs for more information:
      E:\Lib\vcpkg\buildtrees\boost-system\build-x64-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:270 (vcpkg_execute_required_process)
  ports/boost-system/portfile.cmake:14 (boost_modular_build)
  scripts/ports.cmake:71 (include)


Error: Building package boost-system:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-system:x64-windows
  Vcpkg version: 2018.10.20-nohash

Additionally, attach any relevant sections from the log files above.
```

Also attach log file. Any idea what could be wrong?
[build-x64-windows-rel-out.log](https://github.com/edubart/otclient/files/2568970/build-x64-windows-rel-out.log)

**Comment by ras0219-msft** [comment]
>'mt' is not recognized as an internal or external command, operable program or batch file.

What OS/VS version do you have?

**Comment by okk3** [comment]
Hello, do not use VCPKG, go for VS15, here's all you're going to need: https://github.com/edubart/otclient/wiki/Compiling-on-Windows/27f53225ebeeaabb93a9a5431f9acbef557565ec

Best Wishes,
Okke

**Comment by TorchwoodPL** [comment]
> > 'mt' is not recognized as an internal or external command, operable program or batch file.
> 
> What OS/VS version do you have?

Windows 10

**Comment by TorchwoodPL** [comment]
> Hello, do not use VCPKG, go for VS15, here's all you're going to need: https://github.com/edubart/otclient/wiki/Compiling-on-Windows/27f53225ebeeaabb93a9a5431f9acbef557565ec
> 
> Best Wishes,
> Okke

why so?
