### ISSUE TITLE
OTHire

### ISSUE THREAD

**Issue by rrodriguesrm** [edubart/otclient#999]
Hello, is it possible use OTC + OTH? I'm having some "lag" issues, like little rollback on movements, and I know that OTC was developed to work with TFS.

**Comment by Anastaciaa** [comment]
Yes is is

**Comment by rrodriguesrm** [comment]
What about this walking issues @Anastaciaa ? I saw that only few OTS has it working good... But no commits on main repository, sad

**Comment by divinity76** [comment]
i assume "OTC" means `otclient`, but what is `OTH` ?

**Comment by divinity76** [comment]
if OTHire is using the 7.72 tibia protocol, yeah it should work fine.
